import assert from "node:assert/strict";
import fs from "node:fs";

const read = (path: string) => fs.readFileSync(path, "utf8");
const proxy = read("src/proxy.ts");
const pvp = read("src/app/api/pvp/[code]/route.ts");
const matchmaking = read("src/app/api/matchmaking/route.ts");
const ranked = read("src/app/api/ranked/route.ts");
const playerSession = read("src/lib/player-session.ts");
const siteAdmin = read("src/app/api/admin/site/[resource]/[slug]/route.ts");
const sitePublic = read("src/app/api/public/site/[resource]/[slug]/route.ts");
const sitePublish = read("src/app/api/admin/site/[resource]/[slug]/publish/route.ts");
const publicCards = read("src/app/api/public/game/cards/route.ts");
const publicKeywords = read("src/app/api/public/game/keywords/route.ts");
const publicRulesContracts = read("src/app/api/public/game/rules/contracts/route.ts");
const publicAlphaReadiness = read("src/app/api/public/game/alpha/readiness/route.ts");
const publicDeploymentProvenance = read("src/app/api/public/game/deployment/provenance/route.ts");

assert.match(proxy, /requestOriginAllowed/);
assert.match(proxy, /x-request-id/);
assert.match(proxy, /cache-control/);
assert.match(playerSession, /requireStablePlayerIdentity/);
assert.match(pvp, /A valid actionId is required/);
assert.match(pvp, /pvpActionReceipts/);
assert.match(pvp, /for\("update"\)/);
assert.match(pvp, /applyAuthoritativePvpSnapshotAction/);
assert.match(matchmaking, /skipLocked:\s*true/);
assert.match(matchmaking, /activeRoom/);
assert.match(matchmaking, /resumed:\s*true/);
assert.match(ranked, /RANKED_SETTLEMENT_PVP_ONLY/);
assert.match(ranked, /settlePvpRoom/);
assert.match(siteAdmin, /isAdminAuthorized/);
assert.match(siteAdmin, /parseExpectedSiteVersion/);
assert.match(siteAdmin, /pg_advisory_xact_lock/);
assert.match(sitePublish, /canPublishSiteContent/);
assert.match(sitePublic, /site-content-public/);
assert.match(publicCards, /toPublicCardDto/);
assert.match(publicCards, /getCardCollection/);
assert.doesNotMatch(publicCards, /isAdminAuthorized|unauthorized/);
assert.match(publicKeywords, /buildPublicKeywordCatalog/);
assert.match(publicKeywords, /adminKeywords\.enabled/);
assert.doesNotMatch(publicKeywords, /isAdminAuthorized|unauthorized/);
assert.match(publicRulesContracts, /buildPublicRulesContracts/);
assert.match(publicRulesContracts, /collectibleCards/);
assert.match(publicRulesContracts, /getCardCollection/);
assert.doesNotMatch(publicRulesContracts, /isAdminAuthorized|unauthorized/);
assert.match(publicAlphaReadiness, /buildPublicAlphaReadiness/);
assert.match(publicAlphaReadiness, /runtimeStatus/);
assert.doesNotMatch(publicAlphaReadiness, /isAdminAuthorized|unauthorized/);
assert.match(publicDeploymentProvenance, /readDeploymentProvenance/);
assert.match(publicDeploymentProvenance, /APP_RELEASE/);
assert.doesNotMatch(publicDeploymentProvenance, /isAdminAuthorized|unauthorized|DATABASE_URL|ADMIN_|PAYMENT_|SECRET/);

console.log("API CONTRACT REGRESSION: PASS");
