import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";

const root=process.cwd();
const read=(file:string)=>fs.readFileSync(path.join(root,file),"utf8");

const route=read("src/app/api/commander/[code]/route.ts");
const bridge=read("src/lib/commander-combat.ts");
const client=read("src/app/commander/CommanderClient.tsx");
const commanderSchema=read("src/db/schema/commander.ts");
const coreTypes=read("src/game/types.ts");
const spellContract=read("src/game/four-player-spell-contract.ts");
const effectZones=read("src/game/four-player-effect-zones.ts");
const battlefield=read("src/game/four-player-battlefield.ts");
const cardPlay=read("src/game/four-player-card-play.ts");

assert.match(route,/createCommanderCombatEnvelope/,"room start must create the recovered combat envelope");
assert.match(route,/commanderCombatPersistence/,"combat state must persist through the Commander bridge");
assert.match(route,/projectCommanderCombatState/,"GET must expose a per-seat projection instead of private engine state");
assert.match(route,/action==="combat-command"/,"Commander endpoint must expose versioned combat commands");
assert.match(route,/for\("update"\)/,"Commander room transitions must retain PostgreSQL row locks");
assert.match(route,/expectedRevision!==room\.version/,"room version must fail closed on stale commands");
assert.match(route,/isCommanderCombatEnvelope\(room\.gameState\)/,"combat commands must reject incompatible persisted state");

assert.match(bridge,/processAuthoritativeFourPlayerCommand/,"bridge must use recovered #209 authority pipeline");
assert.match(bridge,/projectFourPlayerStateForSeat/,"bridge must preserve hidden-information projection");
assert.match(bridge,/EXPOSED_COMMANDS/,"only an explicit command allowlist may cross the public bridge");
assert.match(bridge,/pass_priority/);
assert.match(bridge,/cast_general/);
assert.match(bridge,/play_card/);
assert.match(bridge,/COMMANDER_COMBAT_ENGINE_VERSION = 2/, "state-shape expansion must fail closed on legacy Commander envelopes");
assert.match(bridge,/fourPlayerStackActionKind/, "bridge must project the authoritative 4P stack taxonomy");
assert.match(bridge,/fourPlayerStackItemIsUncounterable/, "stack projection must publish authoritative uncounterable state");
assert.match(bridge,/settleFourPlayerEffectZoneActions/, "ordered draw, mill and recall zone actions must settle through the bridge");
assert.match(bridge,/fourPlayerStackActionKind/, "bridge must project the authoritative 4P stack taxonomy");
assert.match(bridge,/stackTargetId/, "bridge must carry stack-target ids without trusting client card identity");
assert.match(bridge,/counteredStackItems/, "countered stack cards must settle through authoritative zones");
assert.match(bridge,/declare_attacker/);
assert.match(bridge,/declare_blocker/);
assert.match(bridge,/destroyedObjects/,"combat casualties must settle into authoritative zones");
assert.match(bridge,/stageFourPlayerCardCast/,"play_card must derive authoritative card identity from zones");
assert.match(bridge,/acceptAuthoritativeFourPlayerCommand/,"play_card must still consume the canonical revision/idempotency protocol");
assert.match(bridge,/end_turn/);
assert.match(bridge,/concede/);
assert.match(cardPlay,/semanticProactivePlayAllowed/, "Commander server must preserve reaction-only Trap timing");
assert.match(cardPlay,/semanticReactionAllowed/, "Commander server must preserve semantic reaction legality");

assert.match(client,/action:"combat-command"/,"Commander UI must use the versioned combat bridge");
assert.match(client,/expectedRevision:room\.combat\.revision/,"Commander UI must send authoritative expectedRevision");
assert.match(client,/crypto\.randomUUID\(\)/,"Commander UI commands need unique command ids");
assert.match(client,/combatCommand\("pass_priority"\)/);
assert.match(client,/combatCommand\("cast_general"\)/);
assert.match(client,/combatCommand\("play_card"/);
assert.match(client,/isFourPlayerSpellChainSupported/,"Commander UI must share the authoritative 4P spell contract");
assert.match(client,/legalCounterTargets/,"Commander UI must filter counters before offering stack targets");
assert.match(client,/uncounterable/,"Commander UI must honor authoritative uncounterable projection");
assert.match(client,/PERMANENT_TARGETS/,"Commander UI must expose permanent targeting for reaction spells");
assert.match(client,/archetypeKey!=="trap"/,"Commander UI must not offer semantic Traps proactively");
assert.match(client,/mill/,"Commander UI must request an explicit opponent for 4P mill");
assert.match(client,/negateSpell/,"Commander UI must expose the certified negateSpell subset");
assert.match(client,/Stack 4P/,"Commander UI must render the authoritative circular stack");
assert.match(client,/Responder/,"Commander UI must expose legal Fast\/Burst reaction affordances");
assert.match(client,/stackTargetId/,"Commander UI must send explicit stack targets for counters");
assert.match(client,/Selecionar alvo/);
assert.match(client,/Alvo da Spell/);
assert.match(client,/kind:"player"/);
assert.match(client,/kind:"battlefield"/);
assert.match(client,/combatCommand\("declare_attacker"/);
assert.match(client,/combatCommand\("declare_blocker"/);
assert.match(client,/Atacar P/);
assert.match(client,/Bloquear/);
assert.match(client,/Jogar/);
assert.match(client,/combatCommand\("end_turn"\)/);
assert.match(client,/combatCommand\("concede"\)/);
assert.match(client,/Passar prioridade/);
assert.match(client,/Conjurar General/);
assert.match(client,/Encerrar turno/);
assert.match(client,/Conceder partida/);

assert.match(spellContract,/FOUR_PLAYER_SUPPORTED_SPELL_EFFECT_KINDS/);
assert.match(spellContract,/negateSpell/);
assert.match(spellContract,/recall/);
assert.match(spellContract,/damagePermanent/);
assert.match(spellContract,/destroyPermanent/);
assert.match(spellContract,/mill/);
assert.match(effectZones,/return_to_hand/);
assert.match(effectZones,/millFourPlayerCards/);
assert.match(battlefield,/FourPlayerDurability/);
assert.match(battlefield,/applyFourPlayerPermanentDamage/);

assert.match(commanderSchema,/commander_rooms/);
assert.match(commanderSchema,/gameState: jsonb\("game_state"\)/);
assert.match(coreTypes,/export type PlayerId = "player" \| "ai"/,"1v1 PlayerId must remain binary and untouched");

console.log("COMMANDER 4P COMBAT POSTGRES BRIDGE SOURCE CONTRACT: PASS");
