import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";

const root=process.cwd();
const read=(file:string)=>fs.readFileSync(path.join(root,file),"utf8");

const client=read("src/app/commander/CommanderClient.tsx");
const battlefield=read("src/app/commander/CommanderBattlefield4P.tsx");
const phaserRuntime=read("src/app/commander/CommanderPhaserRuntime.tsx");
const phaserCombatFx=read("src/game/presentation/phaser/BattlefieldCombatFx.ts");
const packageJson=read("package.json");
const packageLock=read("package-lock.json");

assert.match(client,/CommanderBattlefield4P/,"Commander client must mount the cinematic 4P battlefield");
assert.match(client,/combat=\{combat\}/,"cinematic battlefield must consume the authoritative projected combat state");
assert.match(battlefield,/data-commander-battlefield="cinematic-v1"/,"battlefield must expose a stable visual certification marker");
assert.match(battlefield,/relativePosition\(runtime\.seat,viewer\)/,"four-seat layout must orient relative to the local viewer");
assert.match(battlefield,/CardView defId=\{object\.defId\} size="sm"/,"battlefield objects must reuse the certified card renderer");
assert.match(battlefield,/CardView defId=\{runtime\.general\.defId\}/,"General zone must reuse the certified card renderer");
assert.match(battlefield,/runeforge-card-back\.svg/,"opponent hidden hands and deck piles must use the certified card back");
assert.match(battlefield,/combat\.combat\.attackers\.map/,"battlefield must render authoritative attack routes");
assert.match(battlefield,/markerEnd="url\(#commander-arrow\)"/,"attack routes must retain directional arrows");
assert.match(battlefield,/data-commander-attack-fx="authoritative"/,"attack FX must be visibly marked as authoritative-state driven");
assert.match(battlefield,/type CombatMotion="attacking"\|"blocking"\|null/,"battlefield must model visual combat motion without changing gameplay state");
assert.match(battlefield,/combatMotionTransform/,"declared combatants must move toward the center using a presentation-only transform");
assert.match(battlefield,/data-commander-combat-motion/,"moving combatants must expose a stable visual motion marker");
assert.match(battlefield,/declaredAttackerIds=\{assignedAttackerIds\}/,"physical attacker movement must derive from authoritative declared attackers");
assert.match(battlefield,/declaredBlockerIds=\{assignedBlockerIds\}/,"physical blocker movement must derive from authoritative declared blockers");
assert.match(battlefield,/blockerByAttacker/,"attack FX must correlate blockers with authoritative attacker ids");
assert.match(battlefield,/data-commander-attack-blocked/,"blocked attacks must expose a distinct impact state");
assert.match(battlefield,/data-commander-block-route/,"blocker interception must retain a visible route to the collision point");
assert.match(battlefield,/deriveAuthoritativeResolutionFx/,"resolution FX must be derived from consecutive authoritative projections");
assert.match(battlefield,/combat\.revision<=previous\.revision/,"resolution FX must ignore stale or duplicate revisions");
assert.match(battlefield,/seatLife\(before\)-seatLife\(seat\)/,"Nexus damage FX must come from observed authoritative life deltas");
assert.match(battlefield,/afterHealth<beforeHealth/,"battlefield damage FX must come from observed authoritative health deltas");
assert.match(battlefield,/barrier===true&&after\.object\.combat\?\.barrier===false/,"Barrier break FX must require an authoritative true-to-false transition");
assert.match(battlefield,/graveyard\.some\(card=>card\.instanceId===id\)/,"graveyard departure FX must require exact physical instance identity");
assert.match(battlefield,/owner\.general\.zone!=="battlefield"/,"General departure FX must require the projected General to leave the battlefield");
assert.match(battlefield,/previousCombatRef=useRef<CombatState\|null>/,"resolution FX must compare projected revisions locally without gameplay mutation");
assert.match(battlefield,/data-commander-nexus-damage/,"Nexus damage must expose a stable visual evidence marker");
assert.match(battlefield,/data-commander-damage-fx/,"battlefield damage must expose a stable visual evidence marker");
assert.match(battlefield,/data-commander-barrier-break="true"/,"Barrier break must expose a stable visual evidence marker");
assert.match(battlefield,/data-commander-departure-fx="authoritative"/,"destroyed/departed card FX must be marked as authoritative-state driven");
assert.match(battlefield,/data-commander-camera-controls="local"/,"battlefield must expose local-only camera controls");
assert.match(battlefield,/data-commander-camera-zoom=\{cameraZoom\}/,"camera zoom must remain local presentation state");
assert.match(battlefield,/focusCamera\(target:"table"\|"stack"\|"self"\)/,"camera focus must be constrained to table, stack or local seat");
assert.match(battlefield,/scrollIntoView\(\{behavior:"smooth",block:"nearest",inline:"center"\}\)/,"camera focus must be DOM framing only");
assert.match(battlefield,/\(\[80,90,100\] as const\)/,"camera must retain bounded zoom presets");
assert.match(battlefield,/data-commander-camera-surface="table"/,"camera surface must expose a stable certification marker");

assert.doesNotMatch(battlefield,/effectivePower|applyFourPlayerBattlefieldDamage|advanceFourPlayerCombatStep/,"presentation must not recalculate authoritative combat resolution");


assert.match(battlefield,/stroke-dashoffset/,"attack routes must retain animated directional flow");
assert.match(battlefield,/attributeName="cx"/,"attack FX must retain a projectile moving from controller to defender");
assert.match(battlefield,/attributeName="r"/,"defending seat must retain an impact pulse driven by an authoritative attacker");

assert.match(battlefield,/NEXUS DA STACK/,"compact stack must retain an expandable authoritative physical surface");
assert.match(battlefield,/combat\.stack/,"stack presentation must be derived from projected server state");
assert.match(battlefield,/data-commander-stack-cards="physical"/,"stack must retain a physical layered-card presentation");
assert.match(battlefield,/data-commander-stack-top/,"stack must expose its visual top object");
assert.match(battlefield,/CardView defId=\{item\.defId\} size="sm"/,"stack card objects must reuse the certified CardView renderer");
assert.match(battlefield,/NÃO ANULÁVEL/,"stack physical presentation must preserve uncounterable state");

assert.match(battlefield,/runtime\.graveyard\.length/,"public graveyard counts must remain visible");
assert.match(battlefield,/runtime\.handCount/,"opponent hidden-hand presentation must use public counts only");
assert.match(battlefield,/function VisibleHand/,"local viewer must receive a real visible-hand presentation");
assert.match(battlefield,/runtime\.hand\?/,"visible hand must be driven only by the viewer-private projected hand");
assert.match(client,/data-commander-surface=\{matchPresented\?"table":"lobby"\}/,"Commander must expose a distinct fullscreen match surface instead of presenting the lobby above the battlefield");
assert.match(client,/matchPresented\?"h-screen w-screen overflow-hidden"/,"active Commander matches must claim the full viewport");
assert.match(client,/matchPresented\?"hidden":"mt-6 grid gap-4 md:grid-cols-2"/,"legacy lobby seat cards must be hidden while the match table is presented");
assert.match(client,/matchPresented\?"hidden":"border border-white\/10 bg-black\/20 p-5"/,"lobby controls must be hidden while the match table is presented");
assert.match(battlefield,/className="relative h-full w-full overflow-hidden bg-\[#02060b\]/,"four-seat arena must fill its match shell without laboratory horizontal scrolling");
assert.match(battlefield,/grid h-full w-full origin-center/,"unified four-seat arena geometry must fill the available viewport");
assert.match(battlefield,/selectedAttackerId/,"cinematic battlefield must support local attacker selection");
assert.match(battlefield,/selectedBlockerId/,"cinematic battlefield must support local blocker selection");
assert.match(battlefield,/onDeclareAttacker/,"cinematic battlefield must delegate attack commitment to its parent authority");
assert.match(battlefield,/onDeclareBlocker/,"cinematic battlefield must delegate block commitment to its parent authority");
assert.match(battlefield,/data-commander-nexus-target/,"opponent Nexus surfaces must become explicit attack targets");
assert.match(battlefield,/data-commander-seat-zone="integrated"/,"players must occupy integrated arena zones instead of four boxed mini-tables");
assert.match(battlefield,/data-commander-graveyard="pile"/,"graveyards must render as physical clickable piles");
assert.match(battlefield,/data-commander-graveyard-overlay/,"graveyard inspection must expand into a dedicated overlay");
assert.match(battlefield,/useState<80\|90\|100>\(100\)/,"unified arena must default to full-scale viewport usage");
assert.doesNotMatch(battlefield,/w-\[min\(38vw,460px\)\]/,"legacy four-mini-table seat cards must not return");

assert.match(client,/onDeclareAttacker=\{\(unitId,defendingSeat\)=>combatCommand\("declare_attacker"/,"Commander client must keep authoritative attack command ownership");
assert.match(client,/onDeclareBlocker=\{\(unitId,attackerId\)=>combatCommand\("declare_blocker"/,"Commander client must keep authoritative block command ownership");


assert.match(battlefield,/CommanderPhaserRuntime/,"Commander battlefield must mount the isolated Phaser presentation overlay");
assert.match(phaserRuntime,/void import\("phaser"\)/,"Phaser must load client-side behind the React boundary");
assert.match(phaserRuntime,/new Phaser\.Game/,"presentation overlay must instantiate a real Phaser.Game runtime");
assert.match(phaserRuntime,/projectAuthoritativeCombatDelta/,"Phaser runtime must consume the certified authoritative combat adapter");
assert.match(battlefield,/stack=\{combat\.stack\}/,"Commander battlefield must project the authoritative stack into Phaser");
assert.match(phaserRuntime,/STACK_EVENT="runeforged:commander:stack-fx"/,"Phaser stack FX must use an isolated presentation event");
assert.match(phaserRuntime,/lastStackRevisionRef/,"stack FX must deduplicate authoritative revisions");
assert.match(phaserRuntime,/entered=stack\.filter\(item=>!previousIds\.has\(item\.id\)\)/,"stack entry FX must derive only from authoritative item-id additions");
assert.match(phaserRuntime,/departed=previous\.filter\(item=>!currentIds\.has\(item\.id\)\)/,"stack departure FX must derive only from authoritative item-id removals");
assert.match(phaserRuntime,/playStackEntryFx\(this,source,target,item\.speed,item\.uncounterable\)/,"stack entry FX must preserve projected speed and uncounterable state");
assert.match(phaserRuntime,/playStackDepartureFx\(this,/,"stack departure must use a neutral presentation primitive");
assert.match(phaserCombatFx,/export function playStackEntryFx/,"shared Phaser FX must expose stack-entry presentation");
assert.match(phaserCombatFx,/export function playStackDepartureFx/,"shared Phaser FX must expose neutral stack-departure presentation");
assert.doesNotMatch(phaserRuntime,/COUNTERED|ANULADO|RESOLVED|RESOLVIDO/,"Phaser stack departure must not infer why an item left the authoritative stack");

assert.match(battlefield,/objectSeats:Record<string,number>/,"authoritative resolution FX must retain the seat of damaged or barrier-broken objects");
assert.match(battlefield,/resolutionFx=\{resolutionFx\}/,"Commander battlefield must pass only its observed authoritative resolution delta to Phaser");
assert.match(phaserRuntime,/RESOLUTION_EVENT="runeforged:commander:resolution-fx"/,"Phaser runtime must isolate authoritative resolution events from combat command frames");
assert.match(phaserRuntime,/lastResolutionRevisionRef/,"Phaser resolution FX must deduplicate already-rendered revisions");
assert.match(phaserRuntime,/const point=seatPoint\(seatNumber,viewerSeat\)/,"Nexus damage FX must resolve the authoritative damaged seat into the viewer-relative arena anchor");
assert.match(phaserRuntime,/playDamageImpactFx\(this,point,damage,"nexus"\)/,"Nexus damage FX must target that authoritative arena anchor");
assert.match(phaserRuntime,/playDamageImpactFx\(this,seatFxPoint\(seat,viewerSeat,index\),damage,"object"\)/,"object damage FX must use the authoritative object's seat");
assert.match(phaserRuntime,/playBarrierBreakFx\(this,seatFxPoint\(seat,viewerSeat,index\)\)/,"Barrier FX must use the authoritative object's seat");
assert.match(phaserRuntime,/playDepartureFx\(this,seatFxPoint\(departure\.seat,viewerSeat,index\),departure\.destination\)/,"departure FX must use the authoritative projected destination");
assert.match(phaserCombatFx,/export function playDamageImpactFx/,"shared Phaser FX must expose a damage impact primitive");
assert.match(phaserCombatFx,/export function playBarrierBreakFx/,"shared Phaser FX must expose a Barrier break primitive");
assert.match(phaserCombatFx,/export function playDepartureFx/,"shared Phaser FX must expose a departure primitive");
assert.doesNotMatch(phaserRuntime,/seatLife\(|battlefieldMap\(|deriveAuthoritativeResolutionFx|effectivePower|applyFourPlayerBattlefieldDamage|advanceFourPlayerCombatStep/,"Phaser runtime must render authoritative outcomes without recalculating combat");
assert.match(battlefield,/attackerIds:previous\.combat\.attackers\.map\(entry=>entry\.unitId\)/,"resolution presentation must carry authoritative attacker identities from the prior combat snapshot");
assert.match(battlefield,/blockerPairs:previous\.combat\.blockers\.map/,"resolution presentation must carry authoritative blocker pairings from the prior combat snapshot");
assert.match(phaserRuntime,/new Set\(fx\.blockerPairs\.map\(pair=>pair\.attackerId\)\)/,"Phaser may distinguish blocked impacts only from projected authoritative blocker pairs");
assert.match(phaserRuntime,/combat:resolution:attacker:/,"Phaser combat resolution must expose stable attacker-scoped presentation markers");
assert.doesNotMatch(phaserRuntime,/damage\s*[+\-*/]?=|health\s*[+\-*/]?=/,"Phaser combat presentation must not mutate or calculate gameplay damage or health");

assert.match(phaserRuntime,/playCombatLaneFx\(this,start,impact,"attackers"\)/,"attacker lanes must use the certified Phaser combat FX helper");
assert.match(phaserRuntime,/playCombatLaneFx\(this,start,impact,"blockers"\)/,"blocker lanes must use the certified Phaser combat FX helper");
assert.doesNotMatch(phaserRuntime,/const trail=this\.add\.line/,"Commander Phaser runtime must not duplicate combat lane rendering outside the shared helper");

assert.match(phaserRuntime,/viewerSeat:number/,"Phaser runtime must receive the local Commander viewer seat");
assert.match(phaserRuntime,/seatPoint\(route\.controllerSeat,viewerSeat\)/,"attacker FX must originate from its authoritative controller seat in local perspective");
assert.match(phaserRuntime,/seatPoint\(route\.defendingSeat,viewerSeat\)/,"attacker FX must target its authoritative defending seat in local perspective");
assert.match(phaserRuntime,/frame\.attackRoutes\.find\(entry=>entry\.unitId===route\.attackerId\)/,"blocker FX must bind to the exact authoritative attacker id");
assert.match(phaserRuntime,/collisionPoint\(attackerStart,defender\)/,"blocker FX must terminate at the authoritative attacker route collision point");
assert.match(battlefield,/viewerSeat=\{viewer\}/,"Commander battlefield must provide the viewer seat to the presentation-only Phaser overlay");
assert.match(battlefield,/prioritySeat:combat\.prioritySeat/,"Commander battlefield must project the authoritative priority seat into Phaser");
assert.match(battlefield,/activeSeat:combat\.activeSeat/,"Commander battlefield must project the authoritative active seat into Phaser");
assert.match(battlefield,/turn:combat\.turn/,"Commander battlefield must project the authoritative turn into Phaser");
assert.match(battlefield,/round:combat\.round/,"Commander battlefield must project the authoritative round into Phaser");
assert.match(battlefield,/phase:combat\.phase/,"Commander battlefield must project the authoritative phase into Phaser");
assert.match(phaserRuntime,/TURN_EVENT="runeforged:commander:turn-fx"/,"Phaser turn transitions must use an isolated presentation event");
assert.match(phaserRuntime,/previousTurnRef/,"Phaser turn presentation must compare consecutive authoritative turn projections");
assert.doesNotMatch(phaserRuntime,/end_turn|advanceFourPlayer|combatCommand|mutate\(/,"Phaser turn presentation must not own or advance authoritative turn progression");
assert.match(battlefield,/status:combat\.status/,"Commander battlefield must project authoritative match status into Phaser");
assert.match(battlefield,/winnerSeat:combat\.winnerSeat/,"Commander battlefield must project authoritative winner identity into Phaser");
assert.match(battlefield,/eliminatedSeats:combat\.seats\.filter\(seat=>seat\.eliminated\)/,"Commander battlefield must derive Phaser elimination presentation only from authoritative seat elimination flags");
assert.match(phaserRuntime,/OUTCOME_EVENT="runeforged:commander:outcome-fx"/,"match outcome FX must use an isolated presentation event");
assert.match(phaserRuntime,/previousOutcomeRef/,"Phaser outcome presentation must compare consecutive authoritative outcome projections");
assert.doesNotMatch(phaserRuntime,/\bconcede\b|advanceFourPlayer|combatCommand|mutate\(/,"Phaser outcome presentation must not own concede or advance authoritative match outcome");
assert.match(phaserRuntime,/PRIORITY_EVENT="runeforged:commander:priority-fx"/,"priority FX must use an isolated presentation event");
assert.match(battlefield,/targetingFx=\{\{/,"Commander battlefield must explicitly project targeting presentation state into Phaser");
assert.match(phaserRuntime,/TARGETING_EVENT="runeforged:commander:targeting-fx"/,"targeting FX must use an isolated presentation event");
assert.match(phaserRuntime,/selectedKind:"attacker"\|"blocker"\|null/,"targeting projection must distinguish attacker and blocker presentation");
assert.doesNotMatch(phaserRuntime,/declare_attacker|declare_blocker|pass_priority|combat-command/,"Phaser targeting and priority FX must not own authoritative Commander commands");

assert.match(phaserRuntime,/RF_BATTLEFIELD_THEME/,"Commander Phaser must inherit the certified RuneForged battlefield color language");
assert.match(phaserRuntime,/main:0x6ae8be/,"Commander main-phase presentation must preserve the certified 1v1 green token");
assert.match(phaserRuntime,/combat:0xfb923c/,"Commander combat presentation must preserve the certified 1v1 orange token");
assert.match(phaserRuntime,/response:0xa78bfa/,"Commander response presentation must preserve the certified 1v1 violet token");
assert.match(phaserRuntime,/arena:legacy-core/,"Commander Phaser must render a persistent RuneForged arena core");
assert.match(phaserRuntime,/arena:legacy-halo/,"Commander Phaser must render ambient arena energy");

assert.match(phaserRuntime,/arena:rune-ring:/,"Commander Phaser must retain persistent low-noise rune rings around the shared arena core");
assert.match(phaserRuntime,/arena:territory-spoke:/,"Commander Phaser must visually connect all four authoritative seats to the shared arena core");
assert.match(phaserRuntime,/arena:territory-lane:/,"Commander Phaser must retain readable presentation-only lanes between every seat and the shared Forge");
assert.match(phaserRuntime,/arena:territory-label:/,"Commander Phaser must keep compact seat-territory identity readable in still-frame showcase evidence");
assert.match(phaserRuntime,/local\?194:166/,"Commander Phaser must reserve enlarged sanctums for four-player showcase readability");
assert.match(phaserRuntime,/arena:seat-sanctum:/,"Commander Phaser must give each relative seat a persistent presentation-only territory");
assert.match(phaserRuntime,/arena:core-rune:/,"Commander Phaser must retain the legacy response color language in the shared ritual core");
assert.match(phaserRuntime,/arena:forge-plate/,"Commander Phaser must retain a persistent presentation-only Forge plate in the shared arena core");
assert.match(phaserRuntime,/arena:forge-crown/,"Commander Phaser must retain a persistent animated Forge crown without gameplay authority");
assert.match(phaserRuntime,/permanent:nexus-plate:/,"Commander Phaser must render premium Nexus plates from authoritative seat snapshots");
assert.match(phaserRuntime,/permanent:nexus-sigil:/,"Commander Phaser must keep Nexus identity readable in still-frame visual evidence");
assert.match(phaserRuntime,/permanent:general-plate:/,"Commander Phaser must give each authoritative General a premium presentation plate");
assert.match(phaserRuntime,/permanent:general-sigil:/,"Commander Phaser must retain a compact General sigil without changing General authority");
assert.match(phaserRuntime,/const radius=82\+\(index%2\)\*27/,"Commander Phaser must reserve a larger readable permanent orbit around every seat");assert.match(phaserRuntime,/arena:seat-anchor:/,"Commander Phaser must anchor all four seats into the shared battlefield");
assert.match(phaserRuntime,/turn:lane:/,"active-turn presentation must visually connect the authoritative seat to the arena core");
assert.match(phaserRuntime,/stack:arena-core-pulse/,"authoritative stack entry and resolution must energize the shared arena core");
assert.match(phaserRuntime,/permanent:nexus-halo:/,"each authoritative Commander seat must project a persistent Nexus halo");
assert.match(phaserRuntime,/seat\.nexusHealth<=10/,"Nexus presentation must derive critical state from authoritative health");
assert.match(phaserRuntime,/ELIMINADO/,"eliminated Commander seats must project a clear visual Nexus state");
assert.match(phaserRuntime,/permanent:general-presence:/,"a General on the battlefield must project distinct arena presence");
assert.match(phaserRuntime,/seat\.general\.castCount/,"General presentation must expose authoritative recast history");
assert.match(phaserRuntime,/combat:destination:/,"attack declaration must preserve a visible route from collision point to the authoritative defending Nexus");
assert.match(phaserRuntime,/combat:nexus-target:/,"attack declaration must identify the authoritative defending Nexus visually");
assert.match(phaserRuntime,/combat:block-collision:/,"block declarations must produce a distinct collision marker on the authoritative attack route");
assert.match(phaserRuntime,/GENERAL_EVENT="runeforged:commander:general-transition"/,"General transitions must consume a dedicated presentation event");
assert.match(phaserRuntime,/before\.zone===seat\.general\.zone/,"General FX must only fire after an authoritative zone transition");
assert.match(phaserRuntime,/general:transition:/,"General battlefield and General Zone movement must have a distinct cinematic projection");
assert.match(phaserRuntime,/nexus:impact:/,"authoritative Nexus damage must produce a seat-localized arena impact");
assert.match(phaserRuntime,/nexus:recoil:/,"authoritative Nexus damage must visually propagate between the damaged seat and shared arena core");
assert.match(phaserRuntime,/fx\.nexusDamage/,"Nexus impact presentation must remain sourced from authoritative resolution data");
assert.match(phaserRuntime,/data-commander-phaser-runtime="presentation-only"/,"Phaser overlay must expose its presentation-only certification marker");
assert.match(phaserRuntime,/pointer-events-none/,"Phaser overlay must not intercept gameplay input");
assert.match(packageJson,/"phaser": "4\.2\.1"/,"runtime must pin certified Phaser 4.2.1");
assert.match(packageLock,/"node_modules\/phaser"/,"runtime dependency must remain locked");
assert.doesNotMatch(phaserRuntime,/fetch\(|combatCommand|onDeclareAttacker|onDeclareBlocker/,"Phaser runtime must not own network or gameplay commands");
assert.match(phaserRuntime,/React battlefield remains active/,"Phaser runtime failure must preserve the React battlefield fallback");
assert.doesNotMatch(battlefield,/fetch\(/,"cinematic battlefield must remain a pure projection layer with no network authority");
assert.doesNotMatch(battlefield,/combatCommand|mutate\(/,"cinematic battlefield must not create a second command authority");
assert.match(battlefield,/groupEquivalentBattlefieldObjects/,"Commander battlefield must visually group equivalent repeated objects for dense boards");
assert.match(battlefield,/battlefieldVisualStateKey/,"visual stacking must split copies when authoritative state differs");
assert.match(battlefield,/enteredTurn:object\.enteredTurn/,"visual stacking must split summoning-sick copies from otherwise equivalent ready copies");
assert.match(battlefield,/attackable:attackableIds\.has\(object\.id\)/,"visual stacking must preserve per-instance attack readiness");
assert.match(battlefield,/blockable:blockableIds\.has\(object\.id\)/,"visual stacking must preserve per-instance block readiness");
assert.match(battlefield,/data-commander-visual-stack=/,"visual piles must expose their copy count");
assert.match(battlefield,/data-commander-stack-instance-ids=/,"visual piles must preserve every authoritative instance id");
assert.match(battlefield,/×\{group\.length\}/,"visual piles must show a visible copy count");
assert.match(battlefield,/data-commander-stack-copy=/,"expanded visual piles must preserve addressable individual copies");
assert.match(battlefield,/copyAttackable/,"expanded copies must preserve per-instance attack interaction");
assert.match(battlefield,/copyBlockable/,"expanded copies must preserve per-instance block interaction");

const commanderClient=read("src/app/commander/CommanderClient.tsx");
assert.match(commanderClient,/fetch\(\`\/api\/commander\/\$\{code\}\`,\{cache:"no-store",credentials:"include"\}\)/,"Commander recovery must reload the authoritative room snapshot with a no-store GET");
assert.match(commanderClient,/commanderSnapshotMayReplace\(currentRevision,incomingRevision\)/,"Commander recovery must reject stale authoritative snapshots");
assert.match(commanderClient,/clearPendingCombatIntent\(\);[\s\S]*await loadRoom\(code\)/,"Commander resync must clear transient local targeting before restoring the authoritative snapshot");
assert.match(commanderClient,/commanderResumeNeedsResync\("network_reconnect",navigator\.onLine\)/,"Commander must resync after network reconnect");
assert.match(commanderClient,/commanderResumeNeedsResync\("window_focus",navigator\.onLine\)/,"Commander must resync after window focus recovery");
assert.match(commanderClient,/commanderResumeNeedsResync\("visibility_resume",navigator\.onLine\)/,"Commander must resync after visible-tab recovery");
const resyncBody=commanderClient.slice(commanderClient.indexOf("const resyncRoom="),commanderClient.indexOf("useEffect(()=>{const id=window.setTimeout",commanderClient.indexOf("const resyncRoom=")));
assert.doesNotMatch(resyncBody,/combatCommand|method:"POST"|commandId|combat-command/,"Commander resync must never replay a gameplay command");
assert.match(commanderClient,/<CommanderBattlefield4P[\s\S]*combat=\{combat\}/,"Recovered authoritative combat snapshot must feed the Commander battlefield");

console.log("COMMANDER 4P CINEMATIC BATTLEFIELD SOURCE CONTRACT: PASS — relative four-seat table, certified CardView surfaces, hidden-hand projection, stack core and attack routes");
