import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
const root = process.cwd();
const read = (p: string) => fs.readFileSync(path.join(root, p), "utf8");
const schema = ["src/db/schema.ts","src/db/schema/gameplay.ts","src/db/schema/players.ts","src/db/schema/multiplayer.ts","src/db/schema/admin-content.ts","src/db/schema/admin-ops.ts"].map(read).join("\n");
const migration = read("drizzle/0019_engine_hardening_2_17.sql");
const spectator = read("src/app/api/pvp/[code]/spectate/route.ts");
const pvp = read("src/app/api/pvp/[code]/route.ts");
const pvpPublicState = read("src/lib/pvp-public-state.ts");
const draft = read("src/app/api/draft/route.ts");
const packs = read("src/app/api/packs/route.ts");
const cleanup = read("src/lib/session-cleanup.ts");
const playerSession = read("src/lib/player-session.ts");
const gameClient = read("src/app/play/GameClient.tsx");
const catalog = read("src/game/catalog.ts");
const replayViewer = read("src/app/replay/[id]/ReplayViewer.tsx");
const packsLib = read("src/lib/packs.ts");
const pkg = JSON.parse(read("package.json"));
const suites = read("scripts/test-suites.mjs");
assert.match(schema, /packSeed: integer\("pack_seed"\)/);
assert.match(schema, /contentVersion: text\("content_version"\)/);
assert.match(schema, /draftSessions[\s\S]*expiresAt: timestamp\("expires_at"\)/);
assert.match(schema, /pvpRooms[\s\S]*expiresAt: timestamp\("expires_at"\)/);
assert.match(migration, /ALTER TABLE draft_sessions ADD COLUMN IF NOT EXISTS expires_at/);
assert.match(migration, /ALTER TABLE pvp_rooms ADD COLUMN IF NOT EXISTS expires_at/);
assert.match(migration, /ALTER TABLE pack_openings ADD COLUMN IF NOT EXISTS pack_seed/);
assert.match(migration, /ALTER TABLE replays ADD COLUMN IF NOT EXISTS content_version/);
assert.match(spectator, /toSpectatorGameState/);
assert.doesNotMatch(spectator, /publicState\.players\[pid\]\.deck/);
assert.match(pvp, /sanitizeChat/);
assert.match(pvp, /applyAuthoritativePvpSnapshotAction/);
assert.match(pvp, /toPvpParticipantGameState/);
assert.match(pvpPublicState, /publicState\.players\[pid\]\.deck = publicState\.players\[pid\]\.deck\.map/);
assert.match(draft, /DRAFT_TTL_MS/);
assert.match(cleanup, /cleanupExpiredRuntimeSessions/);
assert.match(packs, /packSeed/);
assert.match(packs, /createPackRandom/);
assert.match(packsLib, /createPackRandom/);
assert.doesNotMatch(packs, /Math\.random/);
assert.equal(pkg.scripts["test:all"], "npm run test:behavior");
assert.match(suites, /behavioralTests[\s\S]*engine-hardening-2\.17\.test\.ts/);
assert.match(suites, /sourceContractTests[\s\S]*security-audit-2\.16\.test\.ts/);
assert.match(cleanup, /eq\(pvpRooms\.state, "playing"\)/);
assert.match(cleanup, /state: "expired"/);
assert.match(cleanup, /PVP_PLAYING_TTL_MS/);
assert.match(playerSession, /requireStablePlayerIdentity/);
assert.doesNotMatch(read("src/app/api/packs/route.ts"), /eq\(players\.name, identity\.playerName\)/);
assert.match(pvpPublicState, /publicState\.seed = 0/);
assert.match(pvpPublicState, /publicState\.rngState = 0/);
assert.match(pvpPublicState, /publicState\.idCounter = 0/);
assert.match(pvpPublicState, /for \(const pid of \["player", "ai"\]/);
assert.match(gameClient, /pendingSentinelaAbility/);
assert.match(gameClient, /type: "sentinela"[\s\S]*target \}/);
assert.match(catalog, /readCatalogRevision/);
assert.match(catalog, /cacheRevision/);
assert.match(replayViewer, /const timeline = useMemo/);
assert.match(replayViewer, /visibleTimeline/);
assert.match(replayViewer, /ENGINE EVENTS/);
assert.match(replayViewer, /Histórico Completo/);
assert.match(suites, /sourceContractTests[\s\S]*security-audit-2\.10\.test\.ts/);
assert.match(suites, /sourceContractTests[\s\S]*security-audit-2\.12\.test\.ts/);
assert.match(suites, /sourceContractTests[\s\S]*security-audit-2\.15\.test\.ts/);
console.log("HARDENING 2.17 REGRESSION: PASS");
