"use client";
import { useState } from "react";
import { useDeferredEffect } from "@/hooks/useDeferredEffect";
import { StudioBreadcrumb } from "../StudioChrome";

type S = { enabled:boolean; environment:"sandbox"|"production"; publicKey:string; statementDescriptor:string; revision:number; accessTokenConfigured:boolean; webhookSecretConfigured:boolean; accessTokenFingerprint?:string|null; webhookSecretFingerprint?:string|null };
export default function PaymentSettingsClient(){
  const [s,setS]=useState<S|null>(null),[accessToken,setAccessToken]=useState(""),[webhookSecret,setWebhookSecret]=useState(""),[currentPassword,setCurrentPassword]=useState(""),[currentTotp,setCurrentTotp]=useState(""),[msg,setMsg]=useState(""),[busy,setBusy]=useState(false),[orders,setOrders]=useState<any[]>([]);
  const load=async()=>{const [r,o]=await Promise.all([fetch("/api/admin/payments/settings",{credentials:"include"}),fetch("/api/admin/payments/orders",{credentials:"include"})]);const d=await r.json();const od=await o.json();if(d.ok)setS(d.settings);else setMsg(d.error||"Unauthorized");if(od.ok)setOrders(od.orders||[]);};
  useDeferredEffect(()=>{load().catch(()=>{});},[]);
  const save=async()=>{if(!s)return;setBusy(true);setMsg("");try{const r=await fetch("/api/admin/payments/settings",{method:"PATCH",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({...s,expectedRevision:s.revision,accessToken,webhookSecret,currentPassword,currentTotp})});const d=await r.json();if(d.ok){setS(d.settings);setAccessToken("");setWebhookSecret("");setMsg("✅ Mercado Pago salvo com step-up e segredos criptografados.");}else setMsg(`❌ ${d.error}`);}finally{setCurrentPassword("");setCurrentTotp("");setBusy(false);}};
  if(!s)return <main className="studio-shell"><StudioBreadcrumb section="Commerce" current="Payments"/><div className="panel">{msg||"Carregando…"}</div></main>;
  return <main className="studio-shell"><StudioBreadcrumb section="Commerce" current="Mercado Pago"/><div className="mb-6"><div className="text-xs font-black tracking-[.25em] text-cyan-300">REAL-MONEY COMMERCE</div><h1 className="mt-1 text-3xl font-black">Mercado Pago</h1><p className="mt-2 text-sm text-slate-400">Checkout Pro server-side. Access token e segredo do webhook nunca são devolvidos ao browser após salvar.</p></div>
  {msg&&<div className="mb-4 rounded-xl border border-white/10 p-3 text-sm">{msg}</div>}
  <section className="panel max-w-3xl space-y-4">
    <label className="flex items-center gap-2"><input type="checkbox" checked={s.enabled} onChange={e=>setS({...s,enabled:e.target.checked})}/><b>Gateway habilitado</b></label>
    <label><span className="label">Ambiente</span><select className="input" value={s.environment} onChange={e=>setS({...s,environment:e.target.value as any})}><option value="sandbox">Sandbox/Test</option><option value="production">Production</option></select></label>
    <label><span className="label">Public key</span><input className="input" value={s.publicKey} onChange={e=>setS({...s,publicKey:e.target.value})} placeholder="APP_USR-..."/></label>
    <label><span className="label">Novo access token {s.accessTokenConfigured?`(configurado · ${s.accessTokenFingerprint||"fingerprint"})`:"(obrigatório)"}</span><input className="input" type="password" autoComplete="new-password" value={accessToken} onChange={e=>setAccessToken(e.target.value)} placeholder={s.accessTokenConfigured?"deixe vazio para manter":"APP_USR-..."}/></label>
    <label><span className="label">Novo webhook secret {s.webhookSecretConfigured?`(configurado · ${s.webhookSecretFingerprint||"fingerprint"})`:"(obrigatório)"}</span><input className="input" type="password" autoComplete="new-password" value={webhookSecret} onChange={e=>setWebhookSecret(e.target.value)} placeholder={s.webhookSecretConfigured?"deixe vazio para manter":"secret de Webhooks"}/></label>
    <label><span className="label">Statement descriptor</span><input className="input" value={s.statementDescriptor} onChange={e=>setS({...s,statementDescriptor:e.target.value})}/></label>
    <div className="rounded-xl border border-amber-400/20 bg-amber-400/5 p-3 text-xs text-amber-100">Webhook: <code>{typeof location!=="undefined"?`${location.origin}/api/payments/webhook`:"/api/payments/webhook"}</code>. Configure esta URL no Mercado Pago e copie o segredo de assinatura para o campo acima.</div>
    <div className="rounded-xl border border-red-400/20 bg-red-400/5 p-4 space-y-3">
      <div><div className="text-xs font-black uppercase tracking-wider text-red-200">Reautenticação obrigatória</div><p className="mt-1 text-xs text-slate-400">Alterações no gateway afetam comércio com dinheiro real. Confirme suas credenciais atuais antes de salvar.</p></div>
      <label><span className="label">Senha atual do administrador</span><input className="input" type="password" autoComplete="current-password" value={currentPassword} onChange={e=>setCurrentPassword(e.target.value)} /></label>
      <label><span className="label">Código MFA / TOTP (se habilitado)</span><input className="input" inputMode="numeric" autoComplete="one-time-code" value={currentTotp} onChange={e=>setCurrentTotp(e.target.value.replace(/\D/g,"").slice(0,8))} /></label>
    </div>
    <button className="btn-primary" disabled={busy||!currentPassword} onClick={save}>{busy?"Salvando…":"Salvar / rotacionar credenciais"}</button>
  </section><section className="panel mt-6"><div className="mb-3 flex items-center justify-between"><div><h2 className="text-lg font-black">Últimas ordens</h2><p className="text-xs text-slate-400">Reembolso/chargeback após fulfillment exige revisão manual; o jogo não cria saldo negativo automaticamente.</p></div><button className="btn-ghost" onClick={()=>load().catch(()=>{})}>Atualizar</button></div><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead><tr className="text-slate-400"><th className="p-2">Produto</th><th>Status</th><th>Valor</th><th>Ambiente</th><th>Jogador</th><th>Data</th></tr></thead><tbody>{orders.map(o=><tr key={o.externalReference} className={o.requiresReview?"bg-red-500/10 text-red-200":"border-t border-white/5"}><td className="p-2">{o.productName}{o.requiresReview?" · ⚠ revisar":""}</td><td>{o.status}</td><td>{(o.amountCents/100).toLocaleString("pt-BR",{style:"currency",currency:o.currency})}</td><td>{o.environment}</td><td>#{o.playerId}</td><td>{new Date(o.createdAt).toLocaleString("pt-BR")}</td></tr>)}</tbody></table></div></section></main>;
}
