import { NextRequest } from "next/server";
import { db } from "@/db";
import { adminContentVersions } from "@/db/schema";
import { and, eq } from "drizzle-orm";
import { getAdminSessionContext, isAdminAuthorized, unauthorized, adminRoleAllowed } from "@/lib/admin-auth";
import { ENGINE_VERSION, RULESET_VERSION } from "@/game/version";
export const dynamic="force-dynamic";
function diff(a:any,b:any,prefix=""):any[]{const out:any[]=[];const keys=new Set([...Object.keys(a||{}),...Object.keys(b||{})]);for(const k of keys){const path=prefix?`${prefix}.${k}`:k;const av=a?.[k],bv=b?.[k];if(JSON.stringify(av)!==JSON.stringify(bv)){if(av&&bv&&typeof av==='object'&&typeof bv==='object'&&!Array.isArray(av)&&!Array.isArray(bv))out.push(...diff(av,bv,path));else out.push({path,before:av,after:bv});}}return out;}
export async function GET(req:NextRequest){if(!(await isAdminAuthorized(req)))return unauthorized();const actor=await getAdminSessionContext(req);if(!actor)return unauthorized();if(!adminRoleAllowed(actor.role,"qa"))return Response.json({ok:false,error:`Role ${actor.role} cannot access balance analysis`},{status:403});const resource=String(req.nextUrl.searchParams.get('resource')||'cards'),resourceId=Number(req.nextUrl.searchParams.get('resourceId')),va=Number(req.nextUrl.searchParams.get('versionA')),vb=Number(req.nextUrl.searchParams.get('versionB'));if(!Number.isInteger(resourceId)||!Number.isInteger(va)||!Number.isInteger(vb))return Response.json({ok:false,error:'resourceId, versionA and versionB are required.'},{status:400});const rows=await db.select().from(adminContentVersions).where(and(eq(adminContentVersions.resource,resource),eq(adminContentVersions.resourceId,resourceId)));const a=rows.find(r=>r.version===va),b=rows.find(r=>r.version===vb);if(!a||!b)return Response.json({ok:false,error:'One or both content versions were not found.'},{status:404});return Response.json({ok:true,resource,resourceId,versions:{a,b},diff:diff(a.snapshot,b.snapshot),provenance:{engineA:a.engineVersion||ENGINE_VERSION,engineB:b.engineVersion||ENGINE_VERSION,rulesetA:a.rulesetVersion||RULESET_VERSION,rulesetB:b.rulesetVersion||RULESET_VERSION,engineChanged:a.engineVersion!==b.engineVersion,rulesetChanged:a.rulesetVersion!==b.rulesetVersion}});}
