"use client";

import pkg from "../../../../../package.json";
import Link from "next/link";
import { useCallback, useMemo, useState } from "react";
import { useDeferredEffect } from "@/hooks/useDeferredEffect";

type CardRow = { defId:string; name:string; region:string; type:string; rarity:string; art:string|null; editorialArt:string|null; crop:any; missing:boolean };
type Variant = { url:string; mimeType:string; size:number; width:number; height:number } | null;
type Asset = { id:number; key:string; name:string; url:string; preferredUrl:string; preferredVariant:string; mimeType:string; width:number; height:number; size:number; status:string; variants:{original:Variant;webp:Variant;avif:Variant}; optimization:any };

export default function ArtPipelineClient() {
  const [cards,setCards]=useState<CardRow[]>([]), [assets,setAssets]=useState<Asset[]>([]), [coverage,setCoverage]=useState<any>(null);
  const [query,setQuery]=useState(""), [selected,setSelected]=useState(""), [assetId,setAssetId]=useState(0), [busy,setBusy]=useState(false), [notice,setNotice]=useState("");
  const [crop,setCrop]=useState({x:.5,y:.5,scale:1}), [variant,setVariant]=useState<"auto"|"original"|"webp"|"avif">("auto");
  const load=useCallback(async()=>{ const r=await fetch("/api/admin/studio/art",{credentials:"include",cache:"no-store"}); const d=await r.json(); if(d.ok){setCards(d.cards||[]);setAssets(d.assets||[]);setCoverage(d.coverage);} },[]);
  useDeferredEffect(()=>{void load();},[load]);
  const filtered=useMemo(()=>cards.filter(c=>!query||`${c.name} ${c.defId} ${c.region}`.toLowerCase().includes(query.toLowerCase())).slice(0,160),[cards,query]);
  const card=cards.find(c=>c.defId===selected); const asset=assets.find(a=>a.id===assetId);
  const selectedVariant = asset ? (variant==="auto" ? asset.variants.webp || asset.variants.original : asset.variants[variant]) : null;
  const previewUrl = selectedVariant?.url || asset?.preferredUrl || asset?.url || card?.art || "";
  const originalSize = asset?.variants.original?.size || asset?.size || 0;
  const variantSize = selectedVariant?.size || originalSize;
  const saving = originalSize > 0 && variantSize > 0 ? Math.max(0, Math.round((1 - variantSize/originalSize)*100)) : 0;
  const upload=async(file?:File)=>{ if(!file)return; setBusy(true); const form=new FormData();form.append("file",file);const r=await fetch("/api/admin/assets/upload",{method:"POST",credentials:"include",body:form});const d=await r.json();setBusy(false);if(d.ok){setNotice("Imagem enviada para a biblioteca.");await load();setAssetId(Number(d.row?.id||0));}else setNotice(d.error||"Upload falhou"); };
  const assign=async(action?:"clear")=>{ if(!card)return;setBusy(true);const r=await fetch("/api/admin/studio/art",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify(action?{defId:card.defId,action}:{defId:card.defId,assetId,crop,variant})});const d=await r.json();setBusy(false);setNotice(d.ok?"Arte atualizada no catálogo runtime.":d.error||"Falha ao atualizar arte");if(d.ok)await load(); };
  return <main className="min-h-screen bg-[#07101d] p-5 text-slate-100"><div className="mx-auto max-w-7xl"><header className="mb-5 flex flex-wrap items-center justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[.28em] text-amber-400">RUNEFORGE // {pkg.version}</p><h1 className="text-3xl font-black">Art Pipeline</h1><p className="mt-1 text-sm text-slate-400">Cobertura, crop, WebP/AVIF e override runtime sem rebuild.</p></div><div className="flex gap-2"><Link className="btn-ghost" href="/admin/studio/control">Total Control</Link><Link className="btn-ghost" href="/admin/studio/cards">Card Studio</Link></div></header>
  {coverage&&<section className="mb-5 grid gap-3 sm:grid-cols-4"><Stat l="Cartas" v={coverage.total}/><Stat l="Com arte" v={coverage.withArt}/><Stat l="Sem arte" v={coverage.missing}/><Stat l="Cobertura" v={`${coverage.percent}%`}/></section>}{notice&&<div className="mb-4 rounded-xl border border-amber-400/20 bg-amber-400/10 p-3 text-xs text-amber-100">{notice}</div>}
  <div className="grid gap-5 xl:grid-cols-[1.15fr_.85fr]"><section className="rounded-2xl border border-white/10 bg-white/[.03] p-4"><div className="mb-3 flex gap-2"><input className="input" placeholder="Buscar carta, ID ou região" value={query} onChange={e=>setQuery(e.target.value)}/><label className="btn-ghost cursor-pointer whitespace-nowrap">Upload imagem<input className="hidden" type="file" accept="image/png,image/jpeg,image/webp,image/gif" onChange={e=>void upload(e.target.files?.[0])}/></label></div><div className="max-h-[70vh] space-y-2 overflow-auto pr-1">{filtered.map(c=><button key={c.defId} onClick={()=>{setSelected(c.defId);setCrop({x:Number(c.crop?.x??.5),y:Number(c.crop?.y??.5),scale:Number(c.crop?.scale??1)});}} className={`flex w-full items-center gap-3 rounded-xl border p-2 text-left ${selected===c.defId?"border-amber-300/60 bg-amber-300/10":"border-white/5 bg-slate-950/40"}`}><div className="h-16 w-12 shrink-0 rounded bg-slate-800 bg-cover bg-center" style={{backgroundImage:c.art?`url(${c.art})`:undefined}}>{!c.art&&<span className="flex h-full items-center justify-center text-xl">?</span>}</div><div className="min-w-0 flex-1"><div className="truncate font-bold">{c.name}</div><div className="text-[10px] text-slate-500">{c.defId} · {c.region} · {c.rarity}</div></div><span className={`rounded-full px-2 py-1 text-[9px] font-black uppercase ${c.missing?"bg-red-400/10 text-red-300":c.editorialArt?"bg-emerald-400/10 text-emerald-300":"bg-sky-400/10 text-sky-300"}`}>{c.missing?"missing":c.editorialArt?"runtime":"code"}</span></button>)}</div></section>
  <section className="rounded-2xl border border-white/10 bg-white/[.03] p-5">{!card?<div className="py-16 text-center text-sm text-slate-500">Selecione uma carta.</div>:<><h2 className="text-xl font-black">{card.name}</h2><p className="text-xs text-slate-500">{card.defId}</p><div className="mt-4 aspect-[3/4] rounded-xl border border-white/10 bg-slate-950 bg-cover" style={{backgroundImage:`url(${previewUrl})`,backgroundPosition:`${crop.x*100}% ${crop.y*100}%`,backgroundSize:crop.scale>1?`${crop.scale*100}%`:"cover"}}/><label className="mt-4 block text-[10px] uppercase text-slate-500">Asset</label><select className="input mt-1" value={assetId} onChange={e=>setAssetId(Number(e.target.value))}><option value={0}>Selecione uma imagem</option>{assets.map(a=><option key={a.id} value={a.id}>{a.name} · {a.mimeType}{a.variants.webp?" · optimized":""}</option>)}</select><label className="mt-3 block text-[10px] uppercase text-slate-500">Formato publicado</label><select className="input mt-1" value={variant} onChange={e=>setVariant(e.target.value as typeof variant)}><option value="auto">Auto · WebP preferido</option><option value="webp" disabled={!asset?.variants.webp}>WebP</option><option value="avif" disabled={!asset?.variants.avif}>AVIF</option><option value="original">Original</option></select>{asset&&<div className="mt-2 grid grid-cols-3 gap-2 text-[9px]"><Mini l="Original" v={bytes(originalSize)}/><Mini l="Selecionado" v={bytes(variantSize)}/><Mini l="Economia" v={`${saving}%`}/></div>}<Range l="Foco X" v={crop.x} min={0} max={1} step={.01} set={v=>setCrop({...crop,x:v})}/><Range l="Foco Y" v={crop.y} min={0} max={1} step={.01} set={v=>setCrop({...crop,y:v})}/><Range l="Zoom" v={crop.scale} min={1} max={2.5} step={.05} set={v=>setCrop({...crop,scale:v})}/><div className="mt-5 flex justify-between"><button className="btn-ghost text-red-300" disabled={busy||!card.editorialArt} onClick={()=>void assign("clear")}>Remover override</button><button className="btn-primary" disabled={busy||!assetId} onClick={()=>void assign()}>{busy?"Salvando…":"Publicar arte"}</button></div><p className="mt-3 text-[10px] leading-4 text-slate-500">A publicação exige publisher/admin e grava auditoria. PNG/JPEG/WebP estáticos geram WebP + AVIF; o runtime prefere WebP por compatibilidade e a arte original continua como fallback.</p></>}</section></div></div></main>;
}
function Stat({l,v}:{l:string;v:any}){return <div className="rounded-xl border border-white/10 bg-white/[.03] p-4"><div className="text-[10px] uppercase tracking-wider text-slate-500">{l}</div><div className="mt-1 text-2xl font-black">{v}</div></div>}
function Range({l,v,min,max,step,set}:{l:string;v:number;min:number;max:number;step:number;set:(n:number)=>void}){return <label className="mt-3 block"><span className="flex justify-between text-[10px] uppercase text-slate-500"><b>{l}</b><i>{v.toFixed(2)}</i></span><input className="w-full" type="range" value={v} min={min} max={max} step={step} onChange={e=>set(Number(e.target.value))}/></label>}

function Mini({l,v}:{l:string;v:string}){return <div className="rounded-lg border border-white/10 bg-black/20 p-2"><div className="text-slate-500">{l}</div><b className="text-slate-200">{v}</b></div>}
function bytes(n:number){if(!n)return "—";if(n<1024)return `${n} B`;if(n<1024*1024)return `${(n/1024).toFixed(1)} KB`;return `${(n/1024/1024).toFixed(2)} MB`}
