"use client";
import { useCallback, useMemo, useState } from "react";
import Link from "next/link";
import { StudioBreadcrumb, StudioCommandPalette } from "../StudioChrome";
import { useDeferredEffect } from "@/hooks/useDeferredEffect";

const resources = [["matches","Partidas"],["replays","Replays"],["player-decks","Decks pessoais"],["shared-decks","Decks publicados"],["chat","Chat"],["economy","Ledger"],["rooms","Salas PvP"],["queue","Fila"],["sessions","Sessões"],["pack-openings","Aberturas"]] as const;
const actions: Record<string,string> = { replays: "delete-replay", "player-decks": "delete-player-deck", "shared-decks": "delete-shared-deck", chat: "delete-chat", rooms: "close-room", queue: "remove-queue", sessions: "revoke-session" };
export default function RuntimeOperationsStudio() {
  const [resource,setResource]=useState("matches"),[rows,setRows]=useState<Record<string,any>[]>([]),[search,setSearch]=useState(""),[reason,setReason]=useState(""),[error,setError]=useState(""),[notice,setNotice]=useState("");
  const load=useCallback(async()=>{const response=await fetch(`/api/admin/runtime?resource=${resource}`,{credentials:"include"});const data=await response.json();if(!data.ok)throw new Error(data.error);setRows(data.rows||[]);},[resource]);
  useDeferredEffect(()=>{load().catch((e)=>setError(e.message));},[load]);
  const filtered=useMemo(()=>{const query=search.toLowerCase();return query?rows.filter((row)=>JSON.stringify(row).toLowerCase().includes(query)):rows;},[rows,search]);
  async function act(row:Record<string,any>){const action=actions[resource];if(!action)return;const response=await fetch("/api/admin/runtime",{method:"POST",headers:{"Content-Type":"application/json"},credentials:"include",body:JSON.stringify({action,id:row.id,reason})});const data=await response.json();if(!data.ok)return setError(data.error);setNotice("Ação operacional executada e auditada.");await load();}
  async function cleanup(){const response=await fetch("/api/admin/runtime",{method:"POST",headers:{"Content-Type":"application/json"},credentials:"include",body:JSON.stringify({action:"cleanup"})});const data=await response.json();if(!data.ok)return setError(data.error);setNotice(`Limpeza concluída: ${JSON.stringify(data.result)}`);await load();}
  return <main className="studio-shell min-h-screen"><StudioCommandPalette/><div className="studio-main mx-auto max-w-7xl p-8"><StudioBreadcrumb section="Operations" current="Runtime Console"/><div className="flex flex-wrap items-end justify-between gap-3"><div><div className="studio-kicker">LIVE DATA // MODERATION</div><h1 className="studio-title">Runtime Operations</h1></div><div className="flex gap-2"><button className="btn-ghost" onClick={cleanup}>Limpar expirados</button><Link href="/admin/studio/control" className="btn-primary">Total Control</Link></div></div>{notice&&<div className="mt-4 rounded-xl border border-emerald-400/20 bg-emerald-400/10 p-3 text-xs text-emerald-200">{notice}</div>}{error&&<div className="mt-4 rounded-xl border border-red-400/20 bg-red-400/10 p-3 text-xs text-red-200">{error}</div>}<div className="mt-5 flex flex-wrap gap-2">{resources.map(([id,label])=><button key={id} className={resource===id?"btn-primary":"btn-ghost"} onClick={()=>setResource(id)}>{label}</button>)}</div><div className="mt-5 grid gap-3 md:grid-cols-2"><input className="input" placeholder="Buscar em todos os campos…" value={search} onChange={(e)=>setSearch(e.target.value)}/><input className="input" placeholder="Motivo obrigatório para ações destrutivas" value={reason} onChange={(e)=>setReason(e.target.value)}/></div><section className="studio-section mt-5 overflow-auto"><table className="w-full min-w-[900px] text-left text-xs"><thead><tr className="border-b border-white/10 text-slate-500"><th className="p-3">ID</th><th className="p-3">Resumo</th><th className="p-3">Dados</th><th className="p-3">Ação</th></tr></thead><tbody>{filtered.map((row)=><tr key={row.id} className="border-b border-white/5 align-top"><td className="p-3 font-bold">#{row.id}</td><td className="p-3"><b>{row.name||row.playerName||row.ownerName||row.code||row.currency||resource}</b><div className="text-slate-500">{row.status||row.state||row.mode||row.createdAt||""}</div></td><td className="max-w-2xl p-3"><pre className="max-h-36 overflow-auto whitespace-pre-wrap text-[9px] text-slate-400">{JSON.stringify(row,null,2)}</pre></td><td className="p-3">{actions[resource]?<button className="btn-ghost !px-2 !py-1 text-red-300" disabled={reason.trim().length<8} onClick={()=>act(row)}>{resource==="rooms"?"Encerrar":resource==="sessions"?"Revogar":"Remover"}</button>:<span className="text-slate-600">somente leitura</span>}</td></tr>)}</tbody></table></section></div></main>;
}
