"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import SiteNav from "@/components/SiteNav";
import { resolveCardCosmeticPrestige } from "@/game/card-cosmetics";
type ShowcaseItem={assetId:number;defId:string;cardName:string;cardRarity:string;region:string|null;emoji:string;variantId:string;variantName:string;kind:string;frameId:string;finish:string;serialNumber:number|null;edition:string|null;prestige:{id:string;label:string;shortLabel:string;rank:number}};
type Payload={ok:boolean;canEdit:boolean;player:{name:string;avatar:string|null;title:string|null;level:number};showcase:{visibility:string;tagline:string;items:ShowcaseItem[];stats:{selected:number;serialized:number;special:number;prestige:Record<string,number>}};error?:string};
type WardrobeItem={assetId:number;defId:string;cardName:string;variantId:string;frameId:string;finish:string;serialNumber?:number|null;cosmetic?:{name?:string;acquisition:"pack"|"event"|"promotion"|"market"|"grant";packEligible:boolean;dropWeight:number}|null};
export default function CollectorShowcaseClient({requestedPlayer}:{requestedPlayer:string}){
 const [data,setData]=useState<Payload|null>(null),[wardrobe,setWardrobe]=useState<WardrobeItem[]>([]),[selected,setSelected]=useState<number[]>([]),[visibility,setVisibility]=useState("friends"),[tagline,setTagline]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{setMessage("");const query=requestedPlayer?`?player=${encodeURIComponent(requestedPlayer)}`:"";const response=await fetch(`/api/collection/showcase${query}`,{credentials:"include",cache:"no-store"});const payload=await response.json();if(!response.ok){setData(null);setMessage(payload.error||"Vitrine indisponível");return;}setData(payload);setSelected(payload.showcase.items.map((item:ShowcaseItem)=>item.assetId));setVisibility(payload.showcase.visibility);setTagline(payload.showcase.tagline||"");if(payload.canEdit){const wardrobeResponse=await fetch("/api/player/cosmetics",{credentials:"include",cache:"no-store"});const wardrobePayload=await wardrobeResponse.json();if(wardrobeResponse.ok)setWardrobe(Array.isArray(wardrobePayload.wardrobe)?wardrobePayload.wardrobe:[])}},[requestedPlayer]);
 useEffect(()=>{void load()},[load]);
 const toggle=(id:number)=>setSelected((current)=>current.includes(id)?current.filter((value)=>value!==id):current.length<6?[...current,id]:current);
 const save=async()=>{setBusy(true);setMessage("");try{const response=await fetch("/api/collection/showcase",{method:"PUT",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify({assetIds:selected,visibility,tagline})});const payload=await response.json();if(!response.ok)throw new Error(payload.error||"Falha ao salvar vitrine");setMessage("Vitrine atualizada.");await load()}catch(error){setMessage(error instanceof Error?error.message:"Falha ao salvar vitrine")}finally{setBusy(false)}};
 const copyLink=async()=>{if(!data)return;const url=new URL(window.location.href);url.searchParams.set("player",data.player.name);await navigator.clipboard.writeText(url.toString()).catch(()=>{});setMessage("Link da vitrine copiado.");};
 const selectedSet=useMemo(()=>new Set(selected),[selected]);
 return <main className="rf-app-page"><SiteNav/><div className="rf-app-shell"><header className="rf-app-heading"><div><p className="rf-eyebrow"><span/> METAGAME SOCIAL · PRESTÍGIO COSMÉTICO</p><h1>Vitrine de Colecionador</h1><p>Cópias físicas exatas, frames, acabamentos, edições e seriais sem alterar raridade ou poder de gameplay.</p></div><div className="flex flex-wrap gap-2"><Link href="/collection" className="rf-button rf-button-secondary">COLEÇÃO</Link>{data&&<button className="rf-button rf-button-secondary" onClick={()=>void copyLink()}>COPIAR LINK</button>}<Link href="/friends" className="rf-button rf-button-primary">AMIGOS</Link></div></header>
 {message&&<div className="mb-5 rounded-xl border border-amber-300/20 bg-amber-300/[.06] px-4 py-3 text-sm text-amber-100">{message}</div>}
 {data&&<><section className="rounded-2xl border border-white/10 bg-black/20 p-5"><div className="flex flex-wrap items-end justify-between gap-4"><div className="flex items-center gap-3"><span className="grid h-14 w-14 place-items-center rounded-full border border-amber-300/25 bg-black/30 text-3xl">{data.player.avatar||"🎮"}</span><div><small className="font-black uppercase tracking-wider opacity-55">{data.player.title||"Forjador"} · nível {data.player.level}</small><h2 className="text-2xl font-black">{data.player.name}</h2><p className="mt-1 text-sm opacity-65">{data.showcase.tagline||"Colecionador do Nexus."}</p></div></div><div className="flex flex-wrap gap-2 text-xs font-black uppercase tracking-wider opacity-70"><span>{data.showcase.stats.selected}/6 em destaque</span><span>·</span><span>{data.showcase.stats.special} especiais</span><span>·</span><span>{data.showcase.stats.serialized} serializadas</span></div></div></section>
 <section className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{data.showcase.items.map((item)=><article key={item.assetId} className="rounded-2xl border border-white/10 bg-[#090d14] p-5"><div className="flex items-start justify-between gap-3"><span className="text-3xl">{item.emoji}</span><span className="rounded-full border border-violet-300/20 bg-violet-300/[.07] px-2.5 py-1 text-[9px] font-black uppercase tracking-wider text-violet-100">{item.prestige.shortLabel}</span></div><h3 className="mt-3 text-lg font-black">{item.cardName}</h3><p className="text-xs opacity-55">{item.variantName} · {item.frameId} · {item.finish}</p>{item.serialNumber!=null&&<p className="mt-2 font-mono text-sm text-amber-200">SERIAL #{item.serialNumber}{item.edition?` · ${item.edition}`:""}</p>}<p className="mt-3 text-[10px] uppercase tracking-wider opacity-45">Cópia física #{item.assetId} · gameplay {item.cardRarity}</p></article>)}{!data.showcase.items.length&&<div className="col-span-full rounded-2xl border border-dashed border-white/15 px-6 py-12 text-center text-sm opacity-55">Nenhuma cópia em destaque ainda.</div>}</section></>}
 {data?.canEdit&&<section className="mt-6 rounded-2xl border border-violet-300/15 bg-violet-300/[.025] p-5"><div className="flex flex-wrap items-end justify-between gap-4"><div><small className="font-black uppercase tracking-wider text-violet-200/60">CURADORIA</small><h2 className="text-xl font-black">Monte sua vitrine</h2><p className="text-sm opacity-60">Escolha até seis cópias exatas do seu acervo.</p></div><button className="rf-button rf-button-primary" disabled={busy} onClick={()=>void save()}>{busy?"SALVANDO…":"SALVAR VITRINE"}</button></div><div className="mt-4 grid gap-3 md:grid-cols-[180px_1fr]"><select className="rf-input" value={visibility} onChange={(event)=>setVisibility(event.target.value)}><option value="public">Pública</option><option value="friends">Só amigos</option><option value="private">Privada</option></select><input className="rf-input" maxLength={120} value={tagline} onChange={(event)=>setTagline(event.target.value)} placeholder="Frase curta da sua vitrine"/></div><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{wardrobe.map((item)=>{const chosen=selectedSet.has(item.assetId);const prestige=item.cosmetic?resolveCardCosmeticPrestige(item.cosmetic):null;return <button type="button" key={item.assetId} aria-pressed={chosen} onClick={()=>toggle(item.assetId)} className={`rounded-xl border p-4 text-left transition ${chosen?"border-amber-300/45 bg-amber-300/[.06]":"border-white/10 bg-black/15 hover:border-white/20"}`}><div className="flex justify-between gap-3"><b>{chosen?"✓ ":""}{item.cardName}</b><small className="opacity-50">#{item.assetId}</small></div><p className="mt-1 text-xs opacity-55">{item.cosmetic?.name||"Standard"} · {item.finish}{item.serialNumber!=null?` · #${item.serialNumber}`:""}</p>{prestige&&<p className="mt-2 text-[9px] font-black uppercase tracking-wider text-violet-200">{prestige.shortLabel}</p>}</button>})}</div></section>}</div></main>;
}
