import { NextRequest } from "next/server";
import { db } from "@/db";
import { adminCardTests, adminCardTestRuns, adminAuditLogs, customCards } from "@/db/schema";
import { eq, desc } from "drizzle-orm";
import { getAdminSessionContext, isAdminAuthorized, unauthorized, adminRoleAllowed } from "@/lib/admin-auth";
import { ensureCustomCardsLoaded } from "@/game/catalog";
import { validateAuthorableCard as validateCard } from "@/game/card-authoring";
import { runCardTest } from "@/lib/card-test-runner";
import { ENGINE_VERSION, RULESET_VERSION } from "@/game/version";
export const dynamic="force-dynamic";
export async function GET(req:NextRequest){if(!(await isAdminAuthorized(req)))return unauthorized();const actor=await getAdminSessionContext(req);if(!actor)return unauthorized();if(!adminRoleAllowed(actor.role,"designer"))return Response.json({ok:false,error:`Role ${actor.role} cannot access this resource`},{status:403});const cardId=Number(req.nextUrl.searchParams.get("cardId"));if(!Number.isInteger(cardId))return Response.json({ok:false,error:"cardId required"},{status:400});const tests=await db.select().from(adminCardTests).where(eq(adminCardTests.cardId,cardId)).orderBy(desc(adminCardTests.id));return Response.json({ok:true,tests});}
export async function POST(req:NextRequest){if(!(await isAdminAuthorized(req)))return unauthorized();const actor=await getAdminSessionContext(req);if(!actor)return unauthorized();if(!adminRoleAllowed(actor.role,"designer"))return Response.json({ok:false,error:`Role ${actor.role} cannot edit card tests`},{status:403});const b=await req.json(),cardId=Number(b.cardId);if(!Number.isInteger(cardId))return Response.json({ok:false,error:"cardId required"},{status:400});const [card]=await db.select().from(customCards).where(eq(customCards.id,cardId)).limit(1);if(!card)return Response.json({ok:false,error:"Card not found"},{status:404});const [row]=await db.insert(adminCardTests).values({cardId,name:String(b.name||"Card regression test"),scenario:b.scenario||{},expected:b.expected||{},enabled:b.enabled!==false}).returning();return Response.json({ok:true,test:row});}
export async function PUT(req:NextRequest){if(!(await isAdminAuthorized(req)))return unauthorized();const actor=await getAdminSessionContext(req);if(!actor)return unauthorized();if(!adminRoleAllowed(actor.role,"designer"))return Response.json({ok:false,error:`Role ${actor.role} cannot edit card tests`},{status:403});const b=await req.json(),testId=Number(b.testId);const [row]=await db.update(adminCardTests).set({name:String(b.name||"Card regression test"),scenario:b.scenario||{},expected:b.expected||{},enabled:b.enabled!==false,updatedAt:new Date()}).where(eq(adminCardTests.id,testId)).returning();if(!row)return Response.json({ok:false,error:"Test not found"},{status:404});return Response.json({ok:true,test:row});}
export async function DELETE(req:NextRequest){if(!(await isAdminAuthorized(req)))return unauthorized();const actor=await getAdminSessionContext(req);if(!actor)return unauthorized();if(!adminRoleAllowed(actor.role,"designer"))return Response.json({ok:false,error:`Role ${actor.role} cannot delete card tests`},{status:403});const testId=Number(req.nextUrl.searchParams.get("testId"));await db.delete(adminCardTests).where(eq(adminCardTests.id,testId));return Response.json({ok:true});}
export async function PATCH(req:NextRequest){if(!(await isAdminAuthorized(req)))return unauthorized();const actor=await getAdminSessionContext(req);if(!actor)return unauthorized();if(!adminRoleAllowed(actor.role,"qa"))return Response.json({ok:false,error:`Role ${actor.role} cannot run card QA`},{status:403});const b=await req.json(),cardId=Number(b.cardId);await ensureCustomCardsLoaded();const [card]=await db.select().from(customCards).where(eq(customCards.id,cardId)).limit(1);if(!card)return Response.json({ok:false,error:"Card not found"},{status:404});const validation=validateCard(card.data as any);if(!validation.ok)return Response.json({ok:false,error:validation.error},{status:400});const tests=await db.select().from(adminCardTests).where(eq(adminCardTests.cardId,cardId));const results=[];for(const test of tests.filter(t=>t.enabled)){const result=runCardTest(validation.card,{scenario:test.scenario,expected:test.expected});const [run]=await db.insert(adminCardTestRuns).values({testId:test.id,cardId,passed:result.passed,actual:result.actual,errors:result.errors,engineVersion:ENGINE_VERSION,rulesetVersion:RULESET_VERSION}).returning();results.push({test,run,result});}const passed=results.length>0&&results.every(x=>x.result.passed);await db.insert(adminAuditLogs).values({action:"card_tests_run",resource:"cards",resourceId:cardId,actor:actor.actorId,details:{count:results.length,passed}});return Response.json({ok:true,passed,results});}
