"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import SiteNav from "@/components/SiteNav";

type Seat={playerId:number;playerName:string;seat:number;generalDefId:string;generalName:string;nexus:number;eliminated:boolean;deckSize:number;isCurrent:boolean};
type Room={id:number;code:string;state:string;currentSeat:number;round:number;version:number;winnerPlayerId:number|null;viewerSeat:number|null;viewerIsHost:boolean;players:Seat[];rules:{deckSize:number;generalCount:number;maxCopiesPerCard:number;startingNexus:number};events:Array<{id:number;eventType:string;actorPlayerId:number|null;roomVersion:number;createdAt:string}>};

function parseDeck(raw:string){return raw.split(/[\s,;]+/).map((value)=>value.trim()).filter(Boolean);}
export default function CommanderClient(){
 const [room,setRoom]=useState<Room|null>(null),[code,setCode]=useState(""),[general,setGeneral]=useState(""),[deckText,setDeckText]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 const deck=parseDeck(deckText); const deckCount=deck.length;
 const post=useCallback(async(body:Record<string,unknown>)=>{setBusy(true);setMessage("");try{const response=await fetch("/api/commander",{method:"POST",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(data.error||"Ação recusada");setRoom(data.room||null);if(data.room?.code)setCode(data.room.code);return data;}catch(error){setMessage(error instanceof Error?error.message:"Falha no Commander");return null;}finally{setBusy(false)}},[]);
 const refresh=useCallback(async()=>{try{const suffix=code?`?code=${encodeURIComponent(code)}`:"";const response=await fetch(`/api/commander${suffix}`,{credentials:"include",cache:"no-store"});const data=await response.json();if(response.ok&&data.ok){setRoom(data.room||null);if(data.room?.code)setCode(data.room.code)}}catch{}},[code]);
 useEffect(()=>{const id=window.setInterval(()=>{if(room&&(room.state==="waiting"||room.state==="playing"))void refresh()},4000);return()=>window.clearInterval(id)},[refresh,room]);
 const winner=useMemo(()=>room?.players.find((seat)=>seat.playerId===room.winnerPlayerId)??null,[room]);
 const canLoadout=deckCount===60&&Boolean(general);
 return <main className="rf-app-page"><SiteNav/><div className="rf-app-shell">
  <header className="rf-app-heading"><div><p className="rf-eyebrow"><span/> EXPERIMENTAL · 4 HUMANOS</p><h1>Commander Alpha</h1><p>Modo separado do 1v1: quatro assentos, deck de 60 cartas + 1 General, Nexus 30, turnos circulares e último jogador ativo vence.</p></div><Link href="/modes" className="rf-button rf-button-secondary">VOLTAR AOS MODOS</Link></header>
  <section className="rf-panel p-5">
   <div className="flex flex-wrap items-center justify-between gap-3"><div><small className="font-black uppercase tracking-wider opacity-55">Loadout Commander</small><h2 className="text-xl font-black">60 + 1</h2></div><span className={`rounded-full border px-3 py-1 text-xs font-black ${deckCount===60?"border-emerald-300/30 text-emerald-200":"border-white/10 opacity-70"}`}>{deckCount}/60 cartas</span></div>
   <div className="mt-4 grid gap-3 lg:grid-cols-[260px_1fr]"><input className="rf-input" value={general} onChange={(event)=>setGeneral(event.target.value)} placeholder="defId do General (Champion/Legend/Sentinela)"/><textarea className="rf-input min-h-36" value={deckText} onChange={(event)=>setDeckText(event.target.value)} placeholder="Cole 60 defIds separados por espaço, vírgula ou linha. O General fica fora destas 60 cartas."/></div>
   <p className="mt-2 text-xs opacity-55">O servidor valida 60 cartas exatas, máximo de 3 cópias, identidade regional do General e General fora do deck.</p>
   <div className="mt-4 flex flex-wrap gap-2"><button className="rf-button rf-button-primary" disabled={busy||!canLoadout} onClick={()=>void post({action:"create",deckCards:deck,generalDefId:general})}>Criar sala</button><input className="rf-input w-40 uppercase" value={code} onChange={(event)=>setCode(event.target.value.toUpperCase())} maxLength={6} placeholder="CÓDIGO"/><button className="rf-button rf-button-secondary" disabled={busy||!canLoadout||code.length<6} onClick={()=>void post({action:"join",code,deckCards:deck,generalDefId:general})}>Entrar</button><button className="rf-button rf-button-secondary" disabled={busy||!code} onClick={()=>void refresh()}>Atualizar</button></div>
   {message&&<p className="mt-3 text-sm text-amber-200">{message}</p>}
  </section>
  {room&&<section className="mt-5 rf-panel p-5">
   <div className="flex flex-wrap items-end justify-between gap-4"><div><small className="font-black uppercase tracking-wider opacity-55">Sala</small><h2 className="text-2xl font-black">{room.code}</h2><p className="text-sm opacity-60">Estado {room.state} · rodada {room.round} · versão {room.version}</p></div><div className="flex flex-wrap gap-2">{room.viewerIsHost&&room.state==="waiting"&&<><button className="rf-button rf-button-primary" disabled={busy||room.players.length!==4} onClick={()=>void post({action:"start",code:room.code})}>Iniciar 4 jogadores</button><button className="rf-button rf-button-secondary" disabled={busy} onClick={()=>void post({action:"cancel",code:room.code})}>Cancelar sala</button></>}{room.state==="playing"&&<><button className="rf-button rf-button-primary" disabled={busy||room.viewerSeat!==room.currentSeat} onClick={()=>void post({action:"pass",code:room.code})}>Passar turno</button><button className="rf-button rf-button-secondary" disabled={busy} onClick={()=>void post({action:"forfeit",code:room.code})}>Conceder</button></>}</div></div>
   <div className="mt-5 grid gap-4 md:grid-cols-2">{[1,2,3,4].map((seatNo)=>{const seat=room.players.find((item)=>item.seat===seatNo);return <article key={seatNo} className={`rounded-xl border p-4 ${seat?.isCurrent?"border-amber-300/45 bg-amber-300/[.06]":"border-white/10 bg-black/15"}`}><small className="font-black uppercase tracking-wider opacity-55">Assento {seatNo}</small>{seat?<><h3 className="mt-1 text-lg font-black">{seat.playerName}{seat.playerId===room.winnerPlayerId?" · VENCEDOR":""}</h3><p className="text-sm opacity-70">General: {seat.generalName}</p><p className="mt-2 text-xs opacity-55">{seat.deckSize} cartas · Nexus {seat.nexus} · {seat.eliminated?"eliminado":seat.isCurrent?"turno atual":"ativo"}</p></>:<p className="mt-2 text-sm opacity-45">Aguardando jogador…</p>}</article>})}</div>
   {winner&&<div className="mt-5 rounded-xl border border-emerald-300/25 bg-emerald-300/[.06] p-4 font-black">Vitória: {winner.playerName} · último jogador ativo.</div>}
   {!!room.events.length&&<details className="mt-5 rounded-xl border border-white/10 p-4"><summary className="cursor-pointer font-black uppercase tracking-wider opacity-65">Log autoritativo · {room.events.length}</summary><div className="mt-3 space-y-1 text-xs opacity-65">{room.events.slice().reverse().slice(0,16).map((event)=><p key={event.id}>v{event.roomVersion} · {event.eventType} · {new Date(event.createdAt).toLocaleTimeString("pt-BR")}</p>)}</div></details>}
  </section>}
 </div></main>
}
