import type { CardDef } from "../types";

/**
 * Ecos do Abismo — Tidecall/Voidborn Discard Reanimator content wave.
 *
 * These cards intentionally consume only already-certified Graveyard Effects
 * primitives. The archetype is advanced content and is not part of the six
 * Alpha starter recipes or Ranked pool.
 */
export const ECOS_DO_ABISMO_CARDS: Record<string, CardDef> = {
  rfalpha_reanimator_drowned_recollection: {
    defId: "rfalpha_reanimator_drowned_recollection",
    name: "Recordação Submersa",
    region: "Tidecall",
    type: "Spell",
    cost: 2,
    spell: {
      kind: "selfMill",
      amount: 1,
      target: "none",
      also: { kind: "draw", amount: 1, target: "none" },
    },
    description: "Envie a carta do topo do seu deck ao seu Cemitério. Depois compre 1 carta.",
    flavor: "Nas profundezas, lembrar e afundar são o mesmo movimento.",
    rarity: "Common",
    emoji: "🫧",
    strategicRole: "engine",
    doctrineAffinities: ["ecos_do_abismo"],
  },
  rfalpha_reanimator_memory_smuggler: {
    defId: "rfalpha_reanimator_memory_smuggler",
    name: "Contrabandista de Memórias",
    region: "Tidecall",
    type: "Unit",
    cost: 2,
    power: 1,
    health: 3,
    race: "Spirit",
    keywords: [],
    description: "Uma vez por rodada — descarte 1 carta escolhida da mão: compre 1 carta.",
    flavor: "Algumas lembranças valem mais depois que ninguém deveria encontrá-las.",
    rarity: "Rare",
    emoji: "🫧",
    strategicRole: "engine",
    doctrineAffinities: ["ecos_do_abismo"],
    activatedAbilities: [{
      description: "Contrabando de lembranças — descarte 1 carta escolhida: compre 1.",
      cost: { discardFromHand: 1 },
      effect: { kind: "draw", amount: 1, target: "none" },
      maxUsesPerRound: 1,
    }],
  },
  rfalpha_reanimator_drowned_sepulcher: {
    defId: "rfalpha_reanimator_drowned_sepulcher",
    name: "Sepulcro das Vozes Afogadas",
    region: "Tidecall",
    type: "Artifact",
    cost: 3,
    maxHealth: 4,
    description: "Até duas vezes por rodada — pague 1 de mana e descarte 1 carta escolhida: compre 1 carta.",
    flavor: "A água preserva o que o mundo tentou esquecer.",
    rarity: "Epic",
    emoji: "⚱️",
    strategicRole: "engine",
    doctrineAffinities: ["ecos_do_abismo"],
    activatedAbilities: [{
      description: "Sussurro submerso — pague 1 e descarte 1 carta escolhida: compre 1.",
      cost: { mana: 1, discardFromHand: 1 },
      effect: { kind: "draw", amount: 1, target: "none" },
      maxUsesPerRound: 2,
    }],
  },
  rfalpha_reanimator_dead_memory_thread: {
    defId: "rfalpha_reanimator_dead_memory_thread",
    name: "Fio da Memória Morta",
    region: "Tidecall",
    type: "Spell",
    cost: 2,
    spell: { kind: "returnGraveyardToHand", amount: 0, target: "allyGraveyardCard" },
    description: "Escolha uma carta do seu Cemitério e devolva-a à sua mão.",
    flavor: "Uma lembrança puxada com cuidado ainda sabe o caminho de volta.",
    rarity: "Common",
    emoji: "🧵",
    strategicRole: "engine",
    doctrineAffinities: ["ecos_do_abismo"],
  },
  rfalpha_reanimator_second_pulse: {
    defId: "rfalpha_reanimator_second_pulse",
    name: "Rito do Segundo Pulso",
    region: "Voidborn",
    type: "Spell",
    cost: 5,
    spell: { kind: "reanimateUnit", amount: 0, target: "allyGraveyardUnit" },
    description: "Reanime uma Unidade do seu Cemitério. Ela retorna como uma nova Unidade e sofre Enjoo de Invocação normalmente.",
    flavor: "O primeiro pulso pertence à vida. O segundo pertence ao Vazio.",
    rarity: "Epic",
    emoji: "🜏",
    strategicRole: "finisher",
    doctrineAffinities: ["ecos_do_abismo"],
  },
  rfalpha_reanimator_last_vigil: {
    defId: "rfalpha_reanimator_last_vigil",
    name: "Vigília do Último Eco",
    region: "Voidborn",
    type: "Spell",
    cost: 7,
    spell: {
      kind: "reanimateUnit",
      amount: 0,
      target: "allyGraveyardUnit",
      also: { kind: "healNexus", amount: 3, target: "none" },
    },
    description: "Reanime uma Unidade do seu Cemitério e restaure 3 de vida ao seu Nexus.",
    flavor: "Quando todas as vozes cessam, uma última ainda responde.",
    rarity: "Legend",
    isLegend: true,
    emoji: "🕯️",
    strategicRole: "finisher",
    doctrineAffinities: ["ecos_do_abismo"],
  },
  rfalpha_reanimator_seal_nothing: {
    defId: "rfalpha_reanimator_seal_nothing",
    name: "Selo do Nada",
    region: "Voidborn",
    type: "Spell",
    cost: 1,
    spell: { kind: "banishGraveyardCard", amount: 0, target: "enemyGraveyardCard" },
    description: "Escolha uma carta no Cemitério inimigo e bana-a da partida.",
    flavor: "Nem todo morto merece uma segunda história.",
    rarity: "Common",
    emoji: "◌",
    strategicRole: "removal",
    doctrineAffinities: ["ecos_do_abismo"],
  },
  rfalpha_reanimator_drowned_mirror_lady: {
    defId: "rfalpha_reanimator_drowned_mirror_lady",
    name: "Dama Afogada do Espelho",
    region: "Tidecall",
    type: "Unit",
    cost: 7,
    power: 5,
    health: 7,
    race: "Spirit",
    keywords: ["Elusive", "Barrier"],
    description: "Spirit. Elusive e Barrier. Uma ameaça evasiva que também pode ser conjurada normalmente no fim da curva.",
    flavor: "Seu reflexo chega à superfície antes dela.",
    rarity: "Epic",
    emoji: "🪞",
    strategicRole: "finisher",
    doctrineAffinities: ["ecos_do_abismo"],
  },
  rfalpha_reanimator_dead_tide_devourer: {
    defId: "rfalpha_reanimator_dead_tide_devourer",
    name: "Devorador das Marés Mortas",
    region: "Voidborn",
    type: "Unit",
    cost: 8,
    power: 6,
    health: 8,
    race: "Voidling",
    keywords: ["Lifesteal", "Tough"],
    description: "Voidling. Lifesteal e Tough. Um alvo de reanimação voltado a estabilizar partidas sob pressão.",
    flavor: "Ele não bebe água. Bebe o instante em que a maré recua.",
    rarity: "Epic",
    emoji: "🐙",
    strategicRole: "defense",
    doctrineAffinities: ["ecos_do_abismo"],
  },
  rfalpha_reanimator_hollow_rift_colossus: {
    defId: "rfalpha_reanimator_hollow_rift_colossus",
    name: "Colosso da Fenda Oca",
    region: "Voidborn",
    type: "Unit",
    cost: 9,
    power: 8,
    health: 8,
    race: "Voidling",
    keywords: [],
    description: "Voidling. Ao ser invocado, cause 2 de dano ao Nexus inimigo.",
    flavor: "A fenda não se abriu para deixá-lo passar. Abriu-se porque ele acordou.",
    rarity: "Legend",
    isLegend: true,
    emoji: "🌑",
    strategicRole: "finisher",
    doctrineAffinities: ["ecos_do_abismo"],
    trigger: { when: "onSummon", effect: { kind: "damageNexus", amount: 2, target: "none" } },
  },
};
