import type { CardDef } from "../types";

/**
 * Alpha Semantic Wave — 18 code-authored Vanilla cards.
 *
 * Product goal: every region ships at least one real Structure, Ritual and Trap
 * before the public Alpha. These cards intentionally use only already-certified
 * engine contracts; this file introduces content, never new rules.
 *
 * Ritual product identity is deliberate: every collectible Ritual manipulates
 * mana and then expresses its region through a secondary payoff.
 *
 * The wave is not injected into the 12 historical Balance Lab intake decks.
 * Players can discover the cards through Collection/Codex/Forge/custom decks,
 * while the established Vanilla 1.8 matrix remains comparable.
 */
export const SEMANTIC_ALPHA_CARDS: Record<string, CardDef> = {
  // ───────────────────────────── Emberhold ─────────────────────────────
  rfalpha_ember_structure_forge_bastion: {
    defId: "rfalpha_ember_structure_forge_bastion",
    name: "Bastião da Forja Rubra",
    region: "Emberhold",
    type: "Artifact",
    archetypeKey: "structure",
    archetypeName: "Estrutura",
    cost: 3,
    maxHealth: 4,
    aura: { buffPower: 1, buffHealth: 0 },
    description: "Estrutura. Enquanto permanecer em campo, unidades aliadas recebem +1/+0.",
    flavor: "A muralha não detém o fogo. Ela lhe dá direção.",
    rarity: "Rare",
    emoji: "🏰",
    strategicRole: "engine",
    doctrineAffinities: ["ember_aggro"],
  },
  rfalpha_ember_ritual_red_rite: {
    defId: "rfalpha_ember_ritual_red_rite",
    name: "Rito da Chama Soberana",
    region: "Emberhold",
    type: "Spell",
    archetypeKey: "ritual",
    archetypeName: "Ritual",
    cost: 3,
    spell: {
      kind: "manaRefund", amount: 1, target: "none",
      also: { kind: "damageNexus", amount: 2, target: "none" },
    },
    description: "Ritual de Mana — somente na fase principal. Recupere 1 de mana e cause 2 de dano ao Nexus inimigo.",
    flavor: "Em Emberhold, mana guardada é fogo que ainda não encontrou alvo.",
    rarity: "Common",
    emoji: "🜂",
    strategicRole: "tempo",
    doctrineAffinities: ["ember_aggro"],
  },
  rfalpha_ember_trap_ash_snare: {
    defId: "rfalpha_ember_trap_ash_snare",
    name: "Cilada de Brasas",
    region: "Emberhold",
    type: "Spell",
    archetypeKey: "trap",
    archetypeName: "Armadilha",
    cost: 1,
    speed: "Burst",
    spell: { kind: "damageNexus", amount: 1, target: "none" },
    description: "Armadilha — somente como reação. Cause 1 de dano ao Nexus inimigo.",
    flavor: "Pise onde a cinza parece fria.",
    rarity: "Rare",
    emoji: "🪤",
    strategicRole: "tempo",
    doctrineAffinities: ["ember_aggro"],
  },

  // ───────────────────────────── Tidecall ──────────────────────────────
  rfalpha_tide_structure_silent_beacon: {
    defId: "rfalpha_tide_structure_silent_beacon",
    name: "Farol das Marés Silenciosas",
    region: "Tidecall",
    type: "Artifact",
    archetypeKey: "structure",
    archetypeName: "Estrutura",
    cost: 3,
    maxHealth: 4,
    aura: { buffPower: 0, buffHealth: 1 },
    description: "Estrutura. Enquanto permanecer em campo, unidades aliadas recebem +0/+1.",
    flavor: "Ele não guia navios. Guia correntes inteiras.",
    rarity: "Rare",
    emoji: "🏰",
    strategicRole: "defense",
    doctrineAffinities: ["tide_control"],
  },
  rfalpha_tide_ritual_memory_tide: {
    defId: "rfalpha_tide_ritual_memory_tide",
    name: "Liturgia da Maré da Memória",
    region: "Tidecall",
    type: "Spell",
    archetypeKey: "ritual",
    archetypeName: "Ritual",
    cost: 3,
    spell: {
      kind: "manaRefund", amount: 1, target: "none",
      also: { kind: "draw", amount: 1, target: "none" },
    },
    description: "Ritual de Mana — somente na fase principal. Recupere 1 de mana e compre 1 carta.",
    flavor: "A maré devolve recursos e lembranças com a mesma naturalidade.",
    rarity: "Common",
    emoji: "🜂",
    strategicRole: "engine",
    doctrineAffinities: ["tide_control"],
  },
  rfalpha_tide_trap_countercurrent: {
    defId: "rfalpha_tide_trap_countercurrent",
    name: "Selo da Contramaré",
    region: "Tidecall",
    type: "Spell",
    archetypeKey: "trap",
    archetypeName: "Armadilha",
    cost: 3,
    speed: "Burst",
    spell: { kind: "negateSpell", amount: 0, target: "spellOnStack" },
    description: "Armadilha — somente como reação. Negue a ação na pilha, se ela puder ser anulada.",
    flavor: "A corrente mais perigosa é a que decide voltar.",
    rarity: "Rare",
    emoji: "🪤",
    strategicRole: "removal",
    doctrineAffinities: ["tide_control"],
  },

  // ───────────────────────────── Ironwood ──────────────────────────────
  rfalpha_wood_structure_root_circle: {
    defId: "rfalpha_wood_structure_root_circle",
    name: "Círculo das Raízes de Ferro",
    region: "Ironwood",
    type: "Artifact",
    archetypeKey: "structure",
    archetypeName: "Estrutura",
    cost: 4,
    maxHealth: 5,
    aura: { buffPower: 0, buffHealth: 1 },
    description: "Estrutura. Enquanto permanecer em campo, unidades aliadas recebem +0/+1.",
    flavor: "O bosque aprendeu a erguer muralhas sem cortar uma única árvore.",
    rarity: "Rare",
    emoji: "🏰",
    strategicRole: "defense",
    doctrineAffinities: ["wood_midrange"],
  },
  rfalpha_wood_ritual_ancient_roots: {
    defId: "rfalpha_wood_ritual_ancient_roots",
    name: "Rito das Raízes Antigas",
    region: "Ironwood",
    type: "Spell",
    archetypeKey: "ritual",
    archetypeName: "Ritual",
    cost: 4,
    spell: {
      kind: "manaRefund", amount: 2, target: "none",
      also: { kind: "buffAllies", amount: 0, buffPower: 0, buffHealth: 1, target: "none" },
    },
    description: "Ritual de Mana — somente na fase principal. Recupere 2 de mana e unidades aliadas recebem +0/+1.",
    flavor: "Ironwood investe fundo para que cada raiz devolva mais do que recebeu.",
    rarity: "Common",
    emoji: "🜂",
    strategicRole: "engine",
    doctrineAffinities: ["wood_midrange"],
  },
  rfalpha_wood_trap_emergency_bark: {
    defId: "rfalpha_wood_trap_emergency_bark",
    name: "Casca de Emergência",
    region: "Ironwood",
    type: "Spell",
    archetypeKey: "trap",
    archetypeName: "Armadilha",
    cost: 1,
    speed: "Burst",
    spell: { kind: "grantBarrier", amount: 0, target: "allyUnit" },
    description: "Armadilha — somente como reação. Conceda Barreira a uma unidade aliada.",
    flavor: "A árvore fecha a ferida antes que o machado perceba.",
    rarity: "Rare",
    emoji: "🪤",
    strategicRole: "defense",
    doctrineAffinities: ["wood_midrange"],
  },

  // ───────────────────────────── Voidborn ──────────────────────────────
  rfalpha_void_structure_hollow_obelisk: {
    defId: "rfalpha_void_structure_hollow_obelisk",
    name: "Obelisco da Sombra Oca",
    region: "Voidborn",
    type: "Artifact",
    archetypeKey: "structure",
    archetypeName: "Estrutura",
    cost: 3,
    maxHealth: 4,
    aura: { buffPower: 1, buffHealth: 0, races: ["Voidling"] },
    description: "Estrutura. Enquanto permanecer em campo, Voidlings aliados recebem +1/+0.",
    flavor: "Ele projeta uma sombra mesmo quando não há luz.",
    rarity: "Rare",
    emoji: "🏰",
    strategicRole: "engine",
    doctrineAffinities: ["void_shadow"],
  },
  rfalpha_void_ritual_emptiness: {
    defId: "rfalpha_void_ritual_emptiness",
    name: "Liturgia da Ausência",
    region: "Voidborn",
    type: "Spell",
    archetypeKey: "ritual",
    archetypeName: "Ritual",
    cost: 3,
    spell: {
      kind: "manaRefund", amount: 1, target: "none",
      also: { kind: "mill", amount: 3, target: "none" },
    },
    description: "Ritual de Mana — somente na fase principal. Recupere 1 de mana e descarte 3 cartas do topo do deck inimigo.",
    flavor: "O Vazio devolve uma centelha apenas para cobrar memória em troca.",
    rarity: "Common",
    emoji: "🜂",
    strategicRole: "engine",
    doctrineAffinities: ["void_shadow"],
  },
  rfalpha_void_trap_early_eclipse: {
    defId: "rfalpha_void_trap_early_eclipse",
    name: "Eclipse Prematuro",
    region: "Voidborn",
    type: "Spell",
    archetypeKey: "trap",
    archetypeName: "Armadilha",
    cost: 1,
    speed: "Burst",
    spell: { kind: "mill", amount: 2, target: "none" },
    description: "Armadilha — somente como reação. Descarte 2 cartas do topo do deck inimigo.",
    flavor: "Às vezes a noite chega antes do sol terminar a frase.",
    rarity: "Rare",
    emoji: "🪤",
    strategicRole: "tempo",
    doctrineAffinities: ["void_shadow"],
  },

  // ───────────────────────────── Florestia ─────────────────────────────
  rfalpha_forest_structure_ancestral_den: {
    defId: "rfalpha_forest_structure_ancestral_den",
    name: "Toca da Matilha Ancestral",
    region: "Florestia",
    type: "Artifact",
    archetypeKey: "structure",
    archetypeName: "Estrutura",
    cost: 3,
    maxHealth: 4,
    aura: { buffPower: 1, buffHealth: 1, races: ["Besta"] },
    description: "Estrutura. Enquanto permanecer em campo, Bestas aliadas recebem +1/+1.",
    flavor: "Cada marca na pedra é o nome de uma matilha que voltou para casa.",
    rarity: "Rare",
    emoji: "🏰",
    strategicRole: "engine",
    doctrineAffinities: ["florestia_tribal"],
  },
  rfalpha_forest_ritual_green_moon: {
    defId: "rfalpha_forest_ritual_green_moon",
    name: "Uivo da Lua Verde",
    region: "Florestia",
    type: "Spell",
    archetypeKey: "ritual",
    archetypeName: "Ritual",
    cost: 3,
    spell: {
      kind: "manaRefund", amount: 1, target: "none",
      also: { kind: "buffRace", amount: 0, buffPower: 1, buffHealth: 1, race: "Besta", target: "none" },
    },
    description: "Ritual de Mana — somente na fase principal. Recupere 1 de mana e Bestas aliadas recebem +1/+1.",
    flavor: "A matilha converte presença em força e força novamente em movimento.",
    rarity: "Common",
    emoji: "🜂",
    strategicRole: "engine",
    doctrineAffinities: ["florestia_tribal"],
  },
  rfalpha_forest_trap_pack_ambush: {
    defId: "rfalpha_forest_trap_pack_ambush",
    name: "Emboscada da Alcateia",
    region: "Florestia",
    type: "Spell",
    archetypeKey: "trap",
    archetypeName: "Armadilha",
    cost: 2,
    speed: "Burst",
    spell: { kind: "buffAllies", amount: 0, buffPower: 1, buffHealth: 0, target: "none" },
    description: "Armadilha — somente como reação. Unidades aliadas recebem +1/+0.",
    flavor: "Quando você vê a primeira presa, as outras já fecharam o círculo.",
    rarity: "Rare",
    emoji: "🪤",
    strategicRole: "tempo",
    doctrineAffinities: ["florestia_tribal"],
  },

  // ───────────────────────────── Tempestade ────────────────────────────
  rfalpha_storm_structure_first_thunder: {
    defId: "rfalpha_storm_structure_first_thunder",
    name: "Torre do Primeiro Trovão",
    region: "Tempestade",
    type: "Artifact",
    archetypeKey: "structure",
    archetypeName: "Estrutura",
    cost: 3,
    maxHealth: 3,
    aura: { buffPower: 1, buffHealth: 0, races: ["Tempesteiro", "Anjo"] },
    description: "Estrutura. Enquanto permanecer em campo, Tempesteiros e Anjos aliados recebem +1/+0.",
    flavor: "O céu sempre avisa. A torre é quem traduz.",
    rarity: "Rare",
    emoji: "🏰",
    strategicRole: "engine",
    doctrineAffinities: ["tempestade_rush"],
  },
  rfalpha_storm_ritual_eye_of_storm: {
    defId: "rfalpha_storm_ritual_eye_of_storm",
    name: "Rito do Olho da Tempestade",
    region: "Tempestade",
    type: "Spell",
    archetypeKey: "ritual",
    archetypeName: "Ritual",
    cost: 3,
    spell: {
      kind: "manaRefund", amount: 2, target: "none",
      also: { kind: "stun", amount: 0, target: "enemyUnit" },
    },
    description: "Ritual de Mana — somente na fase principal. Recupere 2 de mana e atordoe uma unidade inimiga.",
    flavor: "Tempestade não economiza energia; concentra tudo no mesmo instante.",
    rarity: "Common",
    emoji: "🜂",
    strategicRole: "tempo",
    doctrineAffinities: ["tempestade_rush"],
  },
  rfalpha_storm_trap_crosswind: {
    defId: "rfalpha_storm_trap_crosswind",
    name: "Contravento Súbito",
    region: "Tempestade",
    type: "Spell",
    archetypeKey: "trap",
    archetypeName: "Armadilha",
    cost: 2,
    speed: "Fast",
    spell: { kind: "stun", amount: 0, target: "enemyUnit" },
    description: "Armadilha — somente como reação. Atordoe uma unidade inimiga.",
    flavor: "O vento muda antes que o ataque perceba que começou.",
    rarity: "Rare",
    emoji: "🪤",
    strategicRole: "tempo",
    doctrineAffinities: ["tempestade_rush"],
  },
};
