"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { type FormEvent, useEffect, useState } from "react";
import SiteNav from "@/components/SiteNav";
import { createGuestPlayerSession, renamePlayerDisplayName } from "@/lib/client-player-session";
import { ALPHA_FIRST_MATCH_DIFFICULTY, ALPHA_ONBOARDING_COMPLETE, ALPHA_ONBOARDING_STORAGE_KEY, shouldShowAlphaOnboarding } from "@/lib/alpha-onboarding";
import { PRODUCT_BRAND } from "@/lib/product-brand";
import GameClient from "./GameClient";

type EntryState = "syncing" | "auth" | "nickname" | "welcome" | "ready" | "error";
type Provider = { provider:"google"|"discord"|"email"; enabled:boolean };

export default function PlayEntryClient() {
  const router=useRouter();
  const [state,setState]=useState<EntryState>("syncing"),[playerName,setPlayerName]=useState(""),[providers,setProviders]=useState<Provider[]>([]),[nickname,setNickname]=useState(""),[email,setEmail]=useState(""),[message,setMessage]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[attempt,setAttempt]=useState(0);

  useEffect(()=>{
    let cancelled=false;
    const sync=async()=>{setState("syncing");setError("");try{
      const current=await fetch("/api/player",{cache:"no-store",credentials:"include"});
      if(cancelled)return;
      if(current.ok){const payload=await current.json();const name=String(payload.player?.name||"");if(!name)throw new Error("Perfil de jogador inválido.");setPlayerName(name);if(name.toLowerCase().startsWith("guest-")){setNickname("");setState("nickname");return;}const completed=localStorage.getItem(ALPHA_ONBOARDING_STORAGE_KEY)===ALPHA_ONBOARDING_COMPLETE;setState(shouldShowAlphaOnboarding({created:false,completed})?"welcome":"ready");return;}
      if(current.status!==401)throw new Error("Não foi possível consultar sua sessão de jogador.");
      const r=await fetch("/api/auth/providers",{cache:"no-store"});
      let d:{ok?:boolean;providers?:Provider[];error?:string}|null=null;
      try{d=await r.json();}catch{
        // Provider discovery is optional for Guest access. A proxy/runtime/database
        // failure must not make /play unusable or hide the explicit Guest fallback.
      }
      if(r.ok&&d?.ok&&Array.isArray(d.providers))setProviders(d.providers);
      else setProviders([]);
      const authError=new URLSearchParams(window.location.search).get("auth_error");if(authError)setMessage(authError==="identity_conflict"?"Esta identidade já pertence a outra conta.":"Não foi possível concluir a autenticação. Tente novamente.");setState("auth");
    }catch(cause){if(cancelled)return;setError(cause instanceof Error?cause.message:"Não foi possível preparar sua sessão de jogador.");setState("error");}};void sync();return()=>{cancelled=true;};
  },[attempt]);

  const providerEnabled=(p:Provider["provider"])=>providers.some(x=>x.provider===p&&x.enabled);
  const oauth=(provider:"google"|"discord")=>{router.push(`/api/auth/oauth/${provider}/start?returnTo=${encodeURIComponent("/play")}`);};
  const magic=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setMessage("");try{const r=await fetch("/api/auth/email/start",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,returnTo:"/play"})});const d=await r.json();setMessage(d.ok?"Link enviado. Abra seu e-mail para entrar na Forja.":d.error||"Não foi possível enviar o link.");}finally{setBusy(false);}};
  const guest=async()=>{setBusy(true);setMessage("");try{const session=await createGuestPlayerSession();if(!session.ok||!session.player)throw new Error(session.error||"Não foi possível criar a sessão de convidado.");setPlayerName(String(session.player.name));setNickname("");setState("nickname");}catch(cause){setMessage(cause instanceof Error?cause.message:"Falha ao continuar como convidado.");}finally{setBusy(false);}};
  const forgeName=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setMessage("");try{const result=await renamePlayerDisplayName(nickname);if(!result.ok||!result.player){setMessage(result.error||"Nome indisponível.");return;}const name=String(result.player.name);setPlayerName(name);const completed=localStorage.getItem(ALPHA_ONBOARDING_STORAGE_KEY)===ALPHA_ONBOARDING_COMPLETE;if(shouldShowAlphaOnboarding({created:true,completed})){localStorage.setItem("runeforge_ai_difficulty",ALPHA_FIRST_MATCH_DIFFICULTY);setState("welcome");}else setState("ready");}finally{setBusy(false);}};

  if(state==="ready")return <GameClient/>;
  if(state==="syncing")return <main className="rf-app-page"><SiteNav/><div className="rf-app-shell max-w-4xl"><section className="rounded-2xl border border-white/10 bg-white/[.03] px-6 py-16 text-center" aria-busy="true"><div className="mx-auto mb-4 h-9 w-9 animate-spin rounded-full border-2 border-white/10 border-t-amber-300"/><p className="rf-eyebrow justify-center"><span/> PREPARANDO O NEXUS</p><h1 className="mt-3 text-3xl font-black text-white">Verificando sua identidade…</h1></section></div></main>;
  if(state==="error")return <main className="rf-app-page"><SiteNav/><div className="rf-app-shell max-w-4xl"><section className="rounded-2xl border border-red-400/20 bg-red-400/[.05] px-6 py-12 text-center" role="alert"><p className="rf-eyebrow justify-center"><span/> SESSÃO INDISPONÍVEL</p><h1 className="mt-3 text-3xl font-black text-white">Não conseguimos abrir sua jornada.</h1><p className="mx-auto mt-3 max-w-xl text-sm leading-6 text-red-100/80">{error}</p><div className="mt-6 flex justify-center gap-3"><button className="rf-button rf-button-primary" onClick={()=>setAttempt(v=>v+1)}>TENTAR NOVAMENTE</button><Link href="/" className="rf-button rf-button-secondary">VOLTAR</Link></div></section></div></main>;

  if(state==="auth")return <main className="rf-app-page"><SiteNav/><div className="rf-app-shell max-w-5xl"><section className="relative overflow-hidden rounded-3xl border border-amber-300/20 bg-[radial-gradient(circle_at_20%_0%,rgba(217,164,65,.16),transparent_34rem),linear-gradient(145deg,rgba(255,255,255,.045),rgba(255,255,255,.012))] p-6 sm:p-10"><div className="absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-amber-200/60 to-transparent"/><div className="mx-auto max-w-xl text-center"><p className="rf-eyebrow justify-center"><span/> IDENTIDADE {PRODUCT_BRAND.displayName}</p><h1 className="mt-4 text-4xl font-black text-white sm:text-5xl">Entre na <em className="not-italic text-amber-200">Forja</em>.</h1><p className="mt-4 text-sm leading-6 text-slate-400">Sua identidade protege coleção, decks, progressão e histórico. Escolha como quer continuar.</p></div>{message&&<div className="mx-auto mt-6 max-w-xl rounded-xl border border-white/10 bg-black/25 p-3 text-center text-sm text-slate-200">{message}</div>}<div className="mx-auto mt-7 grid max-w-xl gap-3">{providerEnabled("google")&&<button className="rf-button rf-button-secondary w-full justify-center" onClick={()=>oauth("google")}>CONTINUAR COM GOOGLE</button>}{providerEnabled("discord")&&<button className="rf-button rf-button-secondary w-full justify-center" onClick={()=>oauth("discord")}>CONTINUAR COM DISCORD</button>}{providerEnabled("email")&&<form onSubmit={magic} className="mt-2 rounded-2xl border border-white/10 bg-black/20 p-4 text-left"><label className="text-xs font-black uppercase tracking-[.12em] text-slate-300">Entrar por e-mail</label><div className="mt-3 flex flex-col gap-2 sm:flex-row"><input required type="email" className="input flex-1" value={email} onChange={e=>setEmail(e.target.value)} placeholder="voce@email.com"/><button disabled={busy} className="rf-button rf-button-primary justify-center" type="submit">{busy?"ENVIANDO…":"ENVIAR LINK"}</button></div><p className="mt-2 text-xs text-slate-500">Sem senha. O link expira em 15 minutos e funciona uma única vez.</p></form>}<div className="relative my-2 text-center text-[10px] font-black uppercase tracking-[.18em] text-slate-600"><span className="bg-[#090b10] px-3">ou</span></div><button disabled={busy} className="rf-button rf-button-secondary w-full justify-center opacity-80" onClick={guest}>CONTINUAR COMO CONVIDADO</button><p className="text-center text-[11px] leading-5 text-slate-500">Você poderá vincular Google, Discord ou e-mail depois sem perder seu progresso.</p></div></section></div></main>;

  if(state==="nickname")return <main className="rf-app-page"><SiteNav/><div className="rf-app-shell max-w-3xl"><section className="rounded-3xl border border-cyan-300/15 bg-white/[.03] p-7 text-center sm:p-10"><p className="rf-eyebrow justify-center"><span/> FORJE SUA IDENTIDADE</p><h1 className="mt-4 text-4xl font-black text-white">Como os outros forjadores vão conhecer você?</h1><p className="mx-auto mt-3 max-w-xl text-sm leading-6 text-slate-400">Escolha seu nome em {PRODUCT_BRAND.displayName}. Seu login fica separado do perfil público e você poderá personalizar avatar, título e banner depois.</p><form onSubmit={forgeName} className="mx-auto mt-7 max-w-md"><input autoFocus required minLength={2} maxLength={40} className="input text-center text-lg font-black" value={nickname} onChange={e=>setNickname(e.target.value)} placeholder="Seu nome na Forja"/>{message&&<p className="mt-3 text-sm text-amber-200">{message}</p>}<button disabled={busy||nickname.trim().length<2} className="rf-button rf-button-primary mt-4 w-full justify-center" type="submit">{busy?"FORJANDO…":"FORJAR IDENTIDADE"}</button></form></section></div></main>;

  const begin=()=>{localStorage.setItem(ALPHA_ONBOARDING_STORAGE_KEY,ALPHA_ONBOARDING_COMPLETE);localStorage.setItem("runeforge_ai_difficulty",ALPHA_FIRST_MATCH_DIFFICULTY);setState("ready");};
  return <main className="rf-app-page"><SiteNav/><div className="rf-app-shell max-w-5xl"><section className="relative overflow-hidden rounded-3xl border border-amber-300/20 bg-[radial-gradient(circle_at_20%_0%,rgba(217,164,65,.15),transparent_35rem),linear-gradient(145deg,rgba(255,255,255,.045),rgba(255,255,255,.012))] p-6 sm:p-8 lg:p-10"><p className="rf-eyebrow"><span/> PRIMEIRO ACESSO · ALPHA JOGÁVEL</p><div className="mt-4 grid gap-8 lg:grid-cols-[1.2fr_.8fr]"><div><h1 className="text-4xl font-black leading-tight text-white sm:text-5xl">Bem-vindo ao Nexus,<br/><em className="text-amber-200 not-italic">{playerName}</em>.</h1><p className="mt-4 max-w-2xl text-base leading-7 text-slate-300">Sua identidade está pronta. A primeira batalha usa a IA <strong className="text-white">Aprendiz</strong> e abre o guia de combate.</p><div className="mt-7 grid gap-3 sm:grid-cols-3"><OnboardingStep number="01" title="Escolha um deck" copy="Comece com um deck oficial."/><OnboardingStep number="02" title="Aprenda no campo" copy="Mulligan, mana, combate e respostas serão guiados."/><OnboardingStep number="03" title="Receba progresso" copy="XP, ouro e coleção ficam ligados à sua conta."/></div><button className="rf-button rf-button-primary mt-8" onClick={begin}>COMEÇAR TREINAMENTO <b>→</b></button></div><aside className="rounded-2xl border border-cyan-300/15 bg-black/25 p-5"><p className="text-[10px] font-black uppercase tracking-[.18em] text-cyan-300/70">CONTA PERSISTENTE</p><h2 className="mt-2 text-xl font-black text-white">Seu progresso acompanha você</h2><p className="mt-2 text-sm leading-6 text-slate-400">Google, Discord e e-mail podem ser vinculados ao mesmo jogador sem mover cartas, decks, ouro ou MMR.</p><Link href="/profile" className="mt-4 inline-flex text-xs font-black uppercase tracking-[.12em] text-cyan-200">VER PERFIL →</Link></aside></div></section></div></main>;
}

function OnboardingStep({number,title,copy}:{number:string;title:string;copy:string}){return <article className="rounded-2xl border border-white/10 bg-black/20 p-4"><span className="font-mono text-[10px] font-black text-amber-300/70">{number}</span><h2 className="mt-2 text-sm font-black text-white">{title}</h2><p className="mt-1 text-xs leading-5 text-slate-400">{copy}</p></article>}