import type { CardDef } from "../../types";

export const EMBERHOLD_CARDS: Record<string, CardDef> = {
  ember_whelp: {
    defId: "ember_whelp",
    name: "Cinder Whelp",
    region: "Emberhold",
    type: "Unit",
    cost: 1,
    power: 2,
    health: 1,
    race: "Dragon",
    keywords: [],
    description: "Dragon. A tiny drake spoiling for a fight.",
    rarity: "Common",
    emoji: "🐉",
  },
  ember_raider: {
    defId: "ember_raider",
    name: "Ashfront Raider",
    region: "Emberhold",
    type: "Unit",
    cost: 2,
    power: 3,
    health: 2,
    race: "Warrior",
    keywords: ["QuickAttack"],
    description: "Warrior. Quick Attack: strikes first in combat.",
    rarity: "Common",
    emoji: "⚔️",
  },
  ember_herald: {
    defId: "ember_herald",
    name: "Cinder Herald",
    region: "Emberhold",
    type: "Unit",
    cost: 2,
    power: 2,
    health: 2,
    keywords: [],
    description: "Play: deal 1 to the enemy Nexus.",
    rarity: "Common",
    emoji: "📯",
    trigger: { when: "onSummon", effect: { kind: "damageNexus", amount: 1, target: "none" } },
  },
  ember_duelist: {
    defId: "ember_duelist",
    name: "Ash Duelist",
    region: "Emberhold",
    type: "Unit",
    cost: 3,
    power: 3,
    health: 3,
    keywords: ["Challenger"],
    description: "Challenger: force an enemy to block this attacker.",
    rarity: "Rare",
    emoji: "🤺",
  },
  ember_zealot: {
    defId: "ember_zealot",
    name: "Emberfang Zealot",
    region: "Emberhold",
    type: "Unit",
    cost: 3,
    power: 4,
    health: 2,
    race: "Dragon",
    keywords: ["Overwhelm"],
    description: "Dragon. Overwhelm: excess damage hits the enemy Nexus.",
    rarity: "Rare",
    emoji: "🔥",
  },
  ember_hatchery: {
    defId: "ember_hatchery",
    name: "Drake Hatchery",
    region: "Emberhold",
    type: "Unit",
    cost: 4,
    power: 2,
    health: 4,
    keywords: [],
    description: "Play: summon a 1/1 Ember Spark.",
    rarity: "Rare",
    emoji: "🥚",
    trigger: {
      when: "onSummon",
      effect: { kind: "summonToken", amount: 1, target: "none", tokenDefId: "ember_spark" },
    },
  },
  ember_spark: {
    defId: "ember_spark",
    name: "Ember Spark",
    region: "Emberhold",
    type: "Unit",
    cost: 0,
    power: 1,
    health: 1,
    keywords: [],
    description: "A fleeting ember given form.",
    rarity: "Common",
    collectible: false,
    emoji: "✨",
  },
  ember_champion: {
    defId: "ember_champion",
    name: "Pyra, the Everflame",
    region: "Emberhold",
    type: "Unit",
    cost: 5,
    power: 5,
    health: 4,
    race: "Dragon",
    keywords: ["Overwhelm", "QuickAttack"],
    description: "Champion (Dragon) — Overwhelm & Quick Attack. Level Up: I've dealt 8 damage to the enemy Nexus.",
    rarity: "Legend",
    isLegend: true,
    isChampion: true,
    art: "/images/champs/pyra.jpg",
    emoji: "👑",
    levelUp: {
      type: "nexusDamage",
      amount: 8,
      toDefId: "ember_champion_2",
      hint: "Deal 8 damage to the enemy Nexus",
    },
  },
  ember_champion_2: {
    defId: "ember_champion_2",
    name: "Pyra, Unbound Inferno",
    region: "Emberhold",
    type: "Unit",
    cost: 5,
    power: 6,
    health: 5,
    keywords: ["Overwhelm", "QuickAttack", "DoubleStrike"],
    description: "Leveled — Overwhelm, Quick Attack, Double Strike. Nexus Strike: deal 1 to all enemies. Level Up: I've dealt 16 damage to the enemy Nexus.",
    rarity: "Legend",
    isLegend: true,
    isChampion: true,
    collectible: false,
    art: "/images/champs/pyra.jpg",
    emoji: "👑",
    trigger: { when: "onNexusStrike", effect: { kind: "aoeEnemy", amount: 1, target: "none" } },
    levelUp: {
      type: "nexusDamage",
      amount: 16,
      toDefId: "ember_champion_3",
      hint: "Deal 16 total damage to the enemy Nexus",
    },
  },
  ember_champion_3: {
    defId: "ember_champion_3",
    name: "Pyra, the Everflame Ascendant",
    region: "Emberhold",
    type: "Unit",
    cost: 5,
    power: 8,
    health: 7,
    keywords: ["Overwhelm", "QuickAttack", "DoubleStrike", "Lifesteal"],
    description: "Fully Ascended — Overwhelm, Quick Attack, Double Strike, Lifesteal. Nexus Strike: deal 2 to all enemies.",
    rarity: "Legend",
    isLegend: true,
    isChampion: true,
    collectible: false,
    art: "/images/champs/pyra.jpg",
    emoji: "👑",
    trigger: { when: "onNexusStrike", effect: { kind: "aoeEnemy", amount: 2, target: "none" } },
  },
  ember_bolt: {
    defId: "ember_bolt",
    name: "Scorching Bolt",
    region: "Emberhold",
    type: "Spell",
    cost: 2,
    description: "Deal 3 damage to a unit.",
    rarity: "Common",
    emoji: "☄️",
    spell: { kind: "damageUnit", amount: 3, target: "anyUnit" },
  },
  ember_rain: {
    defId: "ember_rain",
    name: "Emberstorm",
    region: "Emberhold",
    type: "Spell",
    cost: 4,
    description: "Deal 2 damage to all enemy units.",
    rarity: "Rare",
    emoji: "🌋",
    spell: { kind: "aoeEnemy", amount: 2, target: "none" },
  },
  ember_face: {
    defId: "ember_face",
    name: "Meteor Strike",
    region: "Emberhold",
    type: "Spell",
    cost: 3,
    description: "Deal 3 damage to the enemy Nexus.",
    rarity: "Rare",
    emoji: "💥",
    spell: { kind: "damageNexus", amount: 3, target: "none" },
  },
  ember_cinder: {
    defId: "ember_cinder",
    name: "Cinder Snap",
    region: "Emberhold",
    type: "Spell",
    cost: 2,
    description: "Burst — deal 2 damage to a unit.",
    rarity: "Common",
    speed: "Burst",
    emoji: "🔥",
    spell: { kind: "damageUnit", amount: 2, target: "anyUnit" },
  },
  ember_drake: {
    defId: "ember_drake",
    name: "Kindle Drake",
    region: "Emberhold",
    type: "Unit",
    cost: 3,
    power: 2,
    health: 2,
    race: "Dragon",
    keywords: [],
    description: "Dragon. Rally: all Dragons get +1/+0.",
    rarity: "Common",
    emoji: "🐲",
    trigger: {
      when: "onSummon",
      effect: { kind: "buffAllies", amount: 0, buffPower: 1, buffHealth: 0, target: "none", race: "Dragon" },
    },
  },
  ember_sire: {
    defId: "ember_sire",
    name: "Cinderscale Sire",
    region: "Emberhold",
    type: "Unit",
    cost: 4,
    power: 4,
    health: 4,
    race: "Dragon",
    keywords: ["Overwhelm"],
    description: "Dragon. Rally: all Dragons get +2/+0.",
    rarity: "Rare",
    emoji: "🐉",
    trigger: {
      when: "onSummon",
      effect: { kind: "buffAllies", amount: 0, buffPower: 2, buffHealth: 0, target: "none", race: "Dragon" },
    },
  },
  ember_hearth: {
    defId: "ember_hearth",
    name: "Forgebound Hearth",
    region: "Emberhold",
    type: "Enchantment",
    cost: 3,
    maxHealth: 3,
    description: "Round Start: all Dragons get +1/+0.",
    rarity: "Rare",
    emoji: "🔥",
    trigger: {
      when: "onRoundStart",
      effect: { kind: "buffAllies", amount: 0, buffPower: 1, buffHealth: 0, target: "none", race: "Dragon" },
    },
  },
  ember_forgeheart: {
    defId: "ember_forgeheart",
    name: "Forgeheart",
    region: "Emberhold",
    type: "Artifact",
    cost: 4,
    maxHealth: 3,
    description: "When you summon a Dragon, refund 1 mana.",
    rarity: "Rare",
    emoji: "⚙️",
    trigger: {
      when: "onPermanentSummon",
      effect: { kind: "manaRefund", amount: 1, target: "none", race: "Dragon" },
    },
  },
  ember_blade: {
    defId: "ember_blade",
    name: "Flamebrand",
    region: "Emberhold",
    type: "Equipment",
    cost: 2,
    equipment: { buffPower: 2, buffHealth: 0, keywords: ["Overwhelm"] },
    description: "Equip: +2/+0 and Overwhelm.",
    rarity: "Common",
    emoji: "🗡️",
  },
  ember_tide_wyrm: {
    defId: "ember_tide_wyrm",
    name: "Steamscale Wyrm",
    region: "Emberhold",
    type: "Unit",
    cost: 4,
    power: 3,
    health: 4,
    race: "Dragon",
    secondaryRaces: ["Elemental"],
    keywords: ["Tough"],
    description: "Dragon/Elemental. Play: all Dragons and Elementals get +1/+1.",
    rarity: "Epic",
    emoji: "🐲",
    trigger: {
      when: "onSummon",
      effect: {
        kind: "buffAllies",
        amount: 0,
        buffPower: 1,
        buffHealth: 1,
        target: "none",
        races: ["Dragon", "Elemental"],
      },
    },
  },
  ember_soulblade: {
    defId: "ember_soulblade",
    name: "Soulbrand",
    region: "Emberhold",
    type: "Equipment",
    cost: 3,
    equipment: { buffPower: 2, buffHealth: 1, keywords: ["Overwhelm"] },
    description: "Equip: +2/+1 and Overwhelm. Kill: draw 1.",
    rarity: "Rare",
    emoji: "🗡️",
    trigger: { when: "onKill", effect: { kind: "draw", amount: 1, target: "none" } },
  },
  ember_shatter: {
    defId: "ember_shatter",
    name: "Shatterforge",
    region: "Emberhold",
    type: "Spell",
    cost: 2,
    description: "Destroy an enemy Enchantment or Artifact.",
    rarity: "Common",
    emoji: "🔨",
    spell: { kind: "destroyPermanent", amount: 0, target: "enemyPermanent" },
  },
  ember_anvil: {
    defId: "ember_anvil",
    name: "Anvil Chorus",
    region: "Emberhold",
    type: "Spell",
    cost: 3,
    description: "Give all Dragons and Warriors +1/+1.",
    rarity: "Rare",
    emoji: "⚒️",
    spell: {
      kind: "buffAllies",
      amount: 0,
      buffPower: 1,
      buffHealth: 1,
      target: "none",
      races: ["Dragon", "Warrior"],
    },
  },
  ember_phantom: {
    defId: "ember_phantom",
    name: "Flame Phantom",
    region: "Emberhold",
    type: "Unit",
    cost: 1,
    power: 3,
    health: 1,
    race: "Elemental",
    keywords: ["Ephemeral"],
    description: "Elemental. Ephemeral — dies at end of round or after striking. A flicker of fury.",
    rarity: "Common",
    emoji: "🔥",
  },
  ember_stun: {
    defId: "ember_stun",
    name: "Flame Lash",
    region: "Emberhold",
    type: "Spell",
    cost: 2,
    description: "Deal 1 damage and Stun an enemy unit.",
    rarity: "Common",
    emoji: "⚡",
    spell: {
      kind: "damageUnit",
      amount: 1,
      target: "enemyUnit",
      also: { kind: "stun", amount: 0, target: "enemyUnit" },
    },
  },
  ember_lastbreath: {
    defId: "ember_lastbreath",
    name: "Magma Egg",
    region: "Emberhold",
    type: "Unit",
    cost: 1,
    power: 0,
    health: 2,
    race: "Dragon",
    keywords: ["LastBreath"],
    description: "Dragon. Last Breath: deal 2 to the enemy Nexus.",
    rarity: "Common",
    emoji: "🥚",
    trigger: { when: "onDeath", effect: { kind: "damageNexus", amount: 2, target: "none" } },
  },
  ember_sprinter: {
    defId: "ember_sprinter",
    name: "Blitzrunner",
    region: "Emberhold",
    type: "Unit",
    cost: 2,
    power: 3,
    health: 1,
    race: "Warrior",
    keywords: ["Haste"],
    description: "Warrior. Haste — can attack the turn it is summoned.",
    rarity: "Common",
    emoji: "🏃",
  },
  ember_swarmlord: {
    defId: "ember_swarmlord",
    name: "Swarmlord",
    region: "Emberhold",
    type: "Unit",
    cost: 8,
    power: 7,
    health: 7,
    race: "Dragon",
    keywords: ["Overwhelm"],
    description: "Dragon. Affinity — costs 1 less for each creature you control.",
    rarity: "Legend",
    isLegend: true,
    emoji: "🐲",
    costReduction: { kind: "creatures", per: 1 },
  },
  sent_vulkar: {
    defId: "sent_vulkar",
    name: "Vulkar, a Chama Eterna",
    region: "Emberhold",
    type: "Sentinela",
    cost: 5,
    description: "Sentinela — canaliza o fogo para queimar tudo.",
    rarity: "Legend",
    isLegend: true,
    emoji: "🔥",
    sentinela: {
      startingLoyalty: 4,
      abilities: [
        { cost: 1, description: "+1: causa 2 de dano a uma criatura", effect: { kind: "damageUnit", amount: 2, target: "anyUnit" } },
        { cost: -2, description: "-2: causa 3 de dano ao Nexus inimigo", effect: { kind: "damageNexus", amount: 3, target: "none" } },
        { cost: -6, description: "-6: causa 5 de dano a todas as criaturas inimigas", effect: { kind: "aoeEnemy", amount: 5, target: "none" } },
      ],
    },
  },
  flame_imp: {
    defId: "flame_imp",
    name: "Diabrete Flamejante",
    region: "Emberhold",
    type: "Unit",
    cost: 1,
    power: 2,
    health: 1,
    race: "Elemental",
    keywords: ["Haste"],
    description: "Elemental. Ímpeto.",
    rarity: "Common",
    emoji: "👺",
  },
  ember_battlerager: {
    defId: "ember_battlerager",
    name: "Berserker da Brasa",
    region: "Emberhold",
    type: "Unit",
    cost: 3,
    power: 3,
    health: 3,
    race: "Warrior",
    keywords: ["Overwhelm"],
    description: "Guerreiro. Atropelar.",
    rarity: "Common",
    emoji: "🪓",
  },
  ember_pyromancer: {
    defId: "ember_pyromancer",
    name: "Piromante Sênior",
    region: "Emberhold",
    type: "Unit",
    cost: 4,
    power: 3,
    health: 4,
    race: "Elemental",
    keywords: [],
    description: "Elemental. Invocar: causa 1 de dano a todas as criaturas inimigas.",
    rarity: "Rare",
    emoji: "🧙",
    trigger: { when: "onSummon", effect: { kind: "aoeEnemy", amount: 1, target: "none" } },
  },
  ember_dragonwhelp: {
    defId: "ember_dragonwhelp",
    name: "Filhote de Dragão",
    region: "Emberhold",
    type: "Unit",
    cost: 2,
    power: 2,
    health: 2,
    race: "Dragon",
    keywords: [],
    description: "Dragão. Ao matar uma criatura, ganha +1/+1.",
    rarity: "Common",
    emoji: "🐲",
    trigger: { when: "onKill", effect: { kind: "buffSelf", amount: 0, buffPower: 1, buffHealth: 1, target: "self" } },
  },
  ember_embermage: {
    defId: "ember_embermage",
    name: "Maga das Brasas",
    region: "Emberhold",
    type: "Unit",
    cost: 3,
    power: 2,
    health: 3,
    race: "Spirit",
    keywords: [],
    description: "Espírito. Início de Rodada: causa 1 de dano ao Nexus inimigo.",
    rarity: "Rare",
    emoji: "🔥",
    trigger: { when: "onRoundStart", effect: { kind: "damageNexus", amount: 1, target: "none" } },
  },
  ember_scorchling: {
    defId: "ember_scorchling",
    name: "Chamuscarito",
    region: "Emberhold",
    type: "Unit",
    cost: 2,
    power: 3,
    health: 1,
    race: "Elemental",
    keywords: ["Ephemeral"],
    description: "Elemental. Efêmero.",
    rarity: "Common",
    emoji: "♨️",
  },
  ember_ashguard: {
    defId: "ember_ashguard", name: "Guarda das Cinzas", region: "Emberhold", type: "Unit", cost: 2, power: 2, health: 3,
    race: "Warrior", keywords: ["Tough"], description: "Guerreiro. Resistente. Mantém a linha para que as chamas encontrem o alvo.", rarity: "Common", emoji: "🛡️",
  },
  ember_flare_line: {
    defId: "ember_flare_line", name: "Linha de Fulgor", region: "Emberhold", type: "Spell", cost: 3,
    description: "Cause 2 a uma unidade inimiga e 1 ao Nexus inimigo.", rarity: "Rare", emoji: "🔥", speed: "Fast",
    spell: { kind: "damageUnit", amount: 2, target: "enemyUnit", also: { kind: "damageNexus", amount: 1, target: "none" } },
  },
  convergence_steamwright: {
    defId: "convergence_steamwright", name: "Engenheira da Forja a Vapor", region: "Emberhold", regions: ["Emberhold", "Tidecall"], regionalPerk: "convergence",
    type: "Unit", cost: 3, power: 3, health: 3, race: "Warrior", description: "Maestria da Forja a Vapor. Invocar: compre 1.", rarity: "Rare", emoji: "⚙️",
    trigger: { when: "onSummon", effect: { kind: "draw", amount: 1, target: "none" } }, strategicRole: "engine", doctrineAffinities: ["convergence_dual"],
  },
  convergence_cinderbark: {
    defId: "convergence_cinderbark", name: "Colosso de Casca Incandescente", region: "Emberhold", regions: ["Emberhold", "Ironwood"], regionalPerk: "assault",
    type: "Unit", cost: 4, power: 4, health: 5, race: "Elemental", keywords: ["Tough"], description: "O fogo endurece as raízes em vez de consumi-las.", rarity: "Epic", emoji: "🌋", strategicRole: "finisher", doctrineAffinities: ["convergence_dual"],
  },
  convergence_ashen_covenant: {
    defId: "convergence_ashen_covenant", name: "Pacto das Cinzas Profanas", region: "Emberhold", regions: ["Emberhold", "Voidborn"], regionalPerk: "convergence",
    type: "Spell", cost: 4, description: "Cause 3 a uma unidade inimiga e cure 3 do seu Nexus.", rarity: "Epic", emoji: "🩸", speed: "Fast",
    spell: { kind: "damageUnit", amount: 3, target: "enemyUnit", also: { kind: "healNexus", amount: 3, target: "none" } }, strategicRole: "removal", doctrineAffinities: ["convergence_dual"],
  },
  convergence_huntfire_alpha: {
    defId: "convergence_huntfire_alpha", name: "Alfa da Caçada da Brasa", region: "Emberhold", regions: ["Emberhold", "Florestia"], regionalPerk: "assault",
    type: "Unit", cost: 4, power: 4, health: 4, race: "Besta", keywords: ["Haste"], description: "A matilha segue o rastro deixado pelo incêndio.", rarity: "Rare", emoji: "🐺", strategicRole: "tempo", doctrineAffinities: ["convergence_dual"],
  },
  convergence_stormforge_vanguard: {
    defId: "convergence_stormforge_vanguard", name: "Vanguarda da Forja do Trovão", region: "Emberhold", regions: ["Emberhold", "Tempestade"], regionalPerk: "convergence",
    type: "Unit", cost: 4, power: 4, health: 3, race: "Tempesteiro", keywords: ["QuickAttack"], description: "Cada golpe termina de forjar a própria lâmina.", rarity: "Rare", emoji: "⚡", strategicRole: "tempo", doctrineAffinities: ["convergence_dual"],
  },
  convergence_living_forge_architect: {
    defId: "convergence_living_forge_architect", name: "Arquiteta da Tríade da Criação", region: "Emberhold", regions: ["Emberhold", "Tidecall", "Ironwood"], regionalPerk: "convergence",
    type: "Unit", cost: 6, power: 5, health: 6, race: "Warrior", description: "Invocar: compre 1. Fogo molda, água tempera e raízes dão memória.", rarity: "Legend", emoji: "🔱",
    trigger: { when: "onSummon", effect: { kind: "draw", amount: 1, target: "none" } }, strategicRole: "engine", doctrineAffinities: ["convergence_triad"],
  },
  convergence_black_lightning: {
    defId: "convergence_black_lightning", name: "Arauto da Tempestade Negra", region: "Emberhold", regions: ["Emberhold", "Voidborn", "Tempestade"], regionalPerk: "assault",
    type: "Unit", cost: 7, power: 6, health: 5, race: "Anjo", keywords: ["Fearsome", "Flying"], description: "O trovão queima até a sombra deixada pelo alvo.", rarity: "Legend", emoji: "🜂", strategicRole: "finisher", doctrineAffinities: ["convergence_triad"],
  },
  convergence_worldtree_wildfire: {
    defId: "convergence_worldtree_wildfire", name: "Árvore-Mundo em Chamas", region: "Emberhold", regions: ["Emberhold", "Ironwood", "Florestia"], regionalPerk: "convergence",
    type: "Enchantment", cost: 5, maxHealth: 6, description: "No início da rodada, dê +1/+1 aos aliados.", rarity: "Legend", emoji: "🌳",
    trigger: { when: "onRoundStart", effect: { kind: "buffAllies", amount: 0, buffPower: 1, buffHealth: 1, target: "none" } }, strategicRole: "engine", doctrineAffinities: ["convergence_triad"],
  },
};
