import type { CardDef } from "../../types";

export const FLORESTIA_CARDS: Record<string, CardDef> = {
  forest_cub: {
    defId: "forest_cub",
    name: "Filhote Feroz",
    region: "Florestia",
    type: "Unit",
    cost: 1,
    power: 1,
    health: 2,
    race: "Besta",
    keywords: [],
    description: "Besta. Um pequeno predador em treinamento.",
    rarity: "Common",
    emoji: "🐺",
  },
  forest_packrunner: {
    defId: "forest_packrunner",
    name: "Corredora da Matilha",
    region: "Florestia",
    type: "Unit",
    cost: 2,
    power: 2,
    health: 2,
    race: "Besta",
    keywords: [],
    description: "Besta. Invocar: todas as outras Bestas recebem +1/+0.",
    rarity: "Common",
    emoji: "🐾",
    trigger: { when: "onSummon", effect: { kind: "buffAllies", amount: 0, buffPower: 1, buffHealth: 0, target: "none", race: "Besta" } },
  },
  forest_stalker: {
    defId: "forest_stalker",
    name: "Espreitadora da Floresta",
    region: "Florestia",
    type: "Unit",
    cost: 3,
    power: 3,
    health: 3,
    race: "Besta",
    keywords: ["Reach"],
    description: "Besta. Alcance. Guarda o dossel contra invasores.",
    rarity: "Common",
    emoji: "🦅",
  },
  forest_thornfang: {
    defId: "forest_thornfang",
    name: "Presadente Espinhosa",
    region: "Florestia",
    type: "Unit",
    cost: 4,
    power: 4,
    health: 4,
    race: "Besta",
    keywords: ["Deathtouch"],
    description: "Besta. Toque Mortal. Ao matar uma criatura, compra 1.",
    rarity: "Rare",
    emoji: "🦁",
    trigger: { when: "onKill", effect: { kind: "draw", amount: 1, target: "none" } },
  },
  forest_alpha: {
    defId: "forest_alpha",
    name: "Alfa da Besta-Grande",
    region: "Florestia",
    type: "Unit",
    cost: 5,
    power: 5,
    health: 5,
    race: "Besta",
    keywords: ["Overwhelm"],
    description: "Besta. Atropelar. Invocar: toda Besta aliada ganha +2/+2.",
    rarity: "Epic",
    emoji: "🐻",
    trigger: { when: "onSummon", effect: { kind: "buffAllies", amount: 0, buffPower: 2, buffHealth: 2, target: "none", race: "Besta" } },
  },
  forest_champion: {
    defId: "forest_champion",
    name: "Kaara, Regente das Feras",
    region: "Florestia",
    type: "Unit",
    cost: 6,
    power: 5,
    health: 6,
    race: "Besta",
    keywords: ["Regeneration", "Challenger"],
    description: "Campeão (Besta) — Regeneração & Desafiador. Evoluir: 6+ Bestas invocadas.",
    rarity: "Legend",
    isLegend: true,
    isChampion: true,
    emoji: "🐅",
    levelUp: { type: "alliesSummoned", amount: 6, toDefId: "forest_champion_2", hint: "Invoke 6 allies" },
  },
  forest_champion_2: {
    defId: "forest_champion_2",
    name: "Kaara, Fera Ancestral",
    region: "Florestia",
    type: "Unit",
    cost: 6,
    power: 7,
    health: 8,
    race: "Besta",
    keywords: ["Regeneration", "Challenger", "Overwhelm"],
    description: "Evoluída — Regeneração, Desafiador & Atropelar. Início de Rodada: todas as Bestas recebem +1/+1.",
    rarity: "Legend",
    isLegend: true,
    isChampion: true,
    collectible: false,
    emoji: "🐅",
    trigger: { when: "onRoundStart", effect: { kind: "buffAllies", amount: 0, buffPower: 1, buffHealth: 1, target: "none", race: "Besta" } },
  },
  forest_cub_token: {
    defId: "forest_cub_token",
    name: "Filhote",
    region: "Florestia",
    type: "Unit",
    cost: 0,
    power: 1,
    health: 1,
    race: "Besta",
    keywords: [],
    description: "Uma Besta pequena.",
    rarity: "Common",
    collectible: false,
    emoji: "🐾",
  },
  forest_pack_howl: {
    defId: "forest_pack_howl",
    name: "Uivo da Matilha",
    region: "Florestia",
    type: "Spell",
    cost: 2,
    description: "Todas as criaturas aliadas ganham +1/+1 este turno.",
    rarity: "Common",
    emoji: "🌿",
    spell: { kind: "buffAllies", amount: 0, buffPower: 1, buffHealth: 1, target: "none" },
  },
  forest_summon_pack: {
    defId: "forest_summon_pack",
    name: "Convocar a Matilha",
    region: "Florestia",
    type: "Spell",
    cost: 4,
    description: "Invoca dois Filhotes 1/1.",
    rarity: "Rare",
    emoji: "🐺",
    spell: { kind: "summonToken", amount: 1, target: "none", tokenDefId: "forest_cub_token", also: { kind: "summonToken", amount: 1, target: "none", tokenDefId: "forest_cub_token" } },
  },
  forest_entangle: {
    defId: "forest_entangle",
    name: "Embaraçar",
    region: "Florestia",
    type: "Spell",
    cost: 2,
    description: "Atordoa uma unidade inimiga.",
    rarity: "Common",
    emoji: "🍃",
    spell: { kind: "stun", amount: 0, target: "enemyUnit" },
  },
  forest_ambush: {
    defId: "forest_ambush",
    name: "Emboscada do Bosque",
    region: "Florestia",
    type: "Spell",
    cost: 2,
    speed: "Fast",
    description: "Dá Barreira a uma criatura aliada. A matilha protege quem sustenta a linha.",
    rarity: "Common",
    emoji: "🛡️",
    spell: { kind: "grantBarrier", amount: 0, target: "allyUnit" },
  },
  forest_canopy_warden: {
    defId: "forest_canopy_warden",
    name: "Guardião da Copa",
    region: "Florestia",
    type: "Unit",
    cost: 4,
    power: 3,
    health: 4,
    race: "Besta",
    keywords: ["Reach"],
    description: "Besta. Alcance. Vigia o céu para que a matilha avance sem medo.",
    rarity: "Rare",
    emoji: "🦌",
  },
  forest_enchantment: {
    defId: "forest_enchantment",
    name: "Pacto da Floresta",
    region: "Florestia",
    type: "Enchantment",
    cost: 3,
    maxHealth: 4,
    description: "Início de Rodada: todas as Bestas aliadas recebem +1/+0.",
    rarity: "Rare",
    emoji: "📜",
    trigger: { when: "onRoundStart", effect: { kind: "buffAllies", amount: 0, buffPower: 1, buffHealth: 0, target: "none", race: "Besta" } },
  },
  sent_kaara: {
    defId: "sent_kaara",
    name: "Kaara, Guardiã do Bosque",
    region: "Florestia",
    type: "Sentinela",
    cost: 5,
    description: "Sentinela — fortalece a matilha e defende o bosque.",
    rarity: "Legend",
    isLegend: true,
    emoji: "🐾",
    sentinela: {
      startingLoyalty: 5,
      abilities: [
        { cost: 1, description: "+1: dá +1/+1 a todas as Bestas aliadas", effect: { kind: "buffAllies", amount: 0, buffPower: 1, buffHealth: 1, target: "none", race: "Besta" } },
        { cost: -2, description: "-2: invoca um Filhote 1/1", effect: { kind: "summonToken", amount: 1, target: "none", tokenDefId: "forest_cub_token" } },
        { cost: -9, description: "-9: cura 5 e dá Barreira a uma criatura", effect: { kind: "healUnit", amount: 5, target: "allyUnit", also: { kind: "grantBarrier", amount: 0, target: "allyUnit" } } },
      ],
    },
  },
  forest_moonfang: {
    defId: "forest_moonfang",
    name: "Presalunar",
    region: "Florestia",
    type: "Unit",
    cost: 3,
    power: 3,
    health: 3,
    race: "Besta",
    keywords: ["Lifesteal"],
    description: "Besta. Vampírico.",
    rarity: "Common",
    emoji: "🌙",
  },
  forest_terrormane: {
    defId: "forest_terrormane",
    name: "Crina-Terrível",
    region: "Florestia",
    type: "Unit",
    cost: 5,
    power: 6,
    health: 4,
    race: "Besta",
    keywords: ["Overwhelm"],
    description: "Besta. Atropelar.",
    rarity: "Rare",
    emoji: "🦁",
  },
  forest_soulpack: {
    defId: "forest_soulpack",
    name: "Alma da Matilha",
    region: "Florestia",
    type: "Unit",
    cost: 2,
    power: 2,
    health: 2,
    race: "Besta",
    keywords: [],
    description: "Besta. Início de Rodada: cura 1 de todas as Bestas aliadas.",
    rarity: "Rare",
    emoji: "🐺",
    trigger: { when: "onRoundStart", effect: { kind: "healUnit", amount: 1, target: "allyUnit" } },
  },
  forest_ironhide: {
    defId: "forest_ironhide",
    name: "Couro de Ferro",
    region: "Florestia",
    type: "Unit",
    cost: 4,
    power: 3,
    health: 5,
    race: "Besta",
    keywords: ["Tough"],
    description: "Besta. Resistente.",
    rarity: "Common",
    emoji: "🐗",
  },
  forest_moon_snare: {
    defId: "forest_moon_snare", name: "Laço da Lua", region: "Florestia", type: "Spell", cost: 2,
    description: "Atordoe uma unidade inimiga.", rarity: "Common", emoji: "🌙", speed: "Fast",
    spell: { kind: "stun", amount: 1, target: "enemyUnit" },
  },
  forest_predator_pounce: {
    defId: "forest_predator_pounce", name: "Bote do Predador", region: "Florestia", type: "Spell", cost: 3,
    description: "Cause 3 de dano a uma unidade inimiga.", rarity: "Rare", emoji: "🐾", speed: "Fast",
    spell: { kind: "damageUnit", amount: 3, target: "enemyUnit" },
  },
  forest_spirit_guide: {
    defId: "forest_spirit_guide", name: "Guia Espiritual da Matilha", region: "Florestia", type: "Unit", cost: 2, power: 2, health: 3,
    race: "Besta", keywords: [], description: "Invocar: cure 1 do seu Nexus.", rarity: "Common", emoji: "🦊",
    trigger: { when: "onSummon", effect: { kind: "healNexus", amount: 1, target: "none" } },
  },
  forest_thorn_trap: {
    defId: "forest_thorn_trap", name: "Armadilha de Espinhos", region: "Florestia", type: "Enchantment", cost: 3, maxHealth: 4,
    description: "Quando outro permanente aliado entrar, cause 1 ao Nexus inimigo.", rarity: "Rare", emoji: "🌿",
    trigger: { when: "onPermanentSummon", effect: { kind: "damageNexus", amount: 1, target: "none" } },
  },
  forest_pack_tactician: {
    defId: "forest_pack_tactician", name: "Tático da Matilha", region: "Florestia", type: "Unit", cost: 4, power: 3, health: 4,
    race: "Besta", keywords: ["Challenger"], description: "Invocar: dê +1/+1 às Bestas aliadas.", rarity: "Epic", emoji: "🐺",
    trigger: { when: "onSummon", effect: { kind: "buffRace", amount: 0, buffPower: 1, buffHealth: 1, race: "Besta", target: "none" } },
  },
  forest_primal_recall: {
    defId: "forest_primal_recall", name: "Chamado Primal", region: "Florestia", type: "Spell", cost: 4,
    description: "Devolva uma unidade inimiga para a mão.", rarity: "Epic", emoji: "🌀", speed: "Fast",
    spell: { kind: "recall", amount: 1, target: "enemyUnit" },
  },
  forest_dawn_alpha: {
    defId: "forest_dawn_alpha", name: "Alfa da Alvorada", region: "Florestia", type: "Unit", cost: 5, power: 4, health: 5,
    race: "Besta", keywords: ["Challenger"], description: "Besta. Desafiador. Abre caminho para toda a matilha.", rarity: "Epic", emoji: "🦁",
  },
  forest_pack_shelter: {
    defId: "forest_pack_shelter", name: "Abrigo da Matilha", region: "Florestia", type: "Spell", cost: 2,
    description: "Conceda Barreira a uma unidade aliada.", rarity: "Common", emoji: "🍃", speed: "Burst",
    spell: { kind: "grantBarrier", amount: 0, target: "allyUnit" },
  },
  convergence_thunderwolf: {
    defId: "convergence_thunderwolf", name: "Matriarca do Uivo do Trovão", region: "Florestia", regions: ["Florestia", "Tempestade"], regionalPerk: "assault",
    type: "Unit", cost: 5, power: 4, health: 5, race: "Besta", keywords: ["Haste", "Reach"], description: "Seu uivo chega antes do relâmpago.", rarity: "Legend", emoji: "🐺", strategicRole: "finisher", doctrineAffinities: ["convergence_dual"],
  },
  nexus_howler: {
    defId: "nexus_howler",
    name: "Uivador do Nexus",
    region: "Florestia",
    type: "Unit",
    cost: 2,
    power: 2,
    health: 2,
    race: "Besta",
    keywords: [],
    description: "Besta. Invocar: cura 1 do seu Nexus.",
    rarity: "Common",
    emoji: "🐕",
    trigger: { when: "onSummon", effect: { kind: "healNexus", amount: 1, target: "none" } },
  },
};
