import type { CardDef } from "../../types";

export const IRONWOOD_CARDS: Record<string, CardDef> = {
  wood_cub: {
    defId: "wood_cub",
    name: "Thornback Cub",
    region: "Ironwood",
    type: "Unit",
    cost: 2,
    power: 2,
    health: 3,
    race: "Beast",
    keywords: [],
    description: "Beast. A sturdy woodland beast.",
    rarity: "Common",
    emoji: "🐻",
  },
  wood_caller: {
    defId: "wood_caller",
    name: "Grove Caller",
    region: "Ironwood",
    type: "Unit",
    cost: 3,
    power: 2,
    health: 3,
    keywords: [],
    description: "Play: summon a 1/1 Sapling.",
    rarity: "Rare",
    emoji: "🪵",
    trigger: {
      when: "onSummon",
      effect: { kind: "summonToken", amount: 1, target: "none", tokenDefId: "wood_sapling" },
    },
  },
  wood_sapling: {
    defId: "wood_sapling",
    name: "Sapling",
    region: "Ironwood",
    type: "Unit",
    cost: 0,
    power: 1,
    health: 1,
    keywords: [],
    description: "A newborn shoot of the grove.",
    rarity: "Common",
    collectible: false,
    emoji: "🌱",
  },
  wood_stag: {
    defId: "wood_stag",
    name: "Elder Stag",
    region: "Ironwood",
    type: "Unit",
    cost: 4,
    power: 3,
    health: 4,
    race: "Beast",
    keywords: ["Regeneration"],
    description: "Beast. Regeneration: heals to full at the end of each round.",
    rarity: "Rare",
    emoji: "🦌",
  },
  wood_ent: {
    defId: "wood_ent",
    name: "Ancient Rootcolossus",
    region: "Ironwood",
    type: "Unit",
    cost: 6,
    power: 5,
    health: 6,
    race: "Elemental",
    keywords: ["Overwhelm", "Tough"],
    description: "Elemental. Overwhelm & Tough. The forest given form.",
    rarity: "Epic",
    emoji: "🌳",
  },
  wood_champion: {
    defId: "wood_champion",
    name: "Bramblehart, Grovekeeper",
    region: "Ironwood",
    type: "Unit",
    cost: 5,
    power: 4,
    health: 5,
    race: "Spirit",
    keywords: ["Regeneration", "Overwhelm"],
    description: "Champion (Spirit) — Regeneration & Overwhelm. Level Up: I've summoned 5 allies.",
    rarity: "Legend",
    isLegend: true,
    isChampion: true,
    art: "/images/champs/bramblehart.jpg",
    emoji: "🌲",
    levelUp: {
      type: "alliesSummoned",
      amount: 5,
      toDefId: "wood_champion_2",
      hint: "Summon 5 allies",
    },
  },
  wood_champion_2: {
    defId: "wood_champion_2",
    name: "Bramblehart, Worldroot",
    region: "Ironwood",
    type: "Unit",
    cost: 5,
    power: 5,
    health: 6,
    keywords: ["Regeneration", "Overwhelm"],
    description: "Leveled — Regeneration & Overwhelm. Round Start: give all allies +1/+1.",
    rarity: "Legend",
    isLegend: true,
    isChampion: true,
    collectible: false,
    art: "/images/champs/bramblehart.jpg",
    emoji: "🌲",
    trigger: {
      when: "onRoundStart",
      effect: { kind: "buffAllies", amount: 0, buffPower: 1, buffHealth: 1, target: "none" },
    },
  },
  wood_growth: {
    defId: "wood_growth",
    name: "Wild Growth",
    region: "Ironwood",
    type: "Spell",
    cost: 3,
    description: "Give a unit +1/+2.",
    rarity: "Common",
    emoji: "🌿",
    spell: { kind: "buffUnit", amount: 0, buffPower: 1, buffHealth: 2, target: "allyUnit" },
  },
  wood_mend: {
    defId: "wood_mend",
    name: "Nature's Mending",
    region: "Ironwood",
    type: "Spell",
    cost: 1,
    description: "Restore 3 health to a unit.",
    rarity: "Common",
    emoji: "🍃",
    spell: { kind: "healUnit", amount: 3, target: "allyUnit" },
  },
  wood_ward: {
    defId: "wood_ward",
    name: "Barkskin",
    region: "Ironwood",
    type: "Spell",
    cost: 2,
    description: "Fast — give a unit Tough.",
    rarity: "Common",
    speed: "Fast",
    emoji: "🌿",
    spell: { kind: "grantKeyword", amount: 0, keyword: "Tough", target: "allyUnit" },
  },
  wood_packalpha: {
    defId: "wood_packalpha",
    name: "Grove Alpha",
    region: "Ironwood",
    type: "Unit",
    cost: 3,
    power: 2,
    health: 3,
    race: "Beast",
    keywords: [],
    description: "Beast. Rally: all Beasts get +1/+0.",
    rarity: "Common",
    emoji: "🐺",
    trigger: {
      when: "onSummon",
      effect: { kind: "buffAllies", amount: 0, buffPower: 1, buffHealth: 0, target: "none", race: "Beast" },
    },
  },
  wood_pact: {
    defId: "wood_pact",
    name: "Ancient Pact",
    region: "Ironwood",
    type: "Enchantment",
    cost: 4,
    maxHealth: 4,
    description: "Round Start: all Beasts get +0/+1 and Regeneration.",
    rarity: "Epic",
    emoji: "📜",
    trigger: {
      when: "onRoundStart",
      effect: {
        kind: "buffAllies",
        amount: 0,
        buffPower: 0,
        buffHealth: 1,
        target: "none",
        race: "Beast",
        also: {
          kind: "grantKeyword",
          amount: 0,
          keyword: "Regeneration",
          target: "none",
          race: "Beast",
        },
      },
    },
  },
  wood_claw: {
    defId: "wood_claw",
    name: "Thornfang Claw",
    region: "Ironwood",
    type: "Equipment",
    cost: 2,
    equipment: { buffPower: 1, buffHealth: 1, keywords: [] },
    description: "Equip: +1/+1.",
    rarity: "Common",
    emoji: "🦴",
  },
  wood_void_pack: {
    defId: "wood_void_pack",
    name: "Twilight Packlord",
    region: "Ironwood",
    type: "Unit",
    cost: 4,
    power: 3,
    health: 4,
    race: "Beast",
    secondaryRaces: ["Voidling"],
    keywords: ["Fearsome"],
    description: "Beast/Voidling. Play: all Beasts and Voidlings get +1/+0 and Fearsome.",
    rarity: "Epic",
    emoji: "🐺",
    trigger: {
      when: "onSummon",
      effect: {
        kind: "buffAllies",
        amount: 0,
        buffPower: 1,
        buffHealth: 0,
        target: "none",
        races: ["Beast", "Voidling"],
        also: {
          kind: "grantKeyword",
          amount: 0,
          keyword: "Fearsome",
          target: "none",
          races: ["Beast", "Voidling"],
        },
      },
    },
  },
  wood_heartwood: {
    defId: "wood_heartwood",
    name: "Heartwood Staff",
    region: "Ironwood",
    type: "Equipment",
    cost: 3,
    equipment: { buffPower: 1, buffHealth: 2, keywords: ["Regeneration"] },
    description: "Equip: +1/+2 and Regeneration. Ally death: give this unit +1/+1.",
    rarity: "Rare",
    emoji: "🪵",
    trigger: {
      when: "onAllyDeath",
      effect: { kind: "buffSelf", amount: 0, buffPower: 1, buffHealth: 1, target: "self" },
    },
  },
  wood_wither: {
    defId: "wood_wither",
    name: "Withering Vines",
    region: "Ironwood",
    type: "Spell",
    cost: 1,
    description: "Deal 3 damage to an enemy Enchantment or Artifact.",
    rarity: "Common",
    emoji: "🪴",
    spell: { kind: "damagePermanent", amount: 3, target: "enemyPermanent" },
  },
  wood_martyr: {
    defId: "wood_martyr",
    name: "Seedbearer Martyr",
    region: "Ironwood",
    type: "Unit",
    cost: 2,
    power: 1,
    health: 2,
    race: "Spirit",
    keywords: ["LastBreath"],
    description: "Spirit. Last Breath: summon two 1/1 Saplings.",
    rarity: "Common",
    emoji: "🌱",
    trigger: {
      when: "onDeath",
      effect: {
        kind: "summonToken",
        amount: 1,
        target: "none",
        tokenDefId: "wood_sapling",
        also: { kind: "summonToken", amount: 1, target: "none", tokenDefId: "wood_sapling" },
      },
    },
  },
  wood_recall: {
    defId: "wood_recall",
    name: "Nature's Grasp",
    region: "Ironwood",
    type: "Spell",
    cost: 5,
    description: "Recall an enemy unit to its owner's hand.",
    rarity: "Common",
    emoji: "🌿",
    spell: { kind: "recall", amount: 0, target: "enemyUnit" },
  },
  wood_webweaver: {
    defId: "wood_webweaver",
    name: "Silkweb Weaver",
    region: "Ironwood",
    type: "Unit",
    cost: 3,
    power: 2,
    health: 4,
    race: "Beast",
    keywords: ["Reach"],
    description: "Beast. Reach — can block Elusive units.",
    rarity: "Common",
    emoji: "🕸️",
  },
  wood_root_golem_token: {
    defId: "wood_root_golem_token",
    name: "Golem de Raiz",
    region: "Ironwood",
    type: "Unit",
    cost: 0,
    power: 4,
    health: 6,
    race: "Elemental",
    keywords: ["Tough"],
    description: "Um Elemental de pedra e raiz.",
    rarity: "Common",
    collectible: false,
    emoji: "🗿",
  },
  sent_terrus: {
    defId: "sent_terrus",
    name: "Terrus, Coração de Ferro",
    region: "Ironwood",
    type: "Sentinela",
    cost: 5,
    description: "Sentinela — ancora a linha de frente e recompensa a resistência.",
    rarity: "Legend",
    isLegend: true,
    emoji: "🌲",
    sentinela: {
      startingLoyalty: 6,
      abilities: [
        { cost: 1, description: "+1: dá +0/+2 a todas as criaturas aliadas (aura de trincheira)", effect: { kind: "buffAllies", amount: 0, buffPower: 0, buffHealth: 2, target: "none" } },
        { cost: -3, description: "-3: dá Resistente permanentemente a todas as criaturas aliadas no campo", effect: { kind: "grantKeyword", amount: 0, target: "none", keyword: "Tough" } },
        { cost: -8, description: "-8: invoca um Golem de Raiz 4/6 com Resistente", effect: { kind: "summonToken", amount: 1, target: "none", tokenDefId: "wood_root_golem_token" } },
      ],
    },
  },
  wood_elderbear: {
    defId: "wood_elderbear",
    name: "Urso Ancião",
    region: "Ironwood",
    type: "Unit",
    cost: 4,
    power: 4,
    health: 6,
    race: "Beast",
    keywords: ["Tough"],
    description: "Fera. Resistente.",
    rarity: "Common",
    emoji: "🐻",
  },
  wood_treant: {
    defId: "wood_treant",
    name: "Treant Vigilante",
    region: "Ironwood",
    type: "Unit",
    cost: 5,
    power: 3,
    health: 7,
    race: "Elemental",
    keywords: ["Reach", "Regeneration"],
    description: "Elemental. Alcance & Regeneração.",
    rarity: "Rare",
    emoji: "🌳",
  },
  wood_saprotector: {
    defId: "wood_saprotector",
    name: "Protetor Seivoso",
    region: "Ironwood",
    type: "Unit",
    cost: 3,
    power: 2,
    health: 4,
    race: "Elemental",
    keywords: [],
    description: "Elemental. Invocar: cura 2 de uma criatura aliada.",
    rarity: "Common",
    emoji: "🌿",
    trigger: { when: "onSummon", effect: { kind: "healUnit", amount: 2, target: "allyUnit" } },
  },
  wood_feralwolf: {
    defId: "wood_feralwolf",
    name: "Lobo Selvagem",
    region: "Ironwood",
    type: "Unit",
    cost: 2,
    power: 3,
    health: 2,
    race: "Beast",
    keywords: ["QuickAttack"],
    description: "Fera. Ataque Rápido.",
    rarity: "Common",
    emoji: "🐺",
  },
  wood_ancientprowler: {
    defId: "wood_ancientprowler",
    name: "Espreitador Ancestral",
    region: "Ironwood",
    type: "Unit",
    cost: 6,
    power: 6,
    health: 6,
    race: "Beast",
    keywords: ["Overwhelm", "Regeneration"],
    description: "Fera. Atropelar & Regeneração.",
    rarity: "Epic",
    emoji: "🦁",
  },
  wood_root_prison: {
    defId: "wood_root_prison", name: "Prisão de Raízes", region: "Ironwood", type: "Spell", cost: 3,
    description: "Atordoe uma unidade inimiga.", rarity: "Common", emoji: "🌱", speed: "Fast",
    spell: { kind: "stun", amount: 1, target: "enemyUnit" },
  },
  wood_bark_rupture: {
    defId: "wood_bark_rupture", name: "Ruptura da Casca", region: "Ironwood", type: "Spell", cost: 3,
    description: "Cause 4 de dano a um permanente inimigo.", rarity: "Rare", emoji: "🪵", speed: "Fast",
    spell: { kind: "damagePermanent", amount: 4, target: "enemyPermanent" },
  },
  wood_canopy_bastion: {
    defId: "wood_canopy_bastion", name: "Bastião da Copa", region: "Ironwood", type: "Unit", cost: 4, power: 3, health: 5,
    race: "Beast", keywords: ["Reach"], description: "Besta. Alcance. Protege o bosque enquanto as raízes avançam.", rarity: "Rare", emoji: "🌳",
  },
  wood_seed_of_return: {
    defId: "wood_seed_of_return", name: "Semente do Retorno", region: "Ironwood", type: "Spell", cost: 3,
    description: "Cure 4 de uma unidade aliada e compre 1 carta.", rarity: "Rare", emoji: "🌱", speed: "Burst",
    spell: { kind: "healUnit", amount: 4, target: "allyUnit", also: { kind: "draw", amount: 1, target: "none" } },
  },
  convergence_duskbloom_warden: {
    defId: "convergence_duskbloom_warden", name: "Vigia do Jardim do Crepúsculo", region: "Ironwood", regions: ["Ironwood", "Voidborn"], regionalPerk: "bulwark",
    type: "Unit", cost: 4, power: 3, health: 5, race: "Spirit", keywords: ["Lifesteal"], description: "Floresce onde a luz termina.", rarity: "Rare", emoji: "🥀", strategicRole: "defense", doctrineAffinities: ["convergence_dual"],
  },
  convergence_packkeeper: {
    defId: "convergence_packkeeper", name: "Guardião do Pacto Ancestral", region: "Ironwood", regions: ["Ironwood", "Florestia"], regionalPerk: "assault",
    type: "Unit", cost: 4, power: 3, health: 4, race: "Besta", keywords: ["Reach"], description: "Invocar: dê +1/+1 às Bestas aliadas.", rarity: "Epic", emoji: "🦌",
    trigger: { when: "onSummon", effect: { kind: "buffRace", amount: 0, buffPower: 1, buffHealth: 1, race: "Besta", target: "none" } }, strategicRole: "engine", doctrineAffinities: ["convergence_dual"],
  },
  convergence_canopy_lightning: {
    defId: "convergence_canopy_lightning", name: "Relâmpago da Copa", region: "Ironwood", regions: ["Ironwood", "Tempestade"], regionalPerk: "convergence",
    type: "Spell", cost: 3, description: "Cause 3 a uma unidade inimiga e compre 1.", rarity: "Epic", emoji: "🌩️", speed: "Fast",
    spell: { kind: "damageUnit", amount: 3, target: "enemyUnit", also: { kind: "draw", amount: 1, target: "none" } }, strategicRole: "removal", doctrineAffinities: ["convergence_dual"],
  },
  convergence_dreadroot_alpha: {
    defId: "convergence_dreadroot_alpha", name: "Alfa do Círculo da Raiz Sombria", region: "Ironwood", regions: ["Ironwood", "Voidborn", "Florestia"], regionalPerk: "assault",
    type: "Unit", cost: 6, power: 5, health: 6, race: "Besta", keywords: ["Lifesteal", "Challenger"], description: "Toda presa alimenta o bosque oculto.", rarity: "Legend", emoji: "🌑", strategicRole: "finisher", doctrineAffinities: ["convergence_triad"],
  },
};
