import type { CardDef } from "../../types";

export const TEMPESTADE_CARDS: Record<string, CardDef> = {
  storm_dashbolt: {
    defId: "storm_dashbolt",
    name: "Raio-Veloz",
    region: "Tempestade",
    type: "Unit",
    cost: 1,
    power: 2,
    health: 1,
    race: "Tempesteiro",
    keywords: ["Haste"],
    description: "Tempesteiro. Ímpeto.",
    rarity: "Common",
    emoji: "⚡",
  },
  storm_strikecaller: {
    defId: "storm_strikecaller",
    name: "Chamador do Trovão",
    region: "Tempestade",
    type: "Unit",
    cost: 3,
    power: 2,
    health: 2,
    race: "Tempesteiro",
    keywords: ["DoubleStrike"],
    description: "Tempesteiro. Ataque Duplo.",
    rarity: "Rare",
    emoji: "🌩️",
  },
  storm_cyclone: {
    defId: "storm_cyclone",
    name: "Ciclone Encantado",
    region: "Tempestade",
    type: "Unit",
    cost: 4,
    power: 4,
    health: 3,
    race: "Tempesteiro",
    keywords: ["Haste", "Elusive"],
    description: "Tempesteiro. Ímpeto & Evasivo.",
    rarity: "Epic",
    emoji: "🌪️",
  },
  storm_seraph: {
    defId: "storm_seraph",
    name: "Serafim Guardião",
    region: "Tempestade",
    type: "Unit",
    cost: 3,
    power: 2,
    health: 4,
    race: "Anjo",
    keywords: ["Flying", "Barrier"],
    description: "Anjo. Voo & Barreira.",
    rarity: "Rare",
    emoji: "🕊️",
  },
  storm_herald: {
    defId: "storm_herald",
    name: "Arauto da Tempestade",
    region: "Tempestade",
    type: "Unit",
    cost: 4,
    power: 3,
    health: 4,
    race: "Anjo",
    keywords: ["Flying", "Lifesteal"],
    description: "Anjo. Voo & Vampírico.",
    rarity: "Rare",
    emoji: "👼",
  },
  storm_warchief: {
    defId: "storm_warchief",
    name: "Grão-Mestre Relâmpago",
    region: "Tempestade",
    type: "Unit",
    cost: 4,
    power: 4,
    health: 4,
    race: "Tempesteiro",
    keywords: ["Haste", "DoubleStrike"],
    description: "Tempesteiro. Ímpeto & Ataque Duplo. Invocar: Tempesteiros aliados ganham Ímpeto.",
    rarity: "Epic",
    emoji: "⚔️",
    trigger: { when: "onSummon", effect: { kind: "grantKeyword", amount: 0, target: "none", keyword: "Haste", race: "Tempesteiro" } },
  },
  storm_champion: {
    defId: "storm_champion",
    name: "Zael, Senhor dos Raios",
    region: "Tempestade",
    type: "Unit",
    cost: 6,
    power: 5,
    health: 5,
    race: "Anjo",
    keywords: ["Flying", "Lifesteal"],
    description: "Campeão (Anjo) — Voo & Vampírico. Evoluir: acertar o Nexus inimigo 2 vezes.",
    rarity: "Legend",
    isLegend: true,
    isChampion: true,
    emoji: "🌟",
    levelUp: { type: "nexusStrikes", amount: 2, toDefId: "storm_champion_2", hint: "Strike the enemy Nexus twice" },
  },
  storm_champion_2: {
    defId: "storm_champion_2",
    name: "Zael, Asas da Tempestade",
    region: "Tempestade",
    type: "Unit",
    cost: 6,
    power: 6,
    health: 7,
    race: "Anjo",
    keywords: ["Flying", "Lifesteal", "DoubleStrike"],
    description: "Evoluído — Voo, Vampírico & Ataque Duplo. Ao acertar o Nexus: todos os Anjos recebem +1/+1.",
    rarity: "Legend",
    isLegend: true,
    isChampion: true,
    collectible: false,
    emoji: "🌟",
    trigger: { when: "onNexusStrike", effect: { kind: "buffAllies", amount: 0, buffPower: 1, buffHealth: 1, target: "none", race: "Anjo" } },
  },
  storm_lightning: {
    defId: "storm_lightning",
    name: "Raio",
    region: "Tempestade",
    type: "Spell",
    cost: 2,
    description: "Causa 3 de dano a uma unidade.",
    rarity: "Common",
    emoji: "⚡",
    spell: { kind: "damageUnit", amount: 3, target: "anyUnit" },
  },
  storm_gale: {
    defId: "storm_gale",
    name: "Vendaval",
    region: "Tempestade",
    type: "Spell",
    cost: 3,
    description: "Retorna uma criatura inimiga à mão do oponente.",
    rarity: "Rare",
    emoji: "💨",
    spell: { kind: "recall", amount: 0, target: "enemyUnit" },
  },
  storm_thunder: {
    defId: "storm_thunder",
    name: "Trovão",
    region: "Tempestade",
    type: "Spell",
    cost: 4,
    description: "Causa 2 de dano a todas as criaturas inimigas.",
    rarity: "Rare",
    emoji: "🌩️",
    spell: { kind: "aoeEnemy", amount: 2, target: "none" },
  },
  storm_burst: {
    defId: "storm_burst",
    name: "Rajada Relâmpago",
    region: "Tempestade",
    type: "Spell",
    cost: 1,
    description: "Burst — Causa 1 de dano a uma unidade.",
    rarity: "Common",
    speed: "Burst",
    emoji: "✨",
    spell: { kind: "damageUnit", amount: 1, target: "anyUnit" },
  },
  storm_anthem: {
    defId: "storm_anthem",
    name: "Hino da Tempestade",
    region: "Tempestade",
    type: "Enchantment",
    cost: 4,
    maxHealth: 4,
    description: "Início de Rodada: todos os Anjos e Tempesteiros aliados recebem +1/+0.",
    rarity: "Rare",
    emoji: "🎵",
    trigger: { when: "onRoundStart", effect: { kind: "buffAllies", amount: 0, buffPower: 1, buffHealth: 0, target: "none", races: ["Anjo", "Tempesteiro"] } },
  },
  sent_aurion: {
    defId: "sent_aurion",
    name: "Aurion, Tempestade Viva",
    region: "Tempestade",
    type: "Sentinela",
    cost: 5,
    description: "Sentinela — invoca a fúria dos céus.",
    rarity: "Legend",
    isLegend: true,
    emoji: "⚡",
    sentinela: {
      startingLoyalty: 4,
      abilities: [
        { cost: 1, description: "+1: dá Ímpeto a uma criatura aliada", effect: { kind: "grantKeyword", amount: 0, keyword: "Haste", target: "allyUnit" } },
        { cost: -2, description: "-2: causa 2 de dano a todas as criaturas inimigas", effect: { kind: "aoeEnemy", amount: 2, target: "none" } },
        { cost: -7, description: "-7: dá +3/+3 a todas as criaturas aliadas", effect: { kind: "buffAllies", amount: 0, buffPower: 3, buffHealth: 3, target: "none" } },
      ],
    },
  },
  storm_windrider: {
    defId: "storm_windrider",
    name: "Cavalgante do Vento",
    region: "Tempestade",
    type: "Unit",
    cost: 3,
    power: 2,
    health: 3,
    race: "Tempesteiro",
    keywords: ["Elusive"],
    description: "Tempesteiro. Evasivo.",
    rarity: "Common",
    emoji: "🌬️",
  },
  storm_skyarchon: {
    defId: "storm_skyarchon",
    name: "Arconte Celeste",
    region: "Tempestade",
    type: "Unit",
    cost: 5,
    power: 5,
    health: 4,
    race: "Anjo",
    keywords: ["Flying", "Lifesteal"],
    description: "Anjo. Voo & Vampírico.",
    rarity: "Epic",
    emoji: "😇",
  },
  storm_thunderbird: {
    defId: "storm_thunderbird",
    name: "Pássaro-Trovão",
    region: "Tempestade",
    type: "Unit",
    cost: 4,
    power: 3,
    health: 3,
    race: "Tempesteiro",
    keywords: ["Flying"],
    description: "Tempesteiro. Voo. Ao acertar o Nexus: causa 1 a todas as criaturas inimigas.",
    rarity: "Rare",
    emoji: "🦅",
    trigger: { when: "onNexusStrike", effect: { kind: "aoeEnemy", amount: 1, target: "none" } },
  },
  storm_guardian: {
    defId: "storm_guardian",
    name: "Guardião Celestial",
    region: "Tempestade",
    type: "Unit",
    cost: 4,
    power: 2,
    health: 5,
    race: "Anjo",
    keywords: ["Barrier", "Flying"],
    description: "Anjo. Barreira & Voo.",
    rarity: "Common",
    emoji: "🕊️",
  },
  storm_lightningstriker: {
    defId: "storm_lightningstriker",
    name: "Golpeador-Relâmpago",
    region: "Tempestade",
    type: "Unit",
    cost: 2,
    power: 3,
    health: 1,
    race: "Tempesteiro",
    keywords: ["Haste"],
    description: "Tempesteiro. Ímpeto.",
    rarity: "Common",
    emoji: "⚡",
  },
  nexus_golem: {
    defId: "nexus_golem",
    name: "Golem do Nexus",
    region: "Tempestade",
    type: "Unit",
    cost: 3,
    power: 3,
    health: 3,
    race: "Elemental",
    keywords: ["Tough"],
    description: "Elemental. Resistente.",
    rarity: "Common",
    emoji: "🗿",
  },
  storm_chain_bolt: {
    defId: "storm_chain_bolt", name: "Raio Encadeado", region: "Tempestade", type: "Spell", cost: 2,
    description: "Cause 2 a uma unidade e 1 ao Nexus inimigo.", rarity: "Rare", emoji: "⚡", speed: "Fast",
    spell: { kind: "damageUnit", amount: 2, target: "enemyUnit", also: { kind: "damageNexus", amount: 1, target: "none" } },
  },
  storm_eye: {
    defId: "storm_eye", name: "Olho da Tempestade", region: "Tempestade", type: "Spell", cost: 3,
    description: "Congele uma unidade inimiga e compre 1.", rarity: "Epic", emoji: "🌪️", speed: "Fast",
    spell: { kind: "frostbite", amount: 1, target: "enemyUnit", also: { kind: "draw", amount: 1, target: "none" } },
  },
  storm_sky_sentinel: {
    defId: "storm_sky_sentinel", name: "Sentinela dos Céus", region: "Tempestade", type: "Unit", cost: 3, power: 2, health: 4,
    race: "Tempesteiro", keywords: ["Flying", "Reach"], description: "Voo e Alcance.", rarity: "Rare", emoji: "🦅",
  },
  storm_thunder_angel: {
    defId: "storm_thunder_angel", name: "Anjo do Trovão", region: "Tempestade", type: "Unit", cost: 5, power: 4, health: 5,
    race: "Anjo", keywords: ["Flying", "Lifesteal"], description: "Voo e Vampírico.", rarity: "Epic", emoji: "👼",
  },
  storm_static_adept: {
    defId: "storm_static_adept", name: "Adepto da Estática", region: "Tempestade", type: "Unit", cost: 2, power: 2, health: 3,
    race: "Tempesteiro", keywords: ["Reach"], description: "Tempesteiro. Alcance. Canaliza o céu sem abandonar a defesa.", rarity: "Common", emoji: "⚡",
  },
  storm_tempered_winds: {
    defId: "storm_tempered_winds", name: "Ventos Temperados", region: "Tempestade", type: "Spell", cost: 3,
    description: "Dê +1/+2 a uma unidade aliada.", rarity: "Rare", emoji: "🌬️", speed: "Burst",
    spell: { kind: "buffUnit", amount: 0, buffPower: 1, buffHealth: 2, target: "allyUnit" },
  },
  nexus_stormrider: {
    defId: "nexus_stormrider",
    name: "Cavaleiro Tempestuoso",
    region: "Tempestade",
    type: "Unit",
    cost: 5,
    power: 4,
    health: 5,
    race: "Tempesteiro",
    keywords: ["Flying", "Haste"],
    description: "Tempesteiro. Voo & Ímpeto.",
    rarity: "Epic",
    emoji: "⚔️",
  },};
