import type { CardDef } from "../../types";

export const TIDECALL_CARDS: Record<string, CardDef> = {
  tide_sprite: {
    defId: "tide_sprite",
    name: "Reef Sprite",
    region: "Tidecall",
    type: "Unit",
    cost: 1,
    power: 1,
    health: 2,
    race: "Sprite",
    keywords: ["Elusive"],
    description: "Sprite. Elusive: can only be blocked by Elusive units.",
    rarity: "Common",
    emoji: "🌀",
  },
  tide_oracle: {
    defId: "tide_oracle",
    name: "Tide Oracle",
    region: "Tidecall",
    type: "Unit",
    cost: 2,
    power: 1,
    health: 3,
    keywords: [],
    description: "Play: draw 1.",
    rarity: "Rare",
    emoji: "🧿",
    trigger: { when: "onSummon", effect: { kind: "draw", amount: 1, target: "none" } },
  },
  tide_guard: {
    defId: "tide_guard",
    name: "Tidal Warden",
    region: "Tidecall",
    type: "Unit",
    cost: 3,
    power: 2,
    health: 5,
    race: "Elemental",
    keywords: ["Tough", "Reach"],
    description: "Elemental. Tough and Reach: resists damage and guards the skies.",
    rarity: "Common",
    emoji: "🛡️",
  },
  tide_bladedancer: {
    defId: "tide_bladedancer",
    name: "Riptide Dancer",
    region: "Tidecall",
    type: "Unit",
    cost: 4,
    power: 3,
    health: 3,
    keywords: ["DoubleStrike"],
    description: "Double Strike: strikes twice in combat.",
    rarity: "Epic",
    emoji: "🗡️",
  },
  tide_mystic: {
    defId: "tide_mystic",
    name: "Deepcurrent Mystic",
    region: "Tidecall",
    type: "Unit",
    cost: 4,
    power: 3,
    health: 4,
    race: "Spirit",
    keywords: ["Barrier"],
    description: "Spirit. Barrier: negates the next damage it would take.",
    rarity: "Rare",
    emoji: "🔮",
  },
  tide_champion: {
    defId: "tide_champion",
    name: "Nerida, Tide Empress",
    region: "Tidecall",
    type: "Unit",
    cost: 5,
    power: 4,
    health: 6,
    race: "Spirit",
    keywords: ["Elusive", "Barrier"],
    description: "Champion (Spirit) — Elusive & Barrier. Level Up: I've seen you cast 4 spells.",
    rarity: "Legend",
    isLegend: true,
    isChampion: true,
    art: "/images/champs/nerida.jpg",
    emoji: "🌊",
    levelUp: {
      type: "spellsCast",
      amount: 4,
      toDefId: "tide_champion_2",
      hint: "Cast 4 spells",
    },
  },
  tide_champion_2: {
    defId: "tide_champion_2",
    name: "Nerida, Eternal Tide",
    region: "Tidecall",
    type: "Unit",
    cost: 6,
    power: 5,
    health: 7,
    keywords: ["Elusive", "Barrier"],
    description: "Leveled — Elusive & Barrier. Round Start: refill Barrier and draw 1.",
    rarity: "Legend",
    isLegend: true,
    isChampion: true,
    collectible: false,
    art: "/images/champs/nerida.jpg",
    emoji: "🌊",
    trigger: {
      when: "onRoundStart",
      effect: {
        kind: "grantBarrier",
        amount: 0,
        target: "self",
        also: { kind: "draw", amount: 1, target: "none" },
      },
    },
  },
  tide_freeze: {
    defId: "tide_freeze",
    name: "Riptide",
    region: "Tidecall",
    type: "Spell",
    cost: 2,
    description: "Deal 2 damage to a unit and draw a card.",
    rarity: "Common",
    emoji: "💧",
    spell: {
      kind: "damageUnit",
      amount: 2,
      target: "anyUnit",
      also: { kind: "draw", amount: 1, target: "none" },
    },
  },
  tide_draw: {
    defId: "tide_draw",
    name: "Foresight",
    region: "Tidecall",
    type: "Spell",
    cost: 3,
    description: "Draw 2 cards.",
    rarity: "Common",
    emoji: "📜",
    spell: { kind: "draw", amount: 2, target: "none" },
  },
  tide_heal: {
    defId: "tide_heal",
    name: "Soothing Tide",
    region: "Tidecall",
    type: "Spell",
    cost: 2,
    description: "Restore 4 health to your Nexus.",
    rarity: "Common",
    emoji: "✨",
    spell: { kind: "healNexus", amount: 4, target: "none" },
  },
  tide_shield: {
    defId: "tide_shield",
    name: "Ripcurrent Ward",
    region: "Tidecall",
    type: "Spell",
    cost: 2,
    description: "Burst — give a unit Barrier.",
    rarity: "Rare",
    speed: "Burst",
    emoji: "🌊",
    spell: { kind: "grantBarrier", amount: 0, target: "allyUnit" },
  },
  tide_reefspirit: {
    defId: "tide_reefspirit",
    name: "Reef Spirit",
    region: "Tidecall",
    type: "Unit",
    cost: 1,
    power: 1,
    health: 2,
    race: "Sprite",
    keywords: ["Elusive"],
    description: "Sprite. Elusive.",
    rarity: "Common",
    emoji: "🌊",
  },
  tide_caller: {
    defId: "tide_caller",
    name: "Coral Caller",
    region: "Tidecall",
    type: "Unit",
    cost: 3,
    power: 2,
    health: 3,
    race: "Sprite",
    keywords: [],
    description: "Sprite. Play: give all Sprites +0/+2.",
    rarity: "Rare",
    emoji: "🐚",
    trigger: {
      when: "onSummon",
      effect: { kind: "buffAllies", amount: 0, buffPower: 0, buffHealth: 2, target: "none", race: "Sprite" },
    },
  },
  tide_tidecaller: {
    defId: "tide_tidecaller",
    name: "Tidecaller's Anthem",
    region: "Tidecall",
    type: "Enchantment",
    cost: 3,
    maxHealth: 4,
    description: "Round Start: all Sprites get +0/+1.",
    rarity: "Rare",
    emoji: "🎵",
    trigger: {
      when: "onRoundStart",
      effect: { kind: "buffAllies", amount: 0, buffPower: 0, buffHealth: 1, target: "none", race: "Sprite" },
    },
  },
  tide_tome: {
    defId: "tide_tome",
    name: "Tidecaller's Tome",
    region: "Tidecall",
    type: "Artifact",
    cost: 3,
    maxHealth: 3,
    description: "When you summon a Sprite, draw 1.",
    rarity: "Rare",
    emoji: "📘",
    trigger: {
      when: "onPermanentSummon",
      effect: { kind: "draw", amount: 1, target: "none", race: "Sprite" },
    },
  },
  tide_anchor: {
    defId: "tide_anchor",
    name: "Anchor of Tides",
    region: "Tidecall",
    type: "Equipment",
    cost: 2,
    equipment: { buffPower: 0, buffHealth: 3, keywords: ["Barrier"] },
    description: "Equip: +0/+3 and Barrier.",
    rarity: "Common",
    emoji: "⚓",
  },
  tide_wood_chorus: {
    defId: "tide_wood_chorus",
    name: "Grove Chorus",
    region: "Tidecall",
    type: "Unit",
    cost: 3,
    power: 2,
    health: 3,
    race: "Sprite",
    secondaryRaces: ["Spirit"],
    keywords: [],
    description: "Sprite/Spirit. Play: all Sprites and Spirits get +0/+2.",
    rarity: "Rare",
    emoji: "🎵",
    trigger: {
      when: "onSummon",
      effect: {
        kind: "buffAllies",
        amount: 0,
        buffPower: 0,
        buffHealth: 2,
        target: "none",
        races: ["Sprite", "Spirit"],
      },
    },
  },
  tide_mirror: {
    defId: "tide_mirror",
    name: "Mirror Shell",
    region: "Tidecall",
    type: "Equipment",
    cost: 3,
    equipment: { buffPower: 0, buffHealth: 3, keywords: ["Tough", "Barrier"] },
    description: "Equip: +0/+3, Tough and Barrier. Strike: restore 1 to your Nexus.",
    rarity: "Rare",
    emoji: "🪞",
    trigger: { when: "onStrike", effect: { kind: "healNexus", amount: 1, target: "none" } },
  },
  tide_dispel: {
    defId: "tide_dispel",
    name: "Disenchant Tide",
    region: "Tidecall",
    type: "Spell",
    cost: 2,
    description: "Burst — destroy an enemy Enchantment or Artifact.",
    rarity: "Rare",
    speed: "Burst",
    emoji: "🌊",
    spell: { kind: "destroyPermanent", amount: 0, target: "enemyPermanent" },
  },
  tide_confluence: {
    defId: "tide_confluence",
    name: "Confluence",
    region: "Tidecall",
    type: "Spell",
    cost: 2,
    description: "Draw 1 for each unique race among your units (max 3).",
    rarity: "Epic",
    emoji: "🌀",
    spell: { kind: "drawOnSummon", amount: 1, target: "none" },
  },
  tide_frostbite: {
    defId: "tide_frostbite",
    name: "Flash Freeze",
    region: "Tidecall",
    type: "Spell",
    cost: 3,
    description: "Burst — Frostbite an enemy: set its Power to 0 this round.",
    rarity: "Rare",
    speed: "Burst",
    emoji: "❄️",
    spell: { kind: "frostbite", amount: 0, target: "enemyUnit" },
  },
  tide_stun: {
    defId: "tide_stun",
    name: "Riptide Stun",
    region: "Tidecall",
    type: "Spell",
    cost: 2,
    description: "Stun an enemy unit — it cannot attack or block this round.",
    rarity: "Common",
    emoji: "⚡",
    spell: { kind: "stun", amount: 0, target: "enemyUnit" },
  },
  tide_recall: {
    defId: "tide_recall",
    name: "Recall",
    region: "Tidecall",
    type: "Spell",
    cost: 4,
    description: "Return any unit to its owner's hand.",
    rarity: "Rare",
    emoji: "🌀",
    spell: { kind: "recall", amount: 0, target: "anyUnit" },
  },
  tide_glacial: {
    defId: "tide_glacial",
    name: "Glacial Tomb",
    region: "Tidecall",
    type: "Spell",
    cost: 5,
    description: "Frostbite all enemy units this round.",
    rarity: "Epic",
    emoji: "🧊",
    spell: { kind: "frostbite", amount: 0, target: "none" },
  },
  tide_deny: {
    defId: "tide_deny",
    name: "Deny",
    region: "Tidecall",
    type: "Spell",
    cost: 4,
    description: "Burst — Negate an active spell on the stack.",
    rarity: "Epic",
    speed: "Burst",
    emoji: "🛑",
    spell: { kind: "negateSpell", amount: 0, target: "spellOnStack" },
  },
  tide_erosion: {
    defId: "tide_erosion",
    name: "Tidal Erosion",
    region: "Tidecall",
    type: "Spell",
    cost: 3,
    description: "Mill 4 cards from the enemy deck.",
    rarity: "Rare",
    emoji: "🌀",
    spell: { kind: "mill", amount: 4, target: "none" },
  },
  tide_abyssal_current: {
    defId: "tide_abyssal_current",
    name: "Abyssal Current",
    region: "Tidecall",
    type: "Unit",
    cost: 4,
    power: 2,
    health: 5,
    race: "Elemental",
    keywords: ["Tough"],
    description: "Elemental. Resistente. Ao invocar, descarta (mill) 3 cartas do baralho inimigo.",
    rarity: "Epic",
    emoji: "🐙",
    trigger: { when: "onSummon", effect: { kind: "mill", amount: 3, target: "none" } },
  },
  tide_hexspirit: {
    defId: "tide_hexspirit",
    name: "Warded Spirit",
    region: "Tidecall",
    type: "Unit",
    cost: 4,
    power: 3,
    health: 4,
    race: "Spirit",
    keywords: ["Hexproof"],
    description: "Spirit. Hexproof — can't be targeted by enemy spells.",
    rarity: "Rare",
    emoji: "🔮",
  },
  sent_marinna: {
    defId: "sent_marinna",
    name: "Marinna, Mente das Marés",
    region: "Tidecall",
    type: "Sentinela",
    cost: 5,
    description: "Sentinela — controla o fluxo da batalha.",
    rarity: "Legend",
    isLegend: true,
    emoji: "🌊",
    sentinela: {
      startingLoyalty: 5,
      abilities: [
        { cost: 1, description: "+1: compra 1 carta", effect: { kind: "draw", amount: 1, target: "none" } },
        { cost: -2, description: "-2: devolve uma criatura inimiga à mão", effect: { kind: "recall", amount: 0, target: "enemyUnit" } },
        { cost: -8, description: "-8: dá Barreira a todas as criaturas aliadas", effect: { kind: "grantBarrier", amount: 0, target: "none" } },
      ],
    },
  },
  tide_wavecaller: {
    defId: "tide_wavecaller",
    name: "Chamador de Ondas",
    region: "Tidecall",
    type: "Unit",
    cost: 2,
    power: 1,
    health: 3,
    race: "Sprite",
    keywords: [],
    description: "Sprite. Invocar: cura 2 do seu Nexus.",
    rarity: "Common",
    emoji: "🌊",
    trigger: { when: "onSummon", effect: { kind: "healNexus", amount: 2, target: "none" } },
  },
  tide_tidebarrier: {
    defId: "tide_tidebarrier",
    name: "Barreira de Maré",
    region: "Tidecall",
    type: "Unit",
    cost: 3,
    power: 0,
    health: 6,
    race: "Elemental",
    keywords: ["Barrier", "Tough"],
    description: "Elemental. Barreira & Resistente.",
    rarity: "Common",
    emoji: "🛡️",
  },
  tide_frostguard: {
    defId: "tide_frostguard",
    name: "Guarda Gélida",
    region: "Tidecall",
    type: "Unit",
    cost: 4,
    power: 3,
    health: 4,
    race: "Elemental",
    keywords: ["Tough"],
    description: "Elemental. Resistente. Ao bloquear, congela o atacante (poder 0).",
    rarity: "Rare",
    emoji: "🧊",
    trigger: { when: "onBlock", effect: { kind: "frostbite", amount: 0, target: "enemyUnit" } },
  },
  tide_mystic_2: {
    defId: "tide_mystic_2",
    name: "Místico das Profundezas",
    region: "Tidecall",
    type: "Unit",
    cost: 5,
    power: 4,
    health: 5,
    race: "Spirit",
    keywords: ["Regeneration"],
    description: "Espírito. Regeneração.",
    rarity: "Rare",
    emoji: "🔮",
  },
  tide_tideborn: {
    defId: "tide_tideborn",
    name: "Nascido das Marés",
    region: "Tidecall",
    type: "Unit",
    cost: 1,
    power: 1,
    health: 1,
    race: "Sprite",
    keywords: ["Elusive"],
    description: "Sprite. Evasivo.",
    rarity: "Common",
    emoji: "💧",
  },
  nexus_wisp: {
    defId: "nexus_wisp",
    name: "Fogo-Fátuo",
    region: "Tidecall",
    type: "Unit",
    cost: 1,
    power: 0,
    health: 2,
    race: "Spirit",
    keywords: ["Elusive"],
    description: "Espírito. Evasivo.",
    rarity: "Common",
    emoji: "✨",
  },
  tide_cloudpiercer: {
    defId: "tide_cloudpiercer", name: "Quebra-Nuvens Abissal", region: "Tidecall", type: "Unit", cost: 3, power: 3, health: 4,
    race: "Elemental", keywords: ["Reach"], description: "Elemental. Alcance. Uma muralha de maré contra ameaças aéreas.", rarity: "Common", emoji: "🔱",
  },
  tide_memory_tide: {
    defId: "tide_memory_tide", name: "Maré de Memórias", region: "Tidecall", type: "Spell", cost: 3,
    description: "Compre 2 cartas e cure 2 do seu Nexus.", rarity: "Rare", emoji: "📘",
    spell: { kind: "draw", amount: 2, target: "none", also: { kind: "healNexus", amount: 2, target: "none" } },
  },
  convergence_rootwater_sage: {
    defId: "convergence_rootwater_sage", name: "Sábia das Raízes da Maré", region: "Tidecall", regions: ["Tidecall", "Ironwood"], regionalPerk: "bulwark",
    type: "Unit", cost: 3, power: 2, health: 4, race: "Spirit", description: "Invocar: cure 2 do seu Nexus.", rarity: "Rare", emoji: "🪷",
    trigger: { when: "onSummon", effect: { kind: "healNexus", amount: 2, target: "none" } }, strategicRole: "defense", doctrineAffinities: ["convergence_dual"],
  },
  convergence_drowned_eclipse: {
    defId: "convergence_drowned_eclipse", name: "Eclipse Afogado", region: "Tidecall", regions: ["Tidecall", "Voidborn"], regionalPerk: "convergence",
    type: "Spell", cost: 4, description: "Atordoe uma unidade inimiga e compre 1.", rarity: "Rare", emoji: "🌑", speed: "Fast",
    spell: { kind: "stun", amount: 1, target: "enemyUnit", also: { kind: "draw", amount: 1, target: "none" } }, strategicRole: "tempo", doctrineAffinities: ["convergence_dual"],
  },
  convergence_moonriver_guardian: {
    defId: "convergence_moonriver_guardian", name: "Guardião da Matilha Lunar", region: "Tidecall", regions: ["Tidecall", "Florestia"], regionalPerk: "bulwark",
    type: "Unit", cost: 4, power: 3, health: 5, race: "Besta", keywords: ["Barrier"], description: "A lua guia a matilha por águas que nenhum caçador atravessa.", rarity: "Epic", emoji: "🌙", strategicRole: "defense", doctrineAffinities: ["convergence_dual"],
  },
  convergence_monsoon_oracle: {
    defId: "convergence_monsoon_oracle", name: "Oráculo da Monção Celeste", region: "Tidecall", regions: ["Tidecall", "Tempestade"], regionalPerk: "convergence",
    type: "Unit", cost: 4, power: 3, health: 4, race: "Elemental", keywords: ["Flying"], description: "Invocar: compre 1.", rarity: "Epic", emoji: "🌧️",
    trigger: { when: "onSummon", effect: { kind: "draw", amount: 1, target: "none" } }, strategicRole: "engine", doctrineAffinities: ["convergence_dual"],
  },
  convergence_moon_monsoon: {
    defId: "convergence_moon_monsoon", name: "Chamadora da Lua da Grande Monção", region: "Tidecall", regions: ["Tidecall", "Florestia", "Tempestade"], regionalPerk: "bulwark",
    type: "Unit", cost: 6, power: 4, health: 7, race: "Spirit", keywords: ["Regeneration", "Reach"], description: "A matilha ergue a voz e o oceano responde.", rarity: "Legend", emoji: "🌕", strategicRole: "defense", doctrineAffinities: ["convergence_triad"],
  },
  convergence_abyss_memory: {
    defId: "convergence_abyss_memory", name: "Memória do Abismo Vivo", region: "Tidecall", regions: ["Tidecall", "Ironwood", "Voidborn"], regionalPerk: "convergence",
    type: "Spell", cost: 6, description: "Compre 2 e cure 2 do seu Nexus.", rarity: "Legend", emoji: "🌀",
    spell: { kind: "draw", amount: 2, target: "none", also: { kind: "healNexus", amount: 2, target: "none" } }, strategicRole: "utility", doctrineAffinities: ["convergence_triad"],
  },
  convergence_abyss_grove_warden: {
    defId: "convergence_abyss_grove_warden", name: "Guardião do Abismo Vivo", region: "Tidecall", regions: ["Tidecall", "Ironwood", "Voidborn"], regionalPerk: "bulwark",
    type: "Unit", cost: 5, power: 4, health: 6, race: "Spirit", keywords: ["Tough"], description: "Invocar: cure 2 do seu Nexus. A Maestria tríplice reforça sua Vida.", rarity: "Legend", emoji: "🜄",
    trigger: { when: "onSummon", effect: { kind: "healNexus", amount: 2, target: "none" } }, strategicRole: "defense", doctrineAffinities: ["convergence_triad"],
  },
};
