import type { CardDef } from "../../types";

export const VOIDBORN_CARDS: Record<string, CardDef> = {
  void_imp: {
    defId: "void_imp",
    name: "Gloom Imp",
    region: "Voidborn",
    type: "Unit",
    cost: 1,
    power: 1,
    health: 1,
    race: "Voidling",
    keywords: ["Fearsome"],
    description: "Voidling. Fearsome: can only be blocked by units with 3+ power.",
    rarity: "Common",
    emoji: "👿",
  },
  void_hexer: {
    defId: "void_hexer",
    name: "Hexbound Acolyte",
    region: "Voidborn",
    type: "Unit",
    cost: 2,
    power: 2,
    health: 1,
    keywords: [],
    description: "Play: deal 1 to the strongest enemy.",
    rarity: "Common",
    emoji: "🕯️",
    trigger: { when: "onSummon", effect: { kind: "damageUnit", amount: 1, target: "enemyUnit" } },
  },
  void_stalker: {
    defId: "void_stalker",
    name: "Duskwing Stalker",
    region: "Voidborn",
    type: "Unit",
    cost: 3,
    power: 3,
    health: 3,
    race: "Voidling",
    keywords: ["Fearsome", "Lifesteal"],
    description: "Voidling. Fearsome & Lifesteal: heals your Nexus for damage dealt.",
    rarity: "Rare",
    emoji: "🦇",
  },
  void_duelist: {
    defId: "void_duelist",
    name: "Nightblade",
    region: "Voidborn",
    type: "Unit",
    cost: 4,
    power: 4,
    health: 4,
    keywords: ["Challenger", "Fearsome"],
    description: "Challenger & Fearsome. Pick your prey.",
    rarity: "Epic",
    emoji: "🗡️",
  },
  void_reaper: {
    defId: "void_reaper",
    name: "Soul Reaper",
    region: "Voidborn",
    type: "Unit",
    cost: 4,
    power: 5,
    health: 4,
    race: "Voidling",
    keywords: ["Lifesteal", "Overwhelm"],
    description: "Voidling. Lifesteal & Overwhelm. Feeds on the fallen.",
    rarity: "Epic",
    emoji: "💀",
  },
  void_champion: {
    defId: "void_champion",
    name: "Malakar, the Hollow King",
    region: "Voidborn",
    type: "Unit",
    cost: 6,
    power: 5,
    health: 5,
    race: "Voidling",
    keywords: ["Fearsome", "Lifesteal", "Elusive"],
    description: "Champion (Voidling) — Fearsome, Lifesteal & Elusive. Level Up: I've struck the Nexus twice.",
    rarity: "Legend",
    isLegend: true,
    isChampion: true,
    art: "/images/champs/malakar.jpg",
    emoji: "☠️",
    levelUp: {
      type: "nexusStrikes",
      amount: 2,
      toDefId: "void_champion_2",
      hint: "Strike the enemy Nexus twice",
    },
  },
  void_champion_2: {
    defId: "void_champion_2",
    name: "Malakar, Hunger Eternal",
    region: "Voidborn",
    type: "Unit",
    cost: 6,
    power: 6,
    health: 6,
    keywords: ["Fearsome", "Lifesteal", "Elusive", "Overwhelm"],
    description: "Leveled — Fearsome, Lifesteal, Elusive, Overwhelm. Strike: draw 1.",
    rarity: "Legend",
    isLegend: true,
    isChampion: true,
    collectible: false,
    art: "/images/champs/malakar.jpg",
    emoji: "☠️",
    trigger: { when: "onStrike", effect: { kind: "draw", amount: 1, target: "none" } },
  },
  void_drain: {
    defId: "void_drain",
    name: "Life Siphon",
    region: "Voidborn",
    type: "Spell",
    cost: 3,
    description: "Deal 3 damage to a unit; restore 3 to your Nexus.",
    rarity: "Rare",
    emoji: "🩸",
    spell: {
      kind: "damageUnit",
      amount: 3,
      target: "anyUnit",
      also: { kind: "healNexus", amount: 3, target: "none" },
    },
  },
  void_barrier: {
    defId: "void_barrier",
    name: "Shadow Ward",
    region: "Voidborn",
    type: "Spell",
    cost: 2,
    description: "Grant a unit Barrier.",
    rarity: "Common",
    emoji: "🌑",
    spell: { kind: "grantBarrier", amount: 0, target: "allyUnit" },
  },
  void_veil: {
    defId: "void_veil",
    name: "Gloom Veil",
    region: "Voidborn",
    type: "Spell",
    cost: 3,
    description: "Burst — give a unit -2/-2.",
    rarity: "Rare",
    speed: "Burst",
    emoji: "🌫️",
    spell: { kind: "buffUnit", amount: 0, buffPower: -2, buffHealth: -2, target: "allyUnit" },
  },
  void_whisper: {
    defId: "void_whisper",
    name: "Voidling Whisperer",
    region: "Voidborn",
    type: "Unit",
    cost: 2,
    power: 2,
    health: 2,
    race: "Voidling",
    keywords: ["Fearsome"],
    description: "Voidling. Fearsome. Rally: all Voidlings get +1/+0.",
    rarity: "Rare",
    emoji: "👁",
    trigger: {
      when: "onSummon",
      effect: { kind: "buffAllies", amount: 0, buffPower: 1, buffHealth: 0, target: "none", race: "Voidling" },
    },
  },
  void_harvester: {
    defId: "void_harvester",
    name: "Void Harvester",
    region: "Voidborn",
    type: "Unit",
    cost: 4,
    power: 4,
    health: 4,
    race: "Voidling",
    keywords: ["Lifesteal"],
    description: "Voidling. Lifesteal. Kill: draw 1.",
    rarity: "Rare",
    emoji: "👁‍🗨",
    trigger: { when: "onKill", effect: { kind: "draw", amount: 1, target: "none" } },
  },
  void_siphon: {
    defId: "void_siphon",
    name: "Soul Siphon",
    region: "Voidborn",
    type: "Enchantment",
    cost: 3,
    maxHealth: 3,
    description: "Round Start: all Voidlings get +1/+0 and Lifesteal.",
    rarity: "Rare",
    emoji: "🩸",
    trigger: {
      when: "onRoundStart",
      effect: {
        kind: "buffAllies",
        amount: 0,
        buffPower: 1,
        buffHealth: 0,
        target: "none",
        race: "Voidling",
        also: {
          kind: "grantKeyword",
          amount: 0,
          keyword: "Lifesteal",
          target: "none",
          race: "Voidling",
        },
      },
    },
  },
  void_scythe: {
    defId: "void_scythe",
    name: "Gloom Scythe",
    region: "Voidborn",
    type: "Equipment",
    cost: 3,
    equipment: { buffPower: 3, buffHealth: 0, keywords: ["Lifesteal"] },
    description: "Equip: +3/+0 and Lifesteal.",
    rarity: "Rare",
    emoji: "⚰️",
  },
  void_cloak: {
    defId: "void_cloak",
    name: "Shadowmantle",
    region: "Voidborn",
    type: "Equipment",
    cost: 2,
    equipment: { buffPower: 0, buffHealth: 2, keywords: ["Elusive"] },
    description: "Equip: +0/+2 and Elusive.",
    rarity: "Common",
    emoji: "🧥",
  },
  void_ember_herald: {
    defId: "void_ember_herald",
    name: "Ashen Herald",
    region: "Voidborn",
    type: "Unit",
    cost: 3,
    power: 3,
    health: 2,
    race: "Voidling",
    secondaryRaces: ["Dragon"],
    keywords: ["QuickAttack"],
    description: "Voidling/Dragon. Play: deal 1 to the enemy Nexus, then draw 1 if you control a Dragon or Voidling.",
    rarity: "Rare",
    emoji: "🔥",
    trigger: {
      when: "onSummon",
      effect: {
        kind: "damageNexus",
        amount: 1,
        target: "none",
        also: {
          kind: "draw",
          amount: 1,
          target: "none",
          races: ["Dragon", "Voidling"],
        },
      },
    },
  },
  void_reaper_edge: {
    defId: "void_reaper_edge",
    name: "Reaper's Edge",
    region: "Voidborn",
    type: "Equipment",
    cost: 4,
    equipment: { buffPower: 3, buffHealth: 1, keywords: ["Lifesteal", "Fearsome"] },
    description: "Equip: +3/+1, Lifesteal and Fearsome. Kill: deal 2 to the enemy Nexus.",
    rarity: "Epic",
    emoji: "☠️",
    trigger: {
      when: "onKill",
      effect: { kind: "damageNexus", amount: 2, target: "none" },
    },
  },
  void_unmake: {
    defId: "void_unmake",
    name: "Unmake",
    region: "Voidborn",
    type: "Spell",
    cost: 3,
    description: "Destroy an enemy permanent, then restore 2 to your Nexus.",
    rarity: "Rare",
    emoji: "🌑",
    spell: {
      kind: "destroyPermanent",
      amount: 0,
      target: "enemyPermanent",
      also: { kind: "healNexus", amount: 2, target: "none" },
    },
  },
  void_ghost: {
    defId: "void_ghost",
    name: "Fading Wraith",
    region: "Voidborn",
    type: "Unit",
    cost: 3,
    power: 5,
    health: 3,
    race: "Voidling",
    keywords: ["Ephemeral", "Fearsome"],
    description: "Voidling. Ephemeral & Fearsome. A terrifying presence that won't last.",
    rarity: "Rare",
    emoji: "👻",
  },
  void_deathmark: {
    defId: "void_deathmark",
    name: "Death Mark",
    region: "Voidborn",
    type: "Spell",
    cost: 5,
    description: "Destroy an enemy unit.",
    rarity: "Epic",
    emoji: "💀",
    spell: { kind: "killUnit", amount: 0, target: "enemyUnit" },
  },
  void_disrupt: {
    defId: "void_disrupt",
    name: "Gloom Void",
    region: "Voidborn",
    type: "Spell",
    cost: 3,
    description: "Burst — Negate an active spell on the stack, then draw 1.",
    rarity: "Rare",
    speed: "Burst",
    emoji: "✖️",
    spell: {
      kind: "negateSpell",
      amount: 0,
      target: "spellOnStack",
      also: { kind: "draw", amount: 1, target: "none" },
    },
  },
  void_assassin: {
    defId: "void_assassin",
    name: "Venomspine Assassin",
    region: "Voidborn",
    type: "Unit",
    cost: 3,
    power: 2,
    health: 2,
    race: "Voidling",
    keywords: ["Deathtouch"],
    description: "Voidling. Deathtouch — any damage it deals to a unit destroys it.",
    rarity: "Rare",
    emoji: "🗡️",
  },
  void_toxomancer: {
    defId: "void_toxomancer",
    name: "Toxomancer",
    region: "Voidborn",
    type: "Unit",
    cost: 4,
    power: 3,
    health: 3,
    race: "Voidling",
    keywords: ["Poisonous"],
    description: "Voidling. Poisonous — combat damage dealt straight to the enemy Nexus also gives that many poison counters. 10 poison counters = defeat.",
    rarity: "Epic",
    emoji: "🧪",
  },
  void_wither: {
    defId: "void_wither",
    name: "Blight Witherer",
    region: "Voidborn",
    type: "Unit",
    cost: 5,
    power: 4,
    health: 5,
    race: "Voidling",
    keywords: ["Wither"],
    description: "Voidling. Wither — its damage permanently reduces max health.",
    rarity: "Epic",
    emoji: "🥀",
  },
  void_venom: {
    defId: "void_venom",
    name: "Venom Spit",
    region: "Voidborn",
    type: "Spell",
    cost: 2,
    description: "Give the enemy 2 poison counters (cumulative — 10 poison counters is a loss).",
    rarity: "Rare",
    emoji: "💚",
    spell: { kind: "poison", amount: 2, target: "none" },
  },
  void_giantkiller: {
    defId: "void_giantkiller",
    name: "Giant-Killer",
    region: "Voidborn",
    type: "Unit",
    cost: 9,
    power: 6,
    health: 6,
    race: "Warrior",
    keywords: ["Deathtouch", "Fearsome"],
    description: "Warrior. Affinity — costs 2 less for each unit you control with 4+ power.",
    rarity: "Legend",
    isLegend: true,
    emoji: "🪓",
    costReduction: { kind: "power", per: 2, threshold: 4, max: 6 },
  },
  sent_xerath: {
    defId: "sent_xerath",
    name: "Xerath, Sussurro do Vazio",
    region: "Voidborn",
    type: "Sentinela",
    cost: 6,
    description: "Sentinela — drena a essência dos inimigos.",
    rarity: "Legend",
    isLegend: true,
    emoji: "💀",
    sentinela: {
      startingLoyalty: 4,
      abilities: [
        { cost: 1, description: "+1: dá 1 contador de veneno ao inimigo (10 contadores = derrota)", effect: { kind: "poison", amount: 1, target: "none" } },
        { cost: -3, description: "-3: destrói uma criatura inimiga", effect: { kind: "killUnit", amount: 0, target: "enemyUnit" } },
        { cost: -7, description: "-7: cura 8 de vida do seu Nexus", effect: { kind: "healNexus", amount: 8, target: "none" } },
      ],
    },
  },
  void_shadowstalker: {
    defId: "void_shadowstalker",
    name: "Perseguidor Sombrio",
    region: "Voidborn",
    type: "Unit",
    cost: 3,
    power: 3,
    health: 2,
    race: "Voidling",
    keywords: ["Elusive"],
    description: "Voidling. Evasivo.",
    rarity: "Common",
    emoji: "🌑",
  },
  void_soulsucker: {
    defId: "void_soulsucker",
    name: "Sugador de Almas",
    region: "Voidborn",
    type: "Unit",
    cost: 4,
    power: 3,
    health: 4,
    race: "Voidling",
    keywords: ["Lifesteal"],
    description: "Voidling. Vampírico.",
    rarity: "Rare",
    emoji: "🩸",
  },
  void_nightmare: {
    defId: "void_nightmare",
    name: "Pesadelo Vivo",
    region: "Voidborn",
    type: "Unit",
    cost: 5,
    power: 5,
    health: 3,
    race: "Voidling",
    keywords: ["Fearsome", "Deathtouch"],
    description: "Voidling. Assustador & Toque Mortal.",
    rarity: "Epic",
    emoji: "👹",
  },
  void_specter: {
    defId: "void_specter",
    name: "Espectro do Abismo",
    region: "Voidborn",
    type: "Unit",
    cost: 2,
    power: 2,
    health: 1,
    race: "Voidling",
    keywords: ["LastBreath"],
    description: "Voidling. Último Suspiro: causa 1 de dano ao Nexus inimigo.",
    rarity: "Common",
    emoji: "👻",
    trigger: { when: "onDeath", effect: { kind: "damageNexus", amount: 1, target: "none" } },
  },
  void_voidmage: {
    defId: "void_voidmage",
    name: "Maga do Vazio",
    region: "Voidborn",
    type: "Unit",
    cost: 4,
    power: 2,
    health: 4,
    race: "Spirit",
    keywords: ["Hexproof"],
    description: "Espírito. Hexproof.",
    rarity: "Rare",
    emoji: "🔮",
  },
  void_gloom_warden: {
    defId: "void_gloom_warden", name: "Vigia da Penumbra", region: "Voidborn", type: "Unit", cost: 3, power: 3, health: 3,
    race: "Spirit", keywords: ["Fearsome", "Hexproof"], description: "Espírito. Assustador e Hexproof.", rarity: "Rare", emoji: "🌑",
  },
  void_soul_tax: {
    defId: "void_soul_tax", name: "Tributo da Alma", region: "Voidborn", type: "Spell", cost: 3,
    description: "Cause 2 a uma unidade inimiga e cure 2 do seu Nexus.", rarity: "Rare", emoji: "🩸", speed: "Fast",
    spell: { kind: "damageUnit", amount: 2, target: "enemyUnit", also: { kind: "healNexus", amount: 2, target: "none" } },
  },
  convergence_nightpack_stalker: {
    defId: "convergence_nightpack_stalker", name: "Espreitador da Matilha Sombria", region: "Voidborn", regions: ["Voidborn", "Florestia"], regionalPerk: "assault",
    type: "Unit", cost: 3, power: 3, health: 3, race: "Besta", keywords: ["Fearsome"], description: "A matilha caça até os medos que tentam fugir.", rarity: "Rare", emoji: "🐾", strategicRole: "tempo", doctrineAffinities: ["convergence_dual"],
  },
  convergence_eclipse_herald: {
    defId: "convergence_eclipse_herald", name: "Arauto do Eclipse Elétrico", region: "Voidborn", regions: ["Voidborn", "Tempestade"], regionalPerk: "convergence",
    type: "Unit", cost: 4, power: 4, health: 3, race: "Anjo", keywords: ["Flying"], description: "O céu escurece um instante antes do impacto.", rarity: "Epic", emoji: "🌘", strategicRole: "finisher", doctrineAffinities: ["convergence_dual"],
  },
  nexus_gargoyle: {
    defId: "nexus_gargoyle",
    name: "Gárgula do Nexus",
    region: "Voidborn",
    type: "Unit",
    cost: 3,
    power: 2,
    health: 4,
    race: "Elemental",
    keywords: ["Barrier"],
    description: "Elemental. Barreira.",
    rarity: "Common",
    emoji: "🗿",
  },
};
